// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AdminDashboard struct {
	TotalUsers       int     `json:"totalUsers"`
	ActiveUsersToday int     `json:"activeUsersToday"`
	ActiveUsersMonth int     `json:"activeUsersMonth"`
	TotalRevenue     Money   `json:"totalRevenue"`
	RevenueThisMonth Money   `json:"revenueThisMonth"`
	TotalRequests    int     `json:"totalRequests"`
	RequestsToday    int     `json:"requestsToday"`
	TotalTokens      int     `json:"totalTokens"`
	TokensToday      int     `json:"tokensToday"`
	TotalCost        Money   `json:"totalCost"`
	CostToday        Money   `json:"costToday"`
	SuccessRate      float64 `json:"successRate"`
	ErrorCount       int     `json:"errorCount"`
	AvgLatencyMs     float64 `json:"avgLatencyMs"`
	ActiveProviders  int     `json:"activeProviders"`
	TotalProviders   int     `json:"totalProviders"`
	ActiveProxies    int     `json:"activeProxies"`
	TotalProxies     int     `json:"totalProxies"`
	APIKeysTotal     int     `json:"apiKeysTotal"`
	APIKeysHealthy   int     `json:"apiKeysHealthy"`
	McpCallCount     int     `json:"mcpCallCount"`
	McpErrorCount    int     `json:"mcpErrorCount"`
}

type AdminUsageByUser struct {
	UserID   string `json:"userId"`
	UserName string `json:"userName"`
	Email    string `json:"email"`
	Requests int    `json:"requests"`
	Tokens   int    `json:"tokens"`
	Cost     Money  `json:"cost"`
}

type Alert struct {
	ID             string     `json:"id"`
	TargetType     string     `json:"targetType"`
	TargetID       string     `json:"targetId"`
	AlertType      string     `json:"alertType"`
	Message        string     `json:"message"`
	Status         string     `json:"status"`
	ResolvedAt     *time.Time `json:"resolvedAt,omitempty"`
	AcknowledgedAt *time.Time `json:"acknowledgedAt,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
}

type AlertConfig struct {
	ID                 *string `json:"id,omitempty"`
	TargetType         string  `json:"targetType"`
	TargetID           string  `json:"targetId"`
	IsEnabled          bool    `json:"isEnabled"`
	FailureThreshold   int     `json:"failureThreshold"`
	ErrorRateThreshold float64 `json:"errorRateThreshold"`
	LatencyThresholdMs int     `json:"latencyThresholdMs"`
	BudgetThreshold    float64 `json:"budgetThreshold"`
	CooldownMinutes    int     `json:"cooldownMinutes"`
	WebhookURL         *string `json:"webhookUrl,omitempty"`
	Email              *string `json:"email,omitempty"`
}

type AlertConfigInput struct {
	TargetType         string   `json:"targetType"`
	TargetID           string   `json:"targetId"`
	IsEnabled          bool     `json:"isEnabled"`
	FailureThreshold   int      `json:"failureThreshold"`
	ErrorRateThreshold *float64 `json:"errorRateThreshold,omitempty"`
	LatencyThresholdMs *int     `json:"latencyThresholdMs,omitempty"`
	BudgetThreshold    *float64 `json:"budgetThreshold,omitempty"`
	CooldownMinutes    *int     `json:"cooldownMinutes,omitempty"`
	WebhookURL         *string  `json:"webhookUrl,omitempty"`
	Email              *string  `json:"email,omitempty"`
}

type AlertConnection struct {
	Data  []*Alert `json:"data"`
	Total int      `json:"total"`
}

type Announcement struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	Content   string     `json:"content"`
	Type      string     `json:"type"`
	Priority  int        `json:"priority"`
	IsActive  bool       `json:"isActive"`
	StartsAt  *time.Time `json:"startsAt,omitempty"`
	EndsAt    *time.Time `json:"endsAt,omitempty"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

type AnnouncementInput struct {
	Title    string     `json:"title"`
	Content  string     `json:"content"`
	Type     *string    `json:"type,omitempty"`
	Priority *int       `json:"priority,omitempty"`
	IsActive *bool      `json:"isActive,omitempty"`
	StartsAt *time.Time `json:"startsAt,omitempty"`
	EndsAt   *time.Time `json:"endsAt,omitempty"`
}

type AnomalyResult struct {
	HasAnomaly bool    `json:"hasAnomaly"`
	Message    *string `json:"message,omitempty"`
	Details    *string `json:"details,omitempty"`
}

type APIKey struct {
	ID               string     `json:"id"`
	ProjectID        string     `json:"projectId"`
	Channel          string     `json:"channel"`
	Name             string     `json:"name"`
	KeyPrefix        string     `json:"keyPrefix"`
	IsActive         bool       `json:"isActive"`
	Scopes           string     `json:"scopes"`
	AllowedModels    []string   `json:"allowedModels"`
	AllowedProviders []string   `json:"allowedProviders"`
	RateLimit        int        `json:"rateLimit"`
	TokenLimit       int        `json:"tokenLimit"`
	DailyLimit       int        `json:"dailyLimit"`
	ExpiresAt        *time.Time `json:"expiresAt,omitempty"`
	LastUsedAt       *time.Time `json:"lastUsedAt,omitempty"`
	CreatedAt        time.Time  `json:"createdAt"`
}

type APIKeyHealth struct {
	ID           string     `json:"id"`
	ProviderID   string     `json:"providerId"`
	ProviderName string     `json:"providerName"`
	KeyPrefix    string     `json:"keyPrefix"`
	IsActive     bool       `json:"isActive"`
	IsHealthy    bool       `json:"isHealthy"`
	LastCheck    *time.Time `json:"lastCheck,omitempty"`
	ResponseTime float64    `json:"responseTime"`
	SuccessRate  float64    `json:"successRate"`
}

type APIKeyRateLimitStatus struct {
	KeyID         string `json:"keyId"`
	RpmCurrent    int    `json:"rpmCurrent"`
	RpmLimit      int    `json:"rpmLimit"`
	RpmExceeded   bool   `json:"rpmExceeded"`
	TpmCurrent    int    `json:"tpmCurrent"`
	TpmLimit      int    `json:"tpmLimit"`
	TpmExceeded   bool   `json:"tpmExceeded"`
	DailyCurrent  int    `json:"dailyCurrent"`
	DailyLimit    int    `json:"dailyLimit"`
	DailyExceeded bool   `json:"dailyExceeded"`
	Status        string `json:"status"`
	StatusReason  string `json:"statusReason"`
}

type APIKeyWithSecret struct {
	ID               string     `json:"id"`
	ProjectID        string     `json:"projectId"`
	Channel          string     `json:"channel"`
	Name             string     `json:"name"`
	Key              string     `json:"key"`
	KeyPrefix        string     `json:"keyPrefix"`
	IsActive         bool       `json:"isActive"`
	Scopes           string     `json:"scopes"`
	AllowedModels    []string   `json:"allowedModels"`
	AllowedProviders []string   `json:"allowedProviders"`
	RateLimit        int        `json:"rateLimit"`
	TokenLimit       int        `json:"tokenLimit"`
	DailyLimit       int        `json:"dailyLimit"`
	ExpiresAt        *time.Time `json:"expiresAt,omitempty"`
	CreatedAt        time.Time  `json:"createdAt"`
}

type APIKeysSummary struct {
	Total   int `json:"total"`
	Healthy int `json:"healthy"`
}

type AuditLog struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	Action    string    `json:"action"`
	ActorID   string    `json:"actorId"`
	TargetID  string    `json:"targetId"`
	IP        string    `json:"ip"`
	UserAgent string    `json:"userAgent"`
	Detail    string    `json:"detail"`
}

type AuditLogConnection struct {
	Data     []*AuditLog `json:"data"`
	Total    int         `json:"total"`
	Page     int         `json:"page"`
	PageSize int         `json:"pageSize"`
}

type AuthPayload struct {
	Token                 string  `json:"token"`
	RefreshToken          *string `json:"refreshToken,omitempty"`
	User                  *User   `json:"user"`
	EmailVerificationSent *bool   `json:"emailVerificationSent,omitempty"`
}

type BackupRecord struct {
	ID           string     `json:"id"`
	Type         string     `json:"type"`
	Status       string     `json:"status"`
	SizeBytes    int        `json:"sizeBytes"`
	DurationMs   int        `json:"durationMs"`
	Destination  string     `json:"destination"`
	ErrorMessage *string    `json:"errorMessage,omitempty"`
	StartedAt    time.Time  `json:"startedAt"`
	CompletedAt  *time.Time `json:"completedAt,omitempty"`
}

type BackupStatus struct {
	LastBackup      *BackupRecord   `json:"lastBackup,omitempty"`
	Records         []*BackupRecord `json:"records"`
	IsConfigured    bool            `json:"isConfigured"`
	ScheduleEnabled bool            `json:"scheduleEnabled"`
	NextScheduled   *time.Time      `json:"nextScheduled,omitempty"`
}

type BatchProxyInput struct {
	Proxies []*BatchProxyItem `json:"proxies"`
	PoolID  *string           `json:"poolId,omitempty"`
}

type BatchProxyItem struct {
	URL    string  `json:"url"`
	Type   *string `json:"type,omitempty"`
	Region *string `json:"region,omitempty"`
}

type BatchProxyResult struct {
	Success int      `json:"success"`
	Failed  int      `json:"failed"`
	Proxies []*Proxy `json:"proxies"`
	Errors  []string `json:"errors,omitempty"`
}

type Budget struct {
	ID               string  `json:"id"`
	OrgID            string  `json:"orgId"`
	MonthlyLimitUsd  Money   `json:"monthlyLimitUsd"`
	AlertThreshold   float64 `json:"alertThreshold"`
	EnforceHardLimit bool    `json:"enforceHardLimit"`
	IsActive         bool    `json:"isActive"`
	WebhookURL       *string `json:"webhookUrl,omitempty"`
	Email            *string `json:"email,omitempty"`
}

type BudgetInput struct {
	MonthlyLimitUsd  Money    `json:"monthlyLimitUsd"`
	AlertThreshold   *float64 `json:"alertThreshold,omitempty"`
	EnforceHardLimit *bool    `json:"enforceHardLimit,omitempty"`
	WebhookURL       *string  `json:"webhookUrl,omitempty"`
	Email            *string  `json:"email,omitempty"`
}

type BudgetStatus struct {
	Budget          *Budget `json:"budget,omitempty"`
	CurrentSpend    Money   `json:"currentSpend"`
	RemainingBudget Money   `json:"remainingBudget"`
	PercentUsed     float64 `json:"percentUsed"`
	IsOverBudget    bool    `json:"isOverBudget"`
}

type CacheConfig struct {
	ID                  string  `json:"id"`
	IsEnabled           bool    `json:"isEnabled"`
	SimilarityThreshold float64 `json:"similarityThreshold"`
	DefaultTTLMinutes   int     `json:"defaultTtlMinutes"`
	EmbeddingModel      string  `json:"embeddingModel"`
	MaxCacheSize        int     `json:"maxCacheSize"`
}

type CacheConfigInput struct {
	IsEnabled           bool    `json:"isEnabled"`
	SimilarityThreshold float64 `json:"similarityThreshold"`
	DefaultTTLMinutes   int     `json:"defaultTtlMinutes"`
	EmbeddingModel      string  `json:"embeddingModel"`
	MaxCacheSize        int     `json:"maxCacheSize"`
}

type CacheStats struct {
	TotalCaches int `json:"totalCaches"`
	TotalHits   int `json:"totalHits"`
}

type CaptchaConfig struct {
	Enabled bool   `json:"enabled"`
	SiteKey string `json:"siteKey"`
}

type ChangePasswordInput struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type CheckoutSession struct {
	URL string `json:"url"`
}

type Coupon struct {
	ID             string     `json:"id"`
	Code           string     `json:"code"`
	Name           string     `json:"name"`
	Type           string     `json:"type"`
	DiscountValue  Money      `json:"discountValue"`
	MinAmount      Money      `json:"minAmount"`
	MaxUses        int        `json:"maxUses"`
	UseCount       int        `json:"useCount"`
	MaxUsesPerUser int        `json:"maxUsesPerUser"`
	IsActive       bool       `json:"isActive"`
	ExpiresAt      *time.Time `json:"expiresAt,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
}

type CouponInput struct {
	Code           string     `json:"code"`
	Name           string     `json:"name"`
	Type           string     `json:"type"`
	DiscountValue  Money      `json:"discountValue"`
	MinAmount      *Money     `json:"minAmount,omitempty"`
	MaxUses        *int       `json:"maxUses,omitempty"`
	MaxUsesPerUser *int       `json:"maxUsesPerUser,omitempty"`
	IsActive       *bool      `json:"isActive,omitempty"`
	ExpiresAt      *time.Time `json:"expiresAt,omitempty"`
}

type CreateIdentityProviderInput struct {
	OrgID            string  `json:"orgId"`
	Type             string  `json:"type"`
	Name             string  `json:"name"`
	Domains          string  `json:"domains"`
	OidcClientID     *string `json:"oidcClientId,omitempty"`
	OidcClientSecret *string `json:"oidcClientSecret,omitempty"`
	OidcIssuerURL    *string `json:"oidcIssuerUrl,omitempty"`
	SamlEntityID     *string `json:"samlEntityId,omitempty"`
	SamlSsoURL       *string `json:"samlSsoUrl,omitempty"`
	SamlIdpCert      *string `json:"samlIdpCert,omitempty"`
	EnableJit        *bool   `json:"enableJit,omitempty"`
	DefaultRole      *string `json:"defaultRole,omitempty"`
	GroupRoleMapping *string `json:"groupRoleMapping,omitempty"`
}

type CreateProviderInput struct {
	Name           string   `json:"name"`
	BaseURL        string   `json:"baseUrl"`
	IsActive       *bool    `json:"isActive,omitempty"`
	Priority       *int     `json:"priority,omitempty"`
	Weight         *float64 `json:"weight,omitempty"`
	MaxRetries     *int     `json:"maxRetries,omitempty"`
	Timeout        *int     `json:"timeout,omitempty"`
	UseProxy       *bool    `json:"useProxy,omitempty"`
	RequiresAPIKey *bool    `json:"requiresApiKey,omitempty"`
}

type CreateRoutingRuleInput struct {
	Name               string  `json:"name"`
	Description        *string `json:"description,omitempty"`
	ModelPattern       string  `json:"modelPattern"`
	TargetProviderID   string  `json:"targetProviderId"`
	FallbackProviderID *string `json:"fallbackProviderId,omitempty"`
	Priority           int     `json:"priority"`
	IsEnabled          bool    `json:"isEnabled"`
}

type CreateTaskInput struct {
	Type       string  `json:"type"`
	Input      string  `json:"input"`
	WebhookURL *string `json:"webhookUrl,omitempty"`
}

type CreateWebhookEndpointInput struct {
	ProjectID   string   `json:"projectId"`
	URL         string   `json:"url"`
	Events      []string `json:"events"`
	IsActive    *bool    `json:"isActive,omitempty"`
	Description *string  `json:"description,omitempty"`
}

type DailyStats struct {
	Date        string `json:"date"`
	Requests    int    `json:"requests"`
	TotalTokens int    `json:"totalTokens"`
	TotalCost   Money  `json:"totalCost"`
}

type Dashboard struct {
	TotalRequests    int             `json:"totalRequests"`
	SuccessRate      float64         `json:"successRate"`
	TotalTokens      int             `json:"totalTokens"`
	TotalCost        Money           `json:"totalCost"`
	AverageLatencyMs float64         `json:"averageLatencyMs"`
	ActiveUsers      int             `json:"activeUsers"`
	ActiveProviders  int             `json:"activeProviders"`
	ActiveProxies    int             `json:"activeProxies"`
	RequestsToday    int             `json:"requestsToday"`
	CostToday        Money           `json:"costToday"`
	TokensToday      int             `json:"tokensToday"`
	ErrorCount       int             `json:"errorCount"`
	McpCallCount     int             `json:"mcpCallCount"`
	McpErrorCount    int             `json:"mcpErrorCount"`
	APIKeys          *APIKeysSummary `json:"apiKeys"`
	Proxies          *ProxiesSummary `json:"proxies"`
}

type DatabaseLoad struct {
	ActiveConnections     int     `json:"activeConnections"`
	MaxConnections        int     `json:"maxConnections"`
	PoolIdle              int     `json:"poolIdle"`
	PoolInUse             int     `json:"poolInUse"`
	TransactionsPerSecond float64 `json:"transactionsPerSecond"`
	CacheHitRate          float64 `json:"cacheHitRate"`
	Deadlocks             int     `json:"deadlocks"`
}

type DependencyStatus struct {
	Name      string  `json:"name"`
	Status    string  `json:"status"`
	LatencyMs float64 `json:"latencyMs"`
	Version   *string `json:"version,omitempty"`
	Details   *string `json:"details,omitempty"`
}

type DlpConfig struct {
	ID              string      `json:"id"`
	ProjectID       string      `json:"projectId"`
	IsEnabled       bool        `json:"isEnabled"`
	Strategy        DlpStrategy `json:"strategy"`
	MaskEmails      bool        `json:"maskEmails"`
	MaskPhones      bool        `json:"maskPhones"`
	MaskCreditCards bool        `json:"maskCreditCards"`
	MaskSsn         bool        `json:"maskSsn"`
	MaskAPIKeys     bool        `json:"maskApiKeys"`
	CustomRegex     []string    `json:"customRegex"`
	CreatedAt       time.Time   `json:"createdAt"`
	UpdatedAt       time.Time   `json:"updatedAt"`
}

type DlpTestResult struct {
	OriginalText string `json:"originalText"`
	ScrubbedText string `json:"scrubbedText"`
	HasPii       bool   `json:"hasPii"`
	Blocked      bool   `json:"blocked"`
}

type Document struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Slug        string    `json:"slug"`
	Content     string    `json:"content"`
	Category    string    `json:"category"`
	SortOrder   int       `json:"sortOrder"`
	IsPublished bool      `json:"isPublished"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type DocumentInput struct {
	Title       string  `json:"title"`
	Slug        string  `json:"slug"`
	Content     string  `json:"content"`
	Category    *string `json:"category,omitempty"`
	SortOrder   *int    `json:"sortOrder,omitempty"`
	IsPublished *bool   `json:"isPublished,omitempty"`
}

type ErrorLog struct {
	ID           string    `json:"id"`
	TrajectoryID string    `json:"trajectoryId"`
	TraceID      string    `json:"traceId"`
	Provider     string    `json:"provider"`
	Model        string    `json:"model"`
	StatusCode   int       `json:"statusCode"`
	Headers      string    `json:"headers"`
	ResponseBody string    `json:"responseBody"`
	CreatedAt    time.Time `json:"createdAt"`
}

type ErrorLogConnection struct {
	Data     []*ErrorLog `json:"data"`
	Total    int         `json:"total"`
	Page     int         `json:"page"`
	PageSize int         `json:"pageSize"`
}

type FeatureGate struct {
	Name        string `json:"name"`
	Enabled     bool   `json:"enabled"`
	Category    string `json:"category"`
	Description string `json:"description"`
	Source      string `json:"source"`
}

type FinancialBreakdown struct {
	Name   string `json:"name"`
	Amount Money  `json:"amount"`
	Count  int    `json:"count"`
}

type FinancialDailyPoint struct {
	Date         string `json:"date"`
	CashRevenue  Money  `json:"cashRevenue"`
	UsageRevenue Money  `json:"usageRevenue"`
	ProviderCost Money  `json:"providerCost"`
	GrossProfit  Money  `json:"grossProfit"`
	Orders       int    `json:"orders"`
	Requests     int    `json:"requests"`
}

type FinancialDashboard struct {
	PeriodStart         time.Time                     `json:"periodStart"`
	PeriodEnd           time.Time                     `json:"periodEnd"`
	CashRevenue         Money                         `json:"cashRevenue"`
	NetCashRevenue      Money                         `json:"netCashRevenue"`
	SubscriptionRevenue Money                         `json:"subscriptionRevenue"`
	TopUpRevenue        Money                         `json:"topUpRevenue"`
	UsageRevenue        Money                         `json:"usageRevenue"`
	ProviderCost        Money                         `json:"providerCost"`
	GrossProfit         Money                         `json:"grossProfit"`
	GrossMargin         float64                       `json:"grossMargin"`
	RefundAmount        Money                         `json:"refundAmount"`
	CreditGrants        Money                         `json:"creditGrants"`
	OutstandingBalance  Money                         `json:"outstandingBalance"`
	PaidOrders          int                           `json:"paidOrders"`
	ActiveSubscriptions int                           `json:"activeSubscriptions"`
	PayingCustomers     int                           `json:"payingCustomers"`
	Arpu                Money                         `json:"arpu"`
	Daily               []*FinancialDailyPoint        `json:"daily"`
	PaymentBreakdown    []*FinancialBreakdown         `json:"paymentBreakdown"`
	ProviderBreakdown   []*FinancialProviderBreakdown `json:"providerBreakdown"`
}

type FinancialProviderBreakdown struct {
	ProviderName string  `json:"providerName"`
	Requests     int     `json:"requests"`
	UsageRevenue Money   `json:"usageRevenue"`
	ProviderCost Money   `json:"providerCost"`
	GrossProfit  Money   `json:"grossProfit"`
	GrossMargin  float64 `json:"grossMargin"`
}

type GenerateRedeemCodesInput struct {
	Type         string     `json:"type"`
	CreditAmount *Money     `json:"creditAmount,omitempty"`
	PlanID       *string    `json:"planId,omitempty"`
	PlanDays     *int       `json:"planDays,omitempty"`
	Count        int        `json:"count"`
	ExpiresAt    *time.Time `json:"expiresAt,omitempty"`
	Note         *string    `json:"note,omitempty"`
}

type GenerateRedeemCodesResult struct {
	Codes []string `json:"codes"`
	Count int      `json:"count"`
}

type HealthEvent struct {
	ID         string    `json:"id"`
	TargetType string    `json:"targetType"`
	TargetID   string    `json:"targetId"`
	Status     string    `json:"status"`
	Message    *string   `json:"message,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
}

type IdentityProvider struct {
	ID               string        `json:"id"`
	OrgID            string        `json:"orgId"`
	Organization     *Organization `json:"organization"`
	Type             string        `json:"type"`
	Name             string        `json:"name"`
	IsActive         bool          `json:"isActive"`
	Domains          string        `json:"domains"`
	OidcClientID     *string       `json:"oidcClientId,omitempty"`
	OidcIssuerURL    *string       `json:"oidcIssuerUrl,omitempty"`
	SamlEntityID     *string       `json:"samlEntityId,omitempty"`
	SamlSsoURL       *string       `json:"samlSsoUrl,omitempty"`
	SamlIdpCert      *string       `json:"samlIdpCert,omitempty"`
	EnableJit        bool          `json:"enableJit"`
	DefaultRole      string        `json:"defaultRole"`
	GroupRoleMapping string        `json:"groupRoleMapping"`
	CreatedAt        time.Time     `json:"createdAt"`
	UpdatedAt        time.Time     `json:"updatedAt"`
}

type IntegrationConfig struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Enabled   bool      `json:"enabled"`
	Config    string    `json:"config"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type InviteCode struct {
	ID        string     `json:"id"`
	Code      string     `json:"code"`
	CreatedBy string     `json:"createdBy"`
	MaxUses   int        `json:"maxUses"`
	UseCount  int        `json:"useCount"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	IsActive  bool       `json:"isActive"`
	CreatedAt time.Time  `json:"createdAt"`
}

type InviteCodeInput struct {
	MaxUses   *int       `json:"maxUses,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

type LogEntry struct {
	Timestamp  string   `json:"timestamp"`
	Level      string   `json:"level"`
	Message    string   `json:"message"`
	RequestID  *string  `json:"requestId,omitempty"`
	Caller     *string  `json:"caller,omitempty"`
	Error      *string  `json:"error,omitempty"`
	Method     *string  `json:"method,omitempty"`
	Path       *string  `json:"path,omitempty"`
	StatusCode *int     `json:"statusCode,omitempty"`
	Latency    *float64 `json:"latency,omitempty"`
	ClientIP   *string  `json:"clientIp,omitempty"`
	UserAgent  *string  `json:"userAgent,omitempty"`
	RawJSON    *string  `json:"rawJson,omitempty"`
}

type LoginInput struct {
	Email        string  `json:"email"`
	Password     string  `json:"password"`
	CaptchaToken *string `json:"captchaToken,omitempty"`
}

type McpEnvInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type McpResource struct {
	ID          string  `json:"id"`
	ServerID    string  `json:"serverId"`
	Name        string  `json:"name"`
	URI         string  `json:"uri"`
	Description *string `json:"description,omitempty"`
	MimeType    *string `json:"mimeType,omitempty"`
}

type McpServer struct {
	ID            string     `json:"id"`
	Name          string     `json:"name"`
	Type          string     `json:"type"`
	Command       *string    `json:"command,omitempty"`
	Args          []string   `json:"args,omitempty"`
	URL           *string    `json:"url,omitempty"`
	IsActive      bool       `json:"isActive"`
	Status        string     `json:"status"`
	LastError     *string    `json:"lastError,omitempty"`
	LastCheckedAt *time.Time `json:"lastCheckedAt,omitempty"`
	Tools         []*McpTool `json:"tools,omitempty"`
	CreatedAt     time.Time  `json:"createdAt"`
}

type McpServerInput struct {
	Name     string         `json:"name"`
	Type     string         `json:"type"`
	Command  *string        `json:"command,omitempty"`
	Args     []string       `json:"args,omitempty"`
	URL      *string        `json:"url,omitempty"`
	IsActive *bool          `json:"isActive,omitempty"`
	Env      []*McpEnvInput `json:"env,omitempty"`
}

type McpTool struct {
	ID          string  `json:"id"`
	ServerID    string  `json:"serverId"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	InputSchema *string `json:"inputSchema,omitempty"`
	IsActive    bool    `json:"isActive"`
}

type MfaSecretInfo struct {
	Secret      string   `json:"secret"`
	QRCodeURL   string   `json:"qrCodeUrl"`
	BackupCodes []string `json:"backupCodes"`
}

type Model struct {
	ID          string `json:"id"`
	ProviderID  string `json:"providerId"`
	Name        string `json:"name"`
	DisplayName string `json:"displayName"`
	// Capability classification for the model. Drives the admin grouping and
	// the Playground's STT/TTS dropdown filters (audit M-02, M-08).
	ModelKind               ModelKind `json:"modelKind"`
	InputPricePer1k         Money     `json:"inputPricePer1k"`
	OutputPricePer1k        Money     `json:"outputPricePer1k"`
	PricePerSecond          *Money    `json:"pricePerSecond,omitempty"`
	PricePerImage           *Money    `json:"pricePerImage,omitempty"`
	PricePerMinute          *Money    `json:"pricePerMinute,omitempty"`
	ProviderInputCostPer1k  Money     `json:"providerInputCostPer1k"`
	ProviderOutputCostPer1k Money     `json:"providerOutputCostPer1k"`
	ProviderCostPerSecond   *Money    `json:"providerCostPerSecond,omitempty"`
	ProviderCostPerImage    *Money    `json:"providerCostPerImage,omitempty"`
	ProviderCostPerMinute   *Money    `json:"providerCostPerMinute,omitempty"`
	// Total prompt+completion window the model accepts. Sourced from the
	// upstream provider's /v1/models response (audit M-07).
	ContextWindow int `json:"contextWindow"`
	// Per-request output cap. NULL when the upstream provider doesn't report
	// one — clients should fall back to a sensible default (e.g. 4096) rather
	// than treat NULL as "no cap".
	MaxOutputTokens *int `json:"maxOutputTokens,omitempty"`
	// Deprecated: legacy single-column representation of the context window.
	// Use contextWindow + maxOutputTokens. Kept for one release so existing
	// callers don't break during the migration.
	MaxTokens int `json:"maxTokens"`
	// Comma-or-space-separated warnings stamped by auto-sync. Currently the
	// only emitted value is "nsfw-or-dev-name"; admins can use it to surface a
	// warning badge in the catalog UI (audit L-05).
	CatalogWarnings string    `json:"catalogWarnings"`
	IsActive        bool      `json:"isActive"`
	CreatedAt       time.Time `json:"createdAt"`
}

type ModelInput struct {
	Name                    string     `json:"name"`
	DisplayName             *string    `json:"displayName,omitempty"`
	ModelKind               *ModelKind `json:"modelKind,omitempty"`
	InputPricePer1k         *Money     `json:"inputPricePer1k,omitempty"`
	OutputPricePer1k        *Money     `json:"outputPricePer1k,omitempty"`
	PricePerSecond          *Money     `json:"pricePerSecond,omitempty"`
	PricePerImage           *Money     `json:"pricePerImage,omitempty"`
	PricePerMinute          *Money     `json:"pricePerMinute,omitempty"`
	ProviderInputCostPer1k  *Money     `json:"providerInputCostPer1k,omitempty"`
	ProviderOutputCostPer1k *Money     `json:"providerOutputCostPer1k,omitempty"`
	ProviderCostPerSecond   *Money     `json:"providerCostPerSecond,omitempty"`
	ProviderCostPerImage    *Money     `json:"providerCostPerImage,omitempty"`
	ProviderCostPerMinute   *Money     `json:"providerCostPerMinute,omitempty"`
	ContextWindow           *int       `json:"contextWindow,omitempty"`
	MaxOutputTokens         *int       `json:"maxOutputTokens,omitempty"`
	MaxTokens               *int       `json:"maxTokens,omitempty"`
	IsActive                *bool      `json:"isActive,omitempty"`
}

type ModelStats struct {
	ModelID      string `json:"modelId"`
	ModelName    string `json:"modelName"`
	Requests     int    `json:"requests"`
	InputTokens  int    `json:"inputTokens"`
	OutputTokens int    `json:"outputTokens"`
	TotalCost    Money  `json:"totalCost"`
}

type Mutation struct {
}

type NotificationChannel struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	IsEnabled bool      `json:"isEnabled"`
	Config    string    `json:"config"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type NotificationChannelInput struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	IsEnabled *bool  `json:"isEnabled,omitempty"`
	Config    string `json:"config"`
}

type Order struct {
	ID            string    `json:"id"`
	OrderNo       string    `json:"orderNo"`
	Amount        Money     `json:"amount"`
	Currency      string    `json:"currency"`
	Status        string    `json:"status"`
	PaymentMethod string    `json:"paymentMethod"`
	CreatedAt     time.Time `json:"createdAt"`
	Plan          *Plan     `json:"plan,omitempty"`
}

type Organization struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	BillingLimit Money     `json:"billingLimit"`
	CreatedAt    time.Time `json:"createdAt"`
}

type OrganizationMember struct {
	UserID    string        `json:"userId"`
	OrgID     string        `json:"orgId"`
	Role      string        `json:"role"`
	User      *UserListItem `json:"user"`
	CreatedAt time.Time     `json:"createdAt"`
}

type PasswordPolicy struct {
	MinLength            int  `json:"minLength"`
	RequireLetter        bool `json:"requireLetter"`
	RequireDigit         bool `json:"requireDigit"`
	RequireUpper         bool `json:"requireUpper"`
	RequireLower         bool `json:"requireLower"`
	BlockCommonPasswords bool `json:"blockCommonPasswords"`
}

type Plan struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Description  string  `json:"description"`
	PriceMonth   Money   `json:"priceMonth"`
	TokenLimit   int     `json:"tokenLimit"`
	RateLimit    int     `json:"rateLimit"`
	SupportLevel string  `json:"supportLevel"`
	IsActive     bool    `json:"isActive"`
	Features     *string `json:"features,omitempty"`
}

type PlanInput struct {
	Name         string  `json:"name"`
	Description  *string `json:"description,omitempty"`
	PriceMonth   Money   `json:"priceMonth"`
	TokenLimit   int     `json:"tokenLimit"`
	RateLimit    int     `json:"rateLimit"`
	SupportLevel *string `json:"supportLevel,omitempty"`
	IsActive     *bool   `json:"isActive,omitempty"`
	Features     *string `json:"features,omitempty"`
}

type PlaygroundToken struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
	APIKeyID  string    `json:"apiKeyId"`
	ProjectID string    `json:"projectId"`
}

type Project struct {
	ID             string    `json:"id"`
	OrgID          string    `json:"orgId"`
	Name           string    `json:"name"`
	Description    *string   `json:"description,omitempty"`
	QuotaLimit     Money     `json:"quotaLimit"`
	WhiteListedIps *string   `json:"whiteListedIps,omitempty"`
	CreatedAt      time.Time `json:"createdAt"`
}

type PromptTemplate struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	Description     string         `json:"description"`
	ProjectID       *string        `json:"projectId,omitempty"`
	IsActive        bool           `json:"isActive"`
	ActiveVersionID *string        `json:"activeVersionId,omitempty"`
	ActiveVersion   *PromptVersion `json:"activeVersion,omitempty"`
	VersionCount    int            `json:"versionCount"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       time.Time      `json:"updatedAt"`
}

type PromptTemplateConnection struct {
	Data  []*PromptTemplate `json:"data"`
	Total int               `json:"total"`
}

type PromptTemplateInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	ProjectID   *string `json:"projectId,omitempty"`
	IsActive    *bool   `json:"isActive,omitempty"`
}

type PromptVersion struct {
	ID         string    `json:"id"`
	TemplateID string    `json:"templateId"`
	Version    int       `json:"version"`
	Content    string    `json:"content"`
	Model      *string   `json:"model,omitempty"`
	Parameters *string   `json:"parameters,omitempty"`
	ChangeLog  *string   `json:"changeLog,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
}

type PromptVersionInput struct {
	TemplateID string  `json:"templateId"`
	Content    string  `json:"content"`
	Model      *string `json:"model,omitempty"`
	Parameters *string `json:"parameters,omitempty"`
	ChangeLog  *string `json:"changeLog,omitempty"`
}

type Provider struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	BaseURL        string    `json:"baseUrl"`
	IsActive       bool      `json:"isActive"`
	Priority       int       `json:"priority"`
	Weight         float64   `json:"weight"`
	MaxRetries     int       `json:"maxRetries"`
	Timeout        int       `json:"timeout"`
	UseProxy       bool      `json:"useProxy"`
	DefaultProxyID *string   `json:"defaultProxyId,omitempty"`
	RequiresAPIKey bool      `json:"requiresApiKey"`
	CreatedAt      time.Time `json:"createdAt"`
}

type ProviderAccountTopologyNode struct {
	APIKey           *ProviderAPIKey           `json:"apiKey,omitempty"`
	Label            string                    `json:"label"`
	BindingSource    string                    `json:"bindingSource"`
	ProxyPool        *ProxyPool                `json:"proxyPool,omitempty"`
	CandidateProxies []*Proxy                  `json:"candidateProxies"`
	Route            []*ProxyTopologyRouteStep `json:"route"`
}

type ProviderAPIKey struct {
	ID          string     `json:"id"`
	ProviderID  string     `json:"providerId"`
	ProxyID     *string    `json:"proxyId,omitempty"`
	ProxyPoolID *string    `json:"proxyPoolId,omitempty"`
	Alias       string     `json:"alias"`
	KeyPrefix   string     `json:"keyPrefix"`
	IsActive    bool       `json:"isActive"`
	Priority    int        `json:"priority"`
	Weight      float64    `json:"weight"`
	RateLimit   int        `json:"rateLimit"`
	UsageCount  int        `json:"usageCount"`
	LastUsedAt  *time.Time `json:"lastUsedAt,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
}

type ProviderAPIKeyInput struct {
	APIKey      string   `json:"apiKey"`
	Alias       string   `json:"alias"`
	Priority    *int     `json:"priority,omitempty"`
	Weight      *float64 `json:"weight,omitempty"`
	RateLimit   *int     `json:"rateLimit,omitempty"`
	ProxyID     *string  `json:"proxyId,omitempty"`
	ProxyPoolID *string  `json:"proxyPoolId,omitempty"`
}

type ProviderHealth struct {
	ID           string     `json:"id"`
	Name         string     `json:"name"`
	BaseURL      string     `json:"baseUrl"`
	IsActive     bool       `json:"isActive"`
	IsHealthy    bool       `json:"isHealthy"`
	UseProxy     bool       `json:"useProxy"`
	ResponseTime float64    `json:"responseTime"`
	LastCheck    *time.Time `json:"lastCheck,omitempty"`
	SuccessRate  float64    `json:"successRate"`
	ErrorMessage *string    `json:"errorMessage,omitempty"`
}

type ProviderInput struct {
	Name           *string  `json:"name,omitempty"`
	BaseURL        *string  `json:"baseUrl,omitempty"`
	IsActive       *bool    `json:"isActive,omitempty"`
	Priority       *int     `json:"priority,omitempty"`
	Weight         *float64 `json:"weight,omitempty"`
	MaxRetries     *int     `json:"maxRetries,omitempty"`
	Timeout        *int     `json:"timeout,omitempty"`
	UseProxy       *bool    `json:"useProxy,omitempty"`
	DefaultProxyID *string  `json:"defaultProxyId,omitempty"`
	RequiresAPIKey *bool    `json:"requiresApiKey,omitempty"`
}

type ProviderStats struct {
	ProviderID   string  `json:"providerId"`
	ProviderName string  `json:"providerName"`
	Requests     int     `json:"requests"`
	Tokens       int     `json:"tokens"`
	SuccessRate  float64 `json:"successRate"`
	AvgLatencyMs float64 `json:"avgLatencyMs"`
	TotalCost    Money   `json:"totalCost"`
}

type ProviderTopologyNode struct {
	Provider *Provider                      `json:"provider"`
	Models   []string                       `json:"models"`
	Accounts []*ProviderAccountTopologyNode `json:"accounts"`
}

type ProviderUsage struct {
	ProviderID   string `json:"providerId"`
	ProviderName string `json:"providerName"`
	Requests     int    `json:"requests"`
	Tokens       int    `json:"tokens"`
	Cost         Money  `json:"cost"`
}

type ProxiesSummary struct {
	Total   int `json:"total"`
	Healthy int `json:"healthy"`
}

type Proxy struct {
	ID              string     `json:"id"`
	PoolID          *string    `json:"poolId,omitempty"`
	PoolName        *string    `json:"poolName,omitempty"`
	URL             string     `json:"url"`
	Type            string     `json:"type"`
	Region          string     `json:"region"`
	IsActive        bool       `json:"isActive"`
	Weight          float64    `json:"weight"`
	SuccessCount    int        `json:"successCount"`
	FailureCount    int        `json:"failureCount"`
	AvgLatency      float64    `json:"avgLatency"`
	LastChecked     *time.Time `json:"lastChecked,omitempty"`
	CreatedAt       time.Time  `json:"createdAt"`
	HasAuth         bool       `json:"hasAuth"`
	UpstreamProxyID *string    `json:"upstreamProxyId,omitempty"`
}

type ProxyHealth struct {
	ID           string     `json:"id"`
	URL          string     `json:"url"`
	Type         string     `json:"type"`
	Region       string     `json:"region"`
	IsActive     bool       `json:"isActive"`
	IsHealthy    bool       `json:"isHealthy"`
	ResponseTime float64    `json:"responseTime"`
	LastCheck    *time.Time `json:"lastCheck,omitempty"`
	SuccessRate  float64    `json:"successRate"`
}

type ProxyInput struct {
	URL             string  `json:"url"`
	Type            string  `json:"type"`
	Region          *string `json:"region,omitempty"`
	Username        *string `json:"username,omitempty"`
	Password        *string `json:"password,omitempty"`
	UpstreamProxyID *string `json:"upstreamProxyId,omitempty"`
	PoolID          *string `json:"poolId,omitempty"`
}

type ProxyPool struct {
	ID               string    `json:"id"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	IsActive         bool      `json:"isActive"`
	Strategy         string    `json:"strategy"`
	ProxyCount       int       `json:"proxyCount"`
	ActiveProxyCount int       `json:"activeProxyCount"`
	CreatedAt        time.Time `json:"createdAt"`
}

type ProxyPoolInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	IsActive    *bool   `json:"isActive,omitempty"`
	Strategy    *string `json:"strategy,omitempty"`
}

type ProxyPoolTopologyNode struct {
	Pool    *ProxyPool `json:"pool"`
	Proxies []*Proxy   `json:"proxies"`
}

type ProxyTestResult struct {
	ID        string  `json:"id"`
	URL       string  `json:"url"`
	IsHealthy bool    `json:"isHealthy"`
	LatencyMs float64 `json:"latencyMs"`
	Error     *string `json:"error,omitempty"`
}

type ProxyTopology struct {
	Providers       []*ProviderTopologyNode  `json:"providers"`
	ProxyPools      []*ProxyPoolTopologyNode `json:"proxyPools"`
	DirectAccounts  int                      `json:"directAccounts"`
	ProxiedAccounts int                      `json:"proxiedAccounts"`
}

type ProxyTopologyRouteStep struct {
	ID     string  `json:"id"`
	Type   string  `json:"type"`
	Label  string  `json:"label"`
	Status string  `json:"status"`
	Detail *string `json:"detail,omitempty"`
}

type Query struct {
}

type QuotaInput struct {
	MonthlyTokenLimit *int   `json:"monthlyTokenLimit,omitempty"`
	MonthlyBudgetUsd  *Money `json:"monthlyBudgetUsd,omitempty"`
}

type RedeemCode struct {
	ID           string     `json:"id"`
	Code         string     `json:"code"`
	Type         string     `json:"type"`
	CreditAmount Money      `json:"creditAmount"`
	PlanID       *string    `json:"planId,omitempty"`
	PlanDays     int        `json:"planDays"`
	UsedBy       *string    `json:"usedBy,omitempty"`
	UsedAt       *time.Time `json:"usedAt,omitempty"`
	ExpiresAt    *time.Time `json:"expiresAt,omitempty"`
	IsActive     bool       `json:"isActive"`
	BatchID      string     `json:"batchId"`
	Note         *string    `json:"note,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
}

type RedeemCodeConnection struct {
	Nodes []*RedeemCode `json:"nodes"`
	Total int           `json:"total"`
}

type RedeemRecord struct {
	ID           string    `json:"id"`
	Code         string    `json:"code"`
	CreditAmount Money     `json:"creditAmount"`
	PlanName     *string   `json:"planName,omitempty"`
	RedeemedAt   time.Time `json:"redeemedAt"`
}

type RedeemResult struct {
	Success      bool    `json:"success"`
	Message      string  `json:"message"`
	CreditAmount *Money  `json:"creditAmount,omitempty"`
	PlanName     *string `json:"planName,omitempty"`
}

type RedisLoad struct {
	ConnectedClients int     `json:"connectedClients"`
	UsedMemoryMb     float64 `json:"usedMemoryMB"`
	MaxMemoryMb      float64 `json:"maxMemoryMB"`
	OpsPerSecond     float64 `json:"opsPerSecond"`
	HitRate          float64 `json:"hitRate"`
	KeyCount         int     `json:"keyCount"`
}

type RegisterInput struct {
	Email        string  `json:"email"`
	Password     string  `json:"password"`
	Name         string  `json:"name"`
	InviteCode   *string `json:"inviteCode,omitempty"`
	CaptchaToken string  `json:"captchaToken"`
}

type RegistrationMode struct {
	Mode               string `json:"mode"`
	InviteCodeRequired bool   `json:"inviteCodeRequired"`
}

type ResetPasswordInput struct {
	Token       string `json:"token"`
	NewPassword string `json:"newPassword"`
}

type RevenueChartPoint struct {
	Date         string `json:"date"`
	Revenue      Money  `json:"revenue"`
	Transactions int    `json:"transactions"`
}

type RoutingRule struct {
	ID                 string    `json:"id"`
	Name               string    `json:"name"`
	Description        string    `json:"description"`
	ModelPattern       string    `json:"modelPattern"`
	TargetProviderID   string    `json:"targetProviderId"`
	FallbackProviderID *string   `json:"fallbackProviderId,omitempty"`
	Priority           int       `json:"priority"`
	IsEnabled          bool      `json:"isEnabled"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
	TargetProvider     *Provider `json:"targetProvider,omitempty"`
	FallbackProvider   *Provider `json:"fallbackProvider,omitempty"`
}

type RoutingRuleList struct {
	Data     []*RoutingRule `json:"data"`
	Total    int            `json:"total"`
	Page     int            `json:"page"`
	PageSize int            `json:"pageSize"`
}

type RuntimeInfo struct {
	Goroutines  int     `json:"goroutines"`
	HeapAllocMb float64 `json:"heapAllocMB"`
	HeapSysMb   float64 `json:"heapSysMB"`
	GcPauseMs   float64 `json:"gcPauseMs"`
	NumGc       int     `json:"numGC"`
	CPUCores    int     `json:"cpuCores"`
}

type SemanticCache struct {
	ID        string    `json:"id"`
	Hash      string    `json:"hash"`
	Provider  string    `json:"provider"`
	Model     string    `json:"model"`
	HitCount  int       `json:"hitCount"`
	CreatedAt time.Time `json:"createdAt"`
}

type ServiceInfo struct {
	Version    string `json:"version"`
	GitCommit  string `json:"gitCommit"`
	BuildTime  string `json:"buildTime"`
	Uptime     string `json:"uptime"`
	ConfigMode string `json:"configMode"`
}

type ServiceLoad struct {
	RequestsInFlight  int     `json:"requestsInFlight"`
	RequestsPerSecond float64 `json:"requestsPerSecond"`
	AvgLatencyMs      float64 `json:"avgLatencyMs"`
	P95LatencyMs      float64 `json:"p95LatencyMs"`
	ErrorRate         float64 `json:"errorRate"`
}

type SiteConfig struct {
	SiteName   string `json:"siteName"`
	Subtitle   string `json:"subtitle"`
	LogoURL    string `json:"logoUrl"`
	FaviconURL string `json:"faviconUrl"`
}

type SsoDiscoveryResult struct {
	RedirectURL string `json:"redirectUrl"`
}

type SystemLoad struct {
	Service  *ServiceLoad  `json:"service"`
	Database *DatabaseLoad `json:"database"`
	Redis    *RedisLoad    `json:"redis"`
}

type SystemSLA struct {
	TotalRequests    int     `json:"totalRequests"`
	FailureRate      float64 `json:"failureRate"`
	AvgLatencyMs     float64 `json:"avgLatencyMs"`
	P95LatencyMs     float64 `json:"p95LatencyMs"`
	P99LatencyMs     float64 `json:"p99LatencyMs"`
	ActiveProviders  int     `json:"activeProviders"`
	HealthyProviders int     `json:"healthyProviders"`
}

type SystemSettings struct {
	RegistrationMode  string  `json:"registrationMode"`
	DefaultTokenLimit *int    `json:"defaultTokenLimit,omitempty"`
	DefaultBudgetUsd  *Money  `json:"defaultBudgetUsd,omitempty"`
	Site              *string `json:"site,omitempty"`
	Security          *string `json:"security,omitempty"`
	Defaults          *string `json:"defaults,omitempty"`
	Email             *string `json:"email,omitempty"`
	Backup            *string `json:"backup,omitempty"`
	Payment           *string `json:"payment,omitempty"`
	Oauth             *string `json:"oauth,omitempty"`
}

type SystemSettingsInput struct {
	Category string `json:"category"`
	Data     string `json:"data"`
}

type SystemStatus struct {
	Service       *ServiceInfo        `json:"service"`
	Runtime       *RuntimeInfo        `json:"runtime"`
	Dependencies  []*DependencyStatus `json:"dependencies"`
	OverallStatus string              `json:"overallStatus"`
}

type Task struct {
	ID          string     `json:"id"`
	ProjectID   string     `json:"projectId"`
	Type        string     `json:"type"`
	Status      string     `json:"status"`
	Input       string     `json:"input"`
	Result      *string    `json:"result,omitempty"`
	Error       *string    `json:"error,omitempty"`
	Progress    int        `json:"progress"`
	WebhookURL  *string    `json:"webhookUrl,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	StartedAt   *time.Time `json:"startedAt,omitempty"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
}

type TaskConnection struct {
	Data  []*Task `json:"data"`
	Total int     `json:"total"`
}

type UpdateDlpConfigInput struct {
	ProjectID       string       `json:"projectId"`
	IsEnabled       *bool        `json:"isEnabled,omitempty"`
	Strategy        *DlpStrategy `json:"strategy,omitempty"`
	MaskEmails      *bool        `json:"maskEmails,omitempty"`
	MaskPhones      *bool        `json:"maskPhones,omitempty"`
	MaskCreditCards *bool        `json:"maskCreditCards,omitempty"`
	MaskSsn         *bool        `json:"maskSsn,omitempty"`
	MaskAPIKeys     *bool        `json:"maskApiKeys,omitempty"`
	CustomRegex     []string     `json:"customRegex,omitempty"`
}

type UpdateIdentityProviderInput struct {
	Name             *string `json:"name,omitempty"`
	IsActive         *bool   `json:"isActive,omitempty"`
	Domains          *string `json:"domains,omitempty"`
	OidcClientID     *string `json:"oidcClientId,omitempty"`
	OidcClientSecret *string `json:"oidcClientSecret,omitempty"`
	OidcIssuerURL    *string `json:"oidcIssuerUrl,omitempty"`
	SamlEntityID     *string `json:"samlEntityId,omitempty"`
	SamlSsoURL       *string `json:"samlSsoUrl,omitempty"`
	SamlIdpCert      *string `json:"samlIdpCert,omitempty"`
	EnableJit        *bool   `json:"enableJit,omitempty"`
	DefaultRole      *string `json:"defaultRole,omitempty"`
	GroupRoleMapping *string `json:"groupRoleMapping,omitempty"`
}

type UpdateIntegrationInput struct {
	Enabled bool   `json:"enabled"`
	Config  string `json:"config"`
}

type UpdateNotificationChannelInput struct {
	Name      *string `json:"name,omitempty"`
	IsEnabled *bool   `json:"isEnabled,omitempty"`
	Config    *string `json:"config,omitempty"`
}

type UpdateProfileInput struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type UpdateProjectInput struct {
	Name           *string `json:"name,omitempty"`
	Description    *string `json:"description,omitempty"`
	QuotaLimit     *Money  `json:"quotaLimit,omitempty"`
	WhiteListedIps *string `json:"whiteListedIps,omitempty"`
}

type UpdateProviderAPIKeyInput struct {
	Priority    *int     `json:"priority,omitempty"`
	Weight      *float64 `json:"weight,omitempty"`
	RateLimit   *int     `json:"rateLimit,omitempty"`
	ProxyID     *string  `json:"proxyId,omitempty"`
	ProxyPoolID *string  `json:"proxyPoolId,omitempty"`
}

type UpdateRoutingRuleInput struct {
	Name               *string `json:"name,omitempty"`
	Description        *string `json:"description,omitempty"`
	ModelPattern       *string `json:"modelPattern,omitempty"`
	TargetProviderID   *string `json:"targetProviderId,omitempty"`
	FallbackProviderID *string `json:"fallbackProviderId,omitempty"`
	Priority           *int    `json:"priority,omitempty"`
	IsEnabled          *bool   `json:"isEnabled,omitempty"`
}

type UpdateWebhookEndpointInput struct {
	URL         *string  `json:"url,omitempty"`
	Events      []string `json:"events,omitempty"`
	IsActive    *bool    `json:"isActive,omitempty"`
	Description *string  `json:"description,omitempty"`
}

type UsageChartPoint struct {
	Date     string `json:"date"`
	Requests int    `json:"requests"`
	Tokens   int    `json:"tokens"`
	Cost     Money  `json:"cost"`
}

type UsageConnection struct {
	Data  []*UsageRecord `json:"data"`
	Total int            `json:"total"`
}

type UsageRecord struct {
	ID           string    `json:"id"`
	ModelName    string    `json:"modelName"`
	InputTokens  int       `json:"inputTokens"`
	OutputTokens int       `json:"outputTokens"`
	Cost         Money     `json:"cost"`
	LatencyMs    int       `json:"latencyMs"`
	IsSuccess    bool      `json:"isSuccess"`
	CreatedAt    time.Time `json:"createdAt"`
}

type UsageSummary struct {
	TotalRequests int     `json:"totalRequests"`
	SuccessRate   float64 `json:"successRate"`
	TotalTokens   int     `json:"totalTokens"`
	TotalCost     Money   `json:"totalCost"`
}

type User struct {
	ID                    string     `json:"id"`
	Email                 string     `json:"email"`
	Name                  string     `json:"name"`
	Role                  string     `json:"role"`
	IsActive              bool       `json:"isActive"`
	RequirePasswordChange bool       `json:"requirePasswordChange"`
	MonthlyTokenLimit     *int       `json:"monthlyTokenLimit,omitempty"`
	MonthlyBudgetUsd      *Money     `json:"monthlyBudgetUsd,omitempty"`
	Balance               *Money     `json:"balance,omitempty"`
	CreatedAt             time.Time  `json:"createdAt"`
	LastLoginAt           *time.Time `json:"lastLoginAt,omitempty"`
	MfaEnabled            bool       `json:"mfaEnabled"`
	EmailVerified         bool       `json:"emailVerified"`
}

type UserConnection struct {
	Data  []*UserListItem `json:"data"`
	Total int             `json:"total"`
}

type UserDetail struct {
	ID                string            `json:"id"`
	Email             string            `json:"email"`
	Name              string            `json:"name"`
	Role              string            `json:"role"`
	IsActive          bool              `json:"isActive"`
	CreatedAt         time.Time         `json:"createdAt"`
	APIKeys           int               `json:"apiKeys"`
	MonthlyTokenLimit *int              `json:"monthlyTokenLimit,omitempty"`
	MonthlyBudgetUsd  *Money            `json:"monthlyBudgetUsd,omitempty"`
	MfaEnabled        bool              `json:"mfaEnabled"`
	UsageMonth        *UserMonthlyUsage `json:"usageMonth,omitempty"`
}

type UserGrowthPoint struct {
	Date       string `json:"date"`
	NewUsers   int    `json:"newUsers"`
	TotalUsers int    `json:"totalUsers"`
}

type UserListItem struct {
	ID          string     `json:"id"`
	Email       string     `json:"email"`
	Name        string     `json:"name"`
	Role        string     `json:"role"`
	IsActive    bool       `json:"isActive"`
	LastLoginAt *time.Time `json:"lastLoginAt,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	APIKeyCount int        `json:"apiKeyCount"`
}

type UserMonthlyUsage struct {
	TotalRequests int     `json:"totalRequests"`
	TotalTokens   int     `json:"totalTokens"`
	TotalCost     Money   `json:"totalCost"`
	AvgLatency    float64 `json:"avgLatency"`
	SuccessRate   float64 `json:"successRate"`
	ErrorCount    int     `json:"errorCount"`
}

type UserSubscription struct {
	ID                 string    `json:"id"`
	OrgID              string    `json:"orgId"`
	PlanID             string    `json:"planId"`
	PlanName           string    `json:"planName"`
	Status             string    `json:"status"`
	CurrentPeriodStart time.Time `json:"currentPeriodStart"`
	CurrentPeriodEnd   time.Time `json:"currentPeriodEnd"`
	CancelAtPeriodEnd  bool      `json:"cancelAtPeriodEnd"`
	Plan               *Plan     `json:"plan"`
	UsedTokens         int       `json:"usedTokens"`
	TokenLimit         int       `json:"tokenLimit"`
	QuotaPercentage    float64   `json:"quotaPercentage"`
	IsQuotaExceeded    bool      `json:"isQuotaExceeded"`
}

type WebhookDelivery struct {
	ID           string    `json:"id"`
	EndpointID   string    `json:"endpointId"`
	EventType    string    `json:"eventType"`
	Payload      string    `json:"payload"`
	Status       string    `json:"status"`
	StatusCode   int       `json:"statusCode"`
	ResponseBody *string   `json:"responseBody,omitempty"`
	ErrorMessage *string   `json:"errorMessage,omitempty"`
	RetryCount   int       `json:"retryCount"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type WebhookEndpoint struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"projectId"`
	URL         string    `json:"url"`
	Secret      *string   `json:"secret,omitempty"`
	Events      []string  `json:"events"`
	IsActive    bool      `json:"isActive"`
	Description *string   `json:"description,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type DlpStrategy string

const (
	DlpStrategyRedact DlpStrategy = "REDACT"
	DlpStrategyBlock  DlpStrategy = "BLOCK"
)

var AllDlpStrategy = []DlpStrategy{
	DlpStrategyRedact,
	DlpStrategyBlock,
}

func (e DlpStrategy) IsValid() bool {
	switch e {
	case DlpStrategyRedact, DlpStrategyBlock:
		return true
	}
	return false
}

func (e DlpStrategy) String() string {
	return string(e)
}

func (e *DlpStrategy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DlpStrategy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DlpStrategy", str)
	}
	return nil
}

func (e DlpStrategy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DlpStrategy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DlpStrategy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// ModelKind classifies a catalog row by its capability. Exactly one kind per
// row. Multi-capability models (e.g. chat + embedding) are classified by the
// most specific kind: embedding wins over chat, audio wins over both.
type ModelKind string

const (
	ModelKindChat      ModelKind = "CHAT"
	ModelKindEmbedding ModelKind = "EMBEDDING"
	ModelKindImage     ModelKind = "IMAGE"
	ModelKindStt       ModelKind = "STT"
	ModelKindTts       ModelKind = "TTS"
	ModelKindRerank    ModelKind = "RERANK"
	ModelKindUnknown   ModelKind = "UNKNOWN"
)

var AllModelKind = []ModelKind{
	ModelKindChat,
	ModelKindEmbedding,
	ModelKindImage,
	ModelKindStt,
	ModelKindTts,
	ModelKindRerank,
	ModelKindUnknown,
}

func (e ModelKind) IsValid() bool {
	switch e {
	case ModelKindChat, ModelKindEmbedding, ModelKindImage, ModelKindStt, ModelKindTts, ModelKindRerank, ModelKindUnknown:
		return true
	}
	return false
}

func (e ModelKind) String() string {
	return string(e)
}

func (e *ModelKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ModelKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ModelKind", str)
	}
	return nil
}

func (e ModelKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ModelKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ModelKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleUser  Role = "USER"
	RoleAdmin Role = "ADMIN"
)

var AllRole = []Role{
	RoleUser,
	RoleAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleUser, RoleAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
