// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Alert struct {
	ID             string     `json:"id"`
	TargetType     string     `json:"targetType"`
	TargetID       string     `json:"targetId"`
	AlertType      string     `json:"alertType"`
	Message        string     `json:"message"`
	Status         string     `json:"status"`
	ResolvedAt     *time.Time `json:"resolvedAt,omitempty"`
	AcknowledgedAt *time.Time `json:"acknowledgedAt,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
}

type AlertConfig struct {
	ID               *string `json:"id,omitempty"`
	TargetType       string  `json:"targetType"`
	TargetID         string  `json:"targetId"`
	IsEnabled        bool    `json:"isEnabled"`
	FailureThreshold int     `json:"failureThreshold"`
	WebhookURL       *string `json:"webhookUrl,omitempty"`
	Email            *string `json:"email,omitempty"`
}

type AlertConfigInput struct {
	TargetType       string  `json:"targetType"`
	TargetID         string  `json:"targetId"`
	IsEnabled        bool    `json:"isEnabled"`
	FailureThreshold int     `json:"failureThreshold"`
	WebhookURL       *string `json:"webhookUrl,omitempty"`
	Email            *string `json:"email,omitempty"`
}

type AlertConnection struct {
	Data  []*Alert `json:"data"`
	Total int      `json:"total"`
}

type Announcement struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	Content   string     `json:"content"`
	Type      string     `json:"type"`
	Priority  int        `json:"priority"`
	IsActive  bool       `json:"isActive"`
	StartsAt  *time.Time `json:"startsAt,omitempty"`
	EndsAt    *time.Time `json:"endsAt,omitempty"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

type AnnouncementInput struct {
	Title    string     `json:"title"`
	Content  string     `json:"content"`
	Type     *string    `json:"type,omitempty"`
	Priority *int       `json:"priority,omitempty"`
	IsActive *bool      `json:"isActive,omitempty"`
	StartsAt *time.Time `json:"startsAt,omitempty"`
	EndsAt   *time.Time `json:"endsAt,omitempty"`
}

type AnomalyResult struct {
	HasAnomaly bool    `json:"hasAnomaly"`
	Message    *string `json:"message,omitempty"`
	Details    *string `json:"details,omitempty"`
}

type APIKey struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	KeyPrefix  string     `json:"keyPrefix"`
	IsActive   bool       `json:"isActive"`
	RateLimit  int        `json:"rateLimit"`
	DailyLimit int        `json:"dailyLimit"`
	ExpiresAt  *time.Time `json:"expiresAt,omitempty"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
}

type APIKeyHealth struct {
	ID           string     `json:"id"`
	ProviderID   string     `json:"providerId"`
	ProviderName string     `json:"providerName"`
	KeyPrefix    string     `json:"keyPrefix"`
	IsActive     bool       `json:"isActive"`
	IsHealthy    bool       `json:"isHealthy"`
	LastCheck    *time.Time `json:"lastCheck,omitempty"`
	ResponseTime float64    `json:"responseTime"`
	SuccessRate  float64    `json:"successRate"`
}

type APIKeyWithSecret struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Key        string     `json:"key"`
	KeyPrefix  string     `json:"keyPrefix"`
	IsActive   bool       `json:"isActive"`
	RateLimit  int        `json:"rateLimit"`
	DailyLimit int        `json:"dailyLimit"`
	ExpiresAt  *time.Time `json:"expiresAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
}

type APIKeysSummary struct {
	Total   int `json:"total"`
	Healthy int `json:"healthy"`
}

type AuthPayload struct {
	Token        string  `json:"token"`
	RefreshToken *string `json:"refreshToken,omitempty"`
	User         *User   `json:"user"`
}

type BatchProxyInput struct {
	Proxies []*BatchProxyItem `json:"proxies"`
}

type BatchProxyItem struct {
	URL    string  `json:"url"`
	Type   *string `json:"type,omitempty"`
	Region *string `json:"region,omitempty"`
}

type BatchProxyResult struct {
	Success int      `json:"success"`
	Failed  int      `json:"failed"`
	Proxies []*Proxy `json:"proxies"`
	Errors  []string `json:"errors,omitempty"`
}

type Budget struct {
	ID               string  `json:"id"`
	UserID           string  `json:"userId"`
	MonthlyLimitUsd  float64 `json:"monthlyLimitUsd"`
	AlertThreshold   float64 `json:"alertThreshold"`
	EnforceHardLimit bool    `json:"enforceHardLimit"`
	IsActive         bool    `json:"isActive"`
	WebhookURL       *string `json:"webhookUrl,omitempty"`
	Email            *string `json:"email,omitempty"`
}

type BudgetInput struct {
	MonthlyLimitUsd  float64  `json:"monthlyLimitUsd"`
	AlertThreshold   *float64 `json:"alertThreshold,omitempty"`
	EnforceHardLimit *bool    `json:"enforceHardLimit,omitempty"`
	WebhookURL       *string  `json:"webhookUrl,omitempty"`
	Email            *string  `json:"email,omitempty"`
}

type BudgetStatus struct {
	Budget          *Budget `json:"budget,omitempty"`
	CurrentSpend    float64 `json:"currentSpend"`
	RemainingBudget float64 `json:"remainingBudget"`
	PercentUsed     float64 `json:"percentUsed"`
	IsOverBudget    bool    `json:"isOverBudget"`
}

type ChangePasswordInput struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type CheckoutSession struct {
	URL string `json:"url"`
}

type Coupon struct {
	ID             string     `json:"id"`
	Code           string     `json:"code"`
	Name           string     `json:"name"`
	Type           string     `json:"type"`
	DiscountValue  float64    `json:"discountValue"`
	MinAmount      float64    `json:"minAmount"`
	MaxUses        int        `json:"maxUses"`
	UseCount       int        `json:"useCount"`
	MaxUsesPerUser int        `json:"maxUsesPerUser"`
	IsActive       bool       `json:"isActive"`
	ExpiresAt      *time.Time `json:"expiresAt,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
}

type CouponInput struct {
	Code           string     `json:"code"`
	Name           string     `json:"name"`
	Type           string     `json:"type"`
	DiscountValue  float64    `json:"discountValue"`
	MinAmount      *float64   `json:"minAmount,omitempty"`
	MaxUses        *int       `json:"maxUses,omitempty"`
	MaxUsesPerUser *int       `json:"maxUsesPerUser,omitempty"`
	IsActive       *bool      `json:"isActive,omitempty"`
	ExpiresAt      *time.Time `json:"expiresAt,omitempty"`
}

type CreateTaskInput struct {
	Type       string  `json:"type"`
	Input      string  `json:"input"`
	WebhookURL *string `json:"webhookUrl,omitempty"`
}

type DailyStats struct {
	Date        string  `json:"date"`
	Requests    int     `json:"requests"`
	TotalTokens int     `json:"totalTokens"`
	TotalCost   float64 `json:"totalCost"`
}

type Dashboard struct {
	TotalRequests    int             `json:"totalRequests"`
	SuccessRate      float64         `json:"successRate"`
	TotalTokens      int             `json:"totalTokens"`
	TotalCost        float64         `json:"totalCost"`
	AverageLatencyMs float64         `json:"averageLatencyMs"`
	ActiveUsers      int             `json:"activeUsers"`
	ActiveProviders  int             `json:"activeProviders"`
	ActiveProxies    int             `json:"activeProxies"`
	RequestsToday    int             `json:"requestsToday"`
	CostToday        float64         `json:"costToday"`
	TokensToday      int             `json:"tokensToday"`
	ErrorCount       int             `json:"errorCount"`
	McpCallCount     int             `json:"mcpCallCount"`
	McpErrorCount    int             `json:"mcpErrorCount"`
	APIKeys          *APIKeysSummary `json:"apiKeys"`
	Proxies          *ProxiesSummary `json:"proxies"`
}

type Document struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Slug        string    `json:"slug"`
	Content     string    `json:"content"`
	Category    string    `json:"category"`
	SortOrder   int       `json:"sortOrder"`
	IsPublished bool      `json:"isPublished"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type DocumentInput struct {
	Title       string  `json:"title"`
	Slug        string  `json:"slug"`
	Content     string  `json:"content"`
	Category    *string `json:"category,omitempty"`
	SortOrder   *int    `json:"sortOrder,omitempty"`
	IsPublished *bool   `json:"isPublished,omitempty"`
}

type GenerateRedeemCodesInput struct {
	Type         string     `json:"type"`
	CreditAmount *float64   `json:"creditAmount,omitempty"`
	PlanID       *string    `json:"planId,omitempty"`
	PlanDays     *int       `json:"planDays,omitempty"`
	Count        int        `json:"count"`
	ExpiresAt    *time.Time `json:"expiresAt,omitempty"`
	Note         *string    `json:"note,omitempty"`
}

type GenerateRedeemCodesResult struct {
	Codes []string `json:"codes"`
	Count int      `json:"count"`
}

type HealthEvent struct {
	ID         string    `json:"id"`
	TargetType string    `json:"targetType"`
	TargetID   string    `json:"targetId"`
	Status     string    `json:"status"`
	Message    *string   `json:"message,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
}

type InviteCode struct {
	ID        string     `json:"id"`
	Code      string     `json:"code"`
	CreatedBy string     `json:"createdBy"`
	MaxUses   int        `json:"maxUses"`
	UseCount  int        `json:"useCount"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	IsActive  bool       `json:"isActive"`
	CreatedAt time.Time  `json:"createdAt"`
}

type InviteCodeInput struct {
	MaxUses   *int       `json:"maxUses,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type McpEnvInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type McpResource struct {
	ID          string  `json:"id"`
	ServerID    string  `json:"serverId"`
	Name        string  `json:"name"`
	URI         string  `json:"uri"`
	Description *string `json:"description,omitempty"`
	MimeType    *string `json:"mimeType,omitempty"`
}

type McpServer struct {
	ID            string     `json:"id"`
	Name          string     `json:"name"`
	Type          string     `json:"type"`
	Command       *string    `json:"command,omitempty"`
	Args          []string   `json:"args,omitempty"`
	URL           *string    `json:"url,omitempty"`
	IsActive      bool       `json:"isActive"`
	Status        string     `json:"status"`
	LastError     *string    `json:"lastError,omitempty"`
	LastCheckedAt *time.Time `json:"lastCheckedAt,omitempty"`
	Tools         []*McpTool `json:"tools,omitempty"`
	CreatedAt     time.Time  `json:"createdAt"`
}

type McpServerInput struct {
	Name     string         `json:"name"`
	Type     string         `json:"type"`
	Command  *string        `json:"command,omitempty"`
	Args     []string       `json:"args,omitempty"`
	URL      *string        `json:"url,omitempty"`
	IsActive *bool          `json:"isActive,omitempty"`
	Env      []*McpEnvInput `json:"env,omitempty"`
}

type McpTool struct {
	ID          string  `json:"id"`
	ServerID    string  `json:"serverId"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	InputSchema *string `json:"inputSchema,omitempty"`
	IsActive    bool    `json:"isActive"`
}

type Model struct {
	ID               string    `json:"id"`
	ProviderID       string    `json:"providerId"`
	Name             string    `json:"name"`
	DisplayName      string    `json:"displayName"`
	InputPricePer1k  float64   `json:"inputPricePer1k"`
	OutputPricePer1k float64   `json:"outputPricePer1k"`
	PricePerSecond   *float64  `json:"pricePerSecond,omitempty"`
	PricePerImage    *float64  `json:"pricePerImage,omitempty"`
	PricePerMinute   *float64  `json:"pricePerMinute,omitempty"`
	MaxTokens        int       `json:"maxTokens"`
	IsActive         bool      `json:"isActive"`
	CreatedAt        time.Time `json:"createdAt"`
}

type ModelInput struct {
	Name             string   `json:"name"`
	DisplayName      *string  `json:"displayName,omitempty"`
	InputPricePer1k  *float64 `json:"inputPricePer1k,omitempty"`
	OutputPricePer1k *float64 `json:"outputPricePer1k,omitempty"`
	PricePerSecond   *float64 `json:"pricePerSecond,omitempty"`
	PricePerImage    *float64 `json:"pricePerImage,omitempty"`
	PricePerMinute   *float64 `json:"pricePerMinute,omitempty"`
	MaxTokens        *int     `json:"maxTokens,omitempty"`
	IsActive         *bool    `json:"isActive,omitempty"`
}

type ModelStats struct {
	ModelID      string  `json:"modelId"`
	ModelName    string  `json:"modelName"`
	Requests     int     `json:"requests"`
	InputTokens  int     `json:"inputTokens"`
	OutputTokens int     `json:"outputTokens"`
	TotalCost    float64 `json:"totalCost"`
}

type Mutation struct {
}

type Order struct {
	ID            string    `json:"id"`
	OrderNo       string    `json:"orderNo"`
	Amount        float64   `json:"amount"`
	Currency      string    `json:"currency"`
	Status        string    `json:"status"`
	PaymentMethod string    `json:"paymentMethod"`
	CreatedAt     time.Time `json:"createdAt"`
	Plan          *Plan     `json:"plan,omitempty"`
}

type Plan struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Description  string  `json:"description"`
	PriceMonth   float64 `json:"priceMonth"`
	TokenLimit   int     `json:"tokenLimit"`
	RateLimit    int     `json:"rateLimit"`
	SupportLevel string  `json:"supportLevel"`
	IsActive     bool    `json:"isActive"`
	Features     *string `json:"features,omitempty"`
}

type PlanInput struct {
	Name         string  `json:"name"`
	Description  *string `json:"description,omitempty"`
	PriceMonth   float64 `json:"priceMonth"`
	TokenLimit   int     `json:"tokenLimit"`
	RateLimit    int     `json:"rateLimit"`
	SupportLevel *string `json:"supportLevel,omitempty"`
	IsActive     *bool   `json:"isActive,omitempty"`
	Features     *string `json:"features,omitempty"`
}

type Provider struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	BaseURL        string    `json:"baseUrl"`
	IsActive       bool      `json:"isActive"`
	Priority       int       `json:"priority"`
	Weight         float64   `json:"weight"`
	MaxRetries     int       `json:"maxRetries"`
	Timeout        int       `json:"timeout"`
	UseProxy       bool      `json:"useProxy"`
	DefaultProxyID *string   `json:"defaultProxyId,omitempty"`
	RequiresAPIKey bool      `json:"requiresApiKey"`
	CreatedAt      time.Time `json:"createdAt"`
}

type ProviderAPIKey struct {
	ID         string     `json:"id"`
	ProviderID string     `json:"providerId"`
	Alias      string     `json:"alias"`
	KeyPrefix  string     `json:"keyPrefix"`
	IsActive   bool       `json:"isActive"`
	Priority   int        `json:"priority"`
	Weight     float64    `json:"weight"`
	RateLimit  int        `json:"rateLimit"`
	UsageCount int        `json:"usageCount"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
}

type ProviderAPIKeyInput struct {
	APIKey    string   `json:"apiKey"`
	Alias     string   `json:"alias"`
	Priority  *int     `json:"priority,omitempty"`
	Weight    *float64 `json:"weight,omitempty"`
	RateLimit *int     `json:"rateLimit,omitempty"`
}

type ProviderHealth struct {
	ID           string     `json:"id"`
	Name         string     `json:"name"`
	BaseURL      string     `json:"baseUrl"`
	IsActive     bool       `json:"isActive"`
	IsHealthy    bool       `json:"isHealthy"`
	UseProxy     bool       `json:"useProxy"`
	ResponseTime float64    `json:"responseTime"`
	LastCheck    *time.Time `json:"lastCheck,omitempty"`
	SuccessRate  float64    `json:"successRate"`
	ErrorMessage *string    `json:"errorMessage,omitempty"`
}

type ProviderInput struct {
	Name           *string  `json:"name,omitempty"`
	BaseURL        *string  `json:"baseUrl,omitempty"`
	IsActive       *bool    `json:"isActive,omitempty"`
	Priority       *int     `json:"priority,omitempty"`
	Weight         *float64 `json:"weight,omitempty"`
	MaxRetries     *int     `json:"maxRetries,omitempty"`
	Timeout        *int     `json:"timeout,omitempty"`
	UseProxy       *bool    `json:"useProxy,omitempty"`
	DefaultProxyID *string  `json:"defaultProxyId,omitempty"`
}

type ProviderStats struct {
	ProviderID   string  `json:"providerId"`
	ProviderName string  `json:"providerName"`
	Requests     int     `json:"requests"`
	Tokens       int     `json:"tokens"`
	SuccessRate  float64 `json:"successRate"`
	AvgLatencyMs float64 `json:"avgLatencyMs"`
	TotalCost    float64 `json:"totalCost"`
}

type ProviderUsage struct {
	ProviderID   string  `json:"providerId"`
	ProviderName string  `json:"providerName"`
	Requests     int     `json:"requests"`
	Tokens       int     `json:"tokens"`
	Cost         float64 `json:"cost"`
}

type ProxiesSummary struct {
	Total   int `json:"total"`
	Healthy int `json:"healthy"`
}

type Proxy struct {
	ID              string     `json:"id"`
	URL             string     `json:"url"`
	Type            string     `json:"type"`
	Region          string     `json:"region"`
	IsActive        bool       `json:"isActive"`
	Weight          float64    `json:"weight"`
	SuccessCount    int        `json:"successCount"`
	FailureCount    int        `json:"failureCount"`
	AvgLatency      float64    `json:"avgLatency"`
	LastChecked     *time.Time `json:"lastChecked,omitempty"`
	CreatedAt       time.Time  `json:"createdAt"`
	HasAuth         bool       `json:"hasAuth"`
	UpstreamProxyID *string    `json:"upstreamProxyId,omitempty"`
}

type ProxyHealth struct {
	ID           string     `json:"id"`
	URL          string     `json:"url"`
	Type         string     `json:"type"`
	Region       string     `json:"region"`
	IsActive     bool       `json:"isActive"`
	IsHealthy    bool       `json:"isHealthy"`
	ResponseTime float64    `json:"responseTime"`
	LastCheck    *time.Time `json:"lastCheck,omitempty"`
	SuccessRate  float64    `json:"successRate"`
}

type ProxyInput struct {
	URL             string  `json:"url"`
	Type            string  `json:"type"`
	Region          *string `json:"region,omitempty"`
	Username        *string `json:"username,omitempty"`
	Password        *string `json:"password,omitempty"`
	UpstreamProxyID *string `json:"upstreamProxyId,omitempty"`
}

type ProxyTestResult struct {
	ID        string  `json:"id"`
	URL       string  `json:"url"`
	IsHealthy bool    `json:"isHealthy"`
	LatencyMs float64 `json:"latencyMs"`
	Error     *string `json:"error,omitempty"`
}

type Query struct {
}

type QuotaInput struct {
	MonthlyTokenLimit *int     `json:"monthlyTokenLimit,omitempty"`
	MonthlyBudgetUsd  *float64 `json:"monthlyBudgetUsd,omitempty"`
}

type RedeemCode struct {
	ID           string     `json:"id"`
	Code         string     `json:"code"`
	Type         string     `json:"type"`
	CreditAmount float64    `json:"creditAmount"`
	PlanID       *string    `json:"planId,omitempty"`
	PlanDays     int        `json:"planDays"`
	UsedBy       *string    `json:"usedBy,omitempty"`
	UsedAt       *time.Time `json:"usedAt,omitempty"`
	ExpiresAt    *time.Time `json:"expiresAt,omitempty"`
	IsActive     bool       `json:"isActive"`
	BatchID      string     `json:"batchId"`
	Note         *string    `json:"note,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
}

type RedeemCodeConnection struct {
	Nodes []*RedeemCode `json:"nodes"`
	Total int           `json:"total"`
}

type RedeemRecord struct {
	ID           string    `json:"id"`
	Code         string    `json:"code"`
	CreditAmount float64   `json:"creditAmount"`
	PlanName     *string   `json:"planName,omitempty"`
	RedeemedAt   time.Time `json:"redeemedAt"`
}

type RedeemResult struct {
	Success      bool     `json:"success"`
	Message      string   `json:"message"`
	CreditAmount *float64 `json:"creditAmount,omitempty"`
	PlanName     *string  `json:"planName,omitempty"`
}

type RegisterInput struct {
	Email      string  `json:"email"`
	Password   string  `json:"password"`
	Name       string  `json:"name"`
	InviteCode *string `json:"inviteCode,omitempty"`
}

type ResetPasswordInput struct {
	Token       string `json:"token"`
	NewPassword string `json:"newPassword"`
}

type SystemSettings struct {
	RegistrationMode  string   `json:"registrationMode"`
	DefaultTokenLimit *int     `json:"defaultTokenLimit,omitempty"`
	DefaultBudgetUsd  *float64 `json:"defaultBudgetUsd,omitempty"`
	Site              *string  `json:"site,omitempty"`
	Security          *string  `json:"security,omitempty"`
	Defaults          *string  `json:"defaults,omitempty"`
	Email             *string  `json:"email,omitempty"`
	Backup            *string  `json:"backup,omitempty"`
	Payment           *string  `json:"payment,omitempty"`
}

type SystemSettingsInput struct {
	Category string `json:"category"`
	Data     string `json:"data"`
}

type Task struct {
	ID          string     `json:"id"`
	UserID      string     `json:"userId"`
	Type        string     `json:"type"`
	Status      string     `json:"status"`
	Input       string     `json:"input"`
	Result      *string    `json:"result,omitempty"`
	Error       *string    `json:"error,omitempty"`
	Progress    int        `json:"progress"`
	WebhookURL  *string    `json:"webhookUrl,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	StartedAt   *time.Time `json:"startedAt,omitempty"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
}

type TaskConnection struct {
	Data  []*Task `json:"data"`
	Total int     `json:"total"`
}

type UpdateProfileInput struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type UpdateProviderAPIKeyInput struct {
	Priority  *int     `json:"priority,omitempty"`
	Weight    *float64 `json:"weight,omitempty"`
	RateLimit *int     `json:"rateLimit,omitempty"`
}

type UsageChartPoint struct {
	Date     string  `json:"date"`
	Requests int     `json:"requests"`
	Tokens   int     `json:"tokens"`
	Cost     float64 `json:"cost"`
}

type UsageConnection struct {
	Data  []*UsageRecord `json:"data"`
	Total int            `json:"total"`
}

type UsageRecord struct {
	ID           string    `json:"id"`
	ModelName    string    `json:"modelName"`
	InputTokens  int       `json:"inputTokens"`
	OutputTokens int       `json:"outputTokens"`
	Cost         float64   `json:"cost"`
	LatencyMs    int       `json:"latencyMs"`
	IsSuccess    bool      `json:"isSuccess"`
	CreatedAt    time.Time `json:"createdAt"`
}

type UsageSummary struct {
	TotalRequests int     `json:"totalRequests"`
	SuccessRate   float64 `json:"successRate"`
	TotalTokens   int     `json:"totalTokens"`
	TotalCost     float64 `json:"totalCost"`
}

type User struct {
	ID                    string     `json:"id"`
	Email                 string     `json:"email"`
	Name                  string     `json:"name"`
	Role                  string     `json:"role"`
	IsActive              bool       `json:"isActive"`
	RequirePasswordChange bool       `json:"requirePasswordChange"`
	MonthlyTokenLimit     *int       `json:"monthlyTokenLimit,omitempty"`
	MonthlyBudgetUsd      *float64   `json:"monthlyBudgetUsd,omitempty"`
	Balance               *float64   `json:"balance,omitempty"`
	CreatedAt             time.Time  `json:"createdAt"`
	LastLoginAt           *time.Time `json:"lastLoginAt,omitempty"`
}

type UserConnection struct {
	Data  []*UserListItem `json:"data"`
	Total int             `json:"total"`
}

type UserDetail struct {
	ID                string            `json:"id"`
	Email             string            `json:"email"`
	Name              string            `json:"name"`
	Role              string            `json:"role"`
	IsActive          bool              `json:"isActive"`
	CreatedAt         time.Time         `json:"createdAt"`
	APIKeys           int               `json:"apiKeys"`
	MonthlyTokenLimit *int              `json:"monthlyTokenLimit,omitempty"`
	MonthlyBudgetUsd  *float64          `json:"monthlyBudgetUsd,omitempty"`
	UsageMonth        *UserMonthlyUsage `json:"usageMonth,omitempty"`
}

type UserListItem struct {
	ID          string     `json:"id"`
	Email       string     `json:"email"`
	Name        string     `json:"name"`
	Role        string     `json:"role"`
	IsActive    bool       `json:"isActive"`
	LastLoginAt *time.Time `json:"lastLoginAt,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	APIKeyCount int        `json:"apiKeyCount"`
}

type UserMonthlyUsage struct {
	TotalRequests int     `json:"totalRequests"`
	TotalTokens   int     `json:"totalTokens"`
	TotalCost     float64 `json:"totalCost"`
	AvgLatency    float64 `json:"avgLatency"`
	SuccessRate   float64 `json:"successRate"`
	ErrorCount    int     `json:"errorCount"`
}

type UserSubscription struct {
	ID                 string    `json:"id"`
	UserID             string    `json:"userId"`
	PlanID             string    `json:"planId"`
	Status             string    `json:"status"`
	CurrentPeriodStart time.Time `json:"currentPeriodStart"`
	CurrentPeriodEnd   time.Time `json:"currentPeriodEnd"`
	CancelAtPeriodEnd  bool      `json:"cancelAtPeriodEnd"`
	Plan               *Plan     `json:"plan"`
}

type Role string

const (
	RoleUser  Role = "USER"
	RoleAdmin Role = "ADMIN"
)

var AllRole = []Role{
	RoleUser,
	RoleAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleUser, RoleAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
