// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Alert struct {
	ID             string     `json:"id"`
	TargetType     string     `json:"targetType"`
	TargetID       string     `json:"targetId"`
	AlertType      string     `json:"alertType"`
	Message        string     `json:"message"`
	Status         string     `json:"status"`
	ResolvedAt     *time.Time `json:"resolvedAt,omitempty"`
	AcknowledgedAt *time.Time `json:"acknowledgedAt,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
}

type AlertConfig struct {
	ID                 *string `json:"id,omitempty"`
	TargetType         string  `json:"targetType"`
	TargetID           string  `json:"targetId"`
	IsEnabled          bool    `json:"isEnabled"`
	FailureThreshold   int     `json:"failureThreshold"`
	ErrorRateThreshold float64 `json:"errorRateThreshold"`
	LatencyThresholdMs int     `json:"latencyThresholdMs"`
	BudgetThreshold    float64 `json:"budgetThreshold"`
	CooldownMinutes    int     `json:"cooldownMinutes"`
	WebhookURL         *string `json:"webhookUrl,omitempty"`
	Email              *string `json:"email,omitempty"`
}

type AlertConfigInput struct {
	TargetType         string   `json:"targetType"`
	TargetID           string   `json:"targetId"`
	IsEnabled          bool     `json:"isEnabled"`
	FailureThreshold   int      `json:"failureThreshold"`
	ErrorRateThreshold *float64 `json:"errorRateThreshold,omitempty"`
	LatencyThresholdMs *int     `json:"latencyThresholdMs,omitempty"`
	BudgetThreshold    *float64 `json:"budgetThreshold,omitempty"`
	CooldownMinutes    *int     `json:"cooldownMinutes,omitempty"`
	WebhookURL         *string  `json:"webhookUrl,omitempty"`
	Email              *string  `json:"email,omitempty"`
}

type AlertConnection struct {
	Data  []*Alert `json:"data"`
	Total int      `json:"total"`
}

type Announcement struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	Content   string     `json:"content"`
	Type      string     `json:"type"`
	Priority  int        `json:"priority"`
	IsActive  bool       `json:"isActive"`
	StartsAt  *time.Time `json:"startsAt,omitempty"`
	EndsAt    *time.Time `json:"endsAt,omitempty"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

type AnnouncementInput struct {
	Title    string     `json:"title"`
	Content  string     `json:"content"`
	Type     *string    `json:"type,omitempty"`
	Priority *int       `json:"priority,omitempty"`
	IsActive *bool      `json:"isActive,omitempty"`
	StartsAt *time.Time `json:"startsAt,omitempty"`
	EndsAt   *time.Time `json:"endsAt,omitempty"`
}

type AnomalyResult struct {
	HasAnomaly bool    `json:"hasAnomaly"`
	Message    *string `json:"message,omitempty"`
	Details    *string `json:"details,omitempty"`
}

type APIKey struct {
	ID         string     `json:"id"`
	ProjectID  string     `json:"projectId"`
	Channel    string     `json:"channel"`
	Name       string     `json:"name"`
	KeyPrefix  string     `json:"keyPrefix"`
	IsActive   bool       `json:"isActive"`
	Scopes     string     `json:"scopes"`
	RateLimit  int        `json:"rateLimit"`
	TokenLimit int        `json:"tokenLimit"`
	DailyLimit int        `json:"dailyLimit"`
	ExpiresAt  *time.Time `json:"expiresAt,omitempty"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
}

type APIKeyHealth struct {
	ID           string     `json:"id"`
	ProviderID   string     `json:"providerId"`
	ProviderName string     `json:"providerName"`
	KeyPrefix    string     `json:"keyPrefix"`
	IsActive     bool       `json:"isActive"`
	IsHealthy    bool       `json:"isHealthy"`
	LastCheck    *time.Time `json:"lastCheck,omitempty"`
	ResponseTime float64    `json:"responseTime"`
	SuccessRate  float64    `json:"successRate"`
}

type APIKeyWithSecret struct {
	ID         string     `json:"id"`
	ProjectID  string     `json:"projectId"`
	Channel    string     `json:"channel"`
	Name       string     `json:"name"`
	Key        string     `json:"key"`
	KeyPrefix  string     `json:"keyPrefix"`
	IsActive   bool       `json:"isActive"`
	Scopes     string     `json:"scopes"`
	RateLimit  int        `json:"rateLimit"`
	TokenLimit int        `json:"tokenLimit"`
	DailyLimit int        `json:"dailyLimit"`
	ExpiresAt  *time.Time `json:"expiresAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
}

type APIKeysSummary struct {
	Total   int `json:"total"`
	Healthy int `json:"healthy"`
}

type AuditLog struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	Action    string    `json:"action"`
	ActorID   string    `json:"actorId"`
	TargetID  string    `json:"targetId"`
	IP        string    `json:"ip"`
	UserAgent string    `json:"userAgent"`
	Detail    string    `json:"detail"`
}

type AuditLogConnection struct {
	Data     []*AuditLog `json:"data"`
	Total    int         `json:"total"`
	Page     int         `json:"page"`
	PageSize int         `json:"pageSize"`
}

type AuthPayload struct {
	Token        string  `json:"token"`
	RefreshToken *string `json:"refreshToken,omitempty"`
	User         *User   `json:"user"`
}

type BackupRecord struct {
	ID           string     `json:"id"`
	Type         string     `json:"type"`
	Status       string     `json:"status"`
	SizeBytes    int        `json:"sizeBytes"`
	DurationMs   int        `json:"durationMs"`
	Destination  string     `json:"destination"`
	ErrorMessage *string    `json:"errorMessage,omitempty"`
	StartedAt    time.Time  `json:"startedAt"`
	CompletedAt  *time.Time `json:"completedAt,omitempty"`
}

type BackupStatus struct {
	LastBackup      *BackupRecord   `json:"lastBackup,omitempty"`
	Records         []*BackupRecord `json:"records"`
	IsConfigured    bool            `json:"isConfigured"`
	ScheduleEnabled bool            `json:"scheduleEnabled"`
	NextScheduled   *time.Time      `json:"nextScheduled,omitempty"`
}

type BatchProxyInput struct {
	Proxies []*BatchProxyItem `json:"proxies"`
}

type BatchProxyItem struct {
	URL    string  `json:"url"`
	Type   *string `json:"type,omitempty"`
	Region *string `json:"region,omitempty"`
}

type BatchProxyResult struct {
	Success int      `json:"success"`
	Failed  int      `json:"failed"`
	Proxies []*Proxy `json:"proxies"`
	Errors  []string `json:"errors,omitempty"`
}

type Budget struct {
	ID               string  `json:"id"`
	OrgID            string  `json:"orgId"`
	MonthlyLimitUsd  float64 `json:"monthlyLimitUsd"`
	AlertThreshold   float64 `json:"alertThreshold"`
	EnforceHardLimit bool    `json:"enforceHardLimit"`
	IsActive         bool    `json:"isActive"`
	WebhookURL       *string `json:"webhookUrl,omitempty"`
	Email            *string `json:"email,omitempty"`
}

type BudgetInput struct {
	MonthlyLimitUsd  float64  `json:"monthlyLimitUsd"`
	AlertThreshold   *float64 `json:"alertThreshold,omitempty"`
	EnforceHardLimit *bool    `json:"enforceHardLimit,omitempty"`
	WebhookURL       *string  `json:"webhookUrl,omitempty"`
	Email            *string  `json:"email,omitempty"`
}

type BudgetStatus struct {
	Budget          *Budget `json:"budget,omitempty"`
	CurrentSpend    float64 `json:"currentSpend"`
	RemainingBudget float64 `json:"remainingBudget"`
	PercentUsed     float64 `json:"percentUsed"`
	IsOverBudget    bool    `json:"isOverBudget"`
}

type CacheConfig struct {
	ID                  string  `json:"id"`
	IsEnabled           bool    `json:"isEnabled"`
	SimilarityThreshold float64 `json:"similarityThreshold"`
	DefaultTTLMinutes   int     `json:"defaultTtlMinutes"`
	EmbeddingModel      string  `json:"embeddingModel"`
	MaxCacheSize        int     `json:"maxCacheSize"`
}

type CacheConfigInput struct {
	IsEnabled           bool    `json:"isEnabled"`
	SimilarityThreshold float64 `json:"similarityThreshold"`
	DefaultTTLMinutes   int     `json:"defaultTtlMinutes"`
	EmbeddingModel      string  `json:"embeddingModel"`
	MaxCacheSize        int     `json:"maxCacheSize"`
}

type CacheStats struct {
	TotalCaches int `json:"totalCaches"`
	TotalHits   int `json:"totalHits"`
}

type ChangePasswordInput struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type CheckoutSession struct {
	URL string `json:"url"`
}

type Coupon struct {
	ID             string     `json:"id"`
	Code           string     `json:"code"`
	Name           string     `json:"name"`
	Type           string     `json:"type"`
	DiscountValue  float64    `json:"discountValue"`
	MinAmount      float64    `json:"minAmount"`
	MaxUses        int        `json:"maxUses"`
	UseCount       int        `json:"useCount"`
	MaxUsesPerUser int        `json:"maxUsesPerUser"`
	IsActive       bool       `json:"isActive"`
	ExpiresAt      *time.Time `json:"expiresAt,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
}

type CouponInput struct {
	Code           string     `json:"code"`
	Name           string     `json:"name"`
	Type           string     `json:"type"`
	DiscountValue  float64    `json:"discountValue"`
	MinAmount      *float64   `json:"minAmount,omitempty"`
	MaxUses        *int       `json:"maxUses,omitempty"`
	MaxUsesPerUser *int       `json:"maxUsesPerUser,omitempty"`
	IsActive       *bool      `json:"isActive,omitempty"`
	ExpiresAt      *time.Time `json:"expiresAt,omitempty"`
}

type CreateIdentityProviderInput struct {
	OrgID            string  `json:"orgId"`
	Type             string  `json:"type"`
	Name             string  `json:"name"`
	Domains          string  `json:"domains"`
	OidcClientID     *string `json:"oidcClientId,omitempty"`
	OidcClientSecret *string `json:"oidcClientSecret,omitempty"`
	OidcIssuerURL    *string `json:"oidcIssuerUrl,omitempty"`
	SamlEntityID     *string `json:"samlEntityId,omitempty"`
	SamlSsoURL       *string `json:"samlSsoUrl,omitempty"`
	SamlIdpCert      *string `json:"samlIdpCert,omitempty"`
	EnableJit        *bool   `json:"enableJit,omitempty"`
	DefaultRole      *string `json:"defaultRole,omitempty"`
	GroupRoleMapping *string `json:"groupRoleMapping,omitempty"`
}

type CreateRoutingRuleInput struct {
	Name               string  `json:"name"`
	Description        *string `json:"description,omitempty"`
	ModelPattern       string  `json:"modelPattern"`
	TargetProviderID   string  `json:"targetProviderId"`
	FallbackProviderID *string `json:"fallbackProviderId,omitempty"`
	Priority           int     `json:"priority"`
	IsEnabled          bool    `json:"isEnabled"`
}

type CreateTaskInput struct {
	Type       string  `json:"type"`
	Input      string  `json:"input"`
	WebhookURL *string `json:"webhookUrl,omitempty"`
}

type CreateWebhookEndpointInput struct {
	ProjectID   string   `json:"projectId"`
	URL         string   `json:"url"`
	Events      []string `json:"events"`
	Description *string  `json:"description,omitempty"`
}

type DailyStats struct {
	Date        string  `json:"date"`
	Requests    int     `json:"requests"`
	TotalTokens int     `json:"totalTokens"`
	TotalCost   float64 `json:"totalCost"`
}

type Dashboard struct {
	TotalRequests    int             `json:"totalRequests"`
	SuccessRate      float64         `json:"successRate"`
	TotalTokens      int             `json:"totalTokens"`
	TotalCost        float64         `json:"totalCost"`
	AverageLatencyMs float64         `json:"averageLatencyMs"`
	ActiveUsers      int             `json:"activeUsers"`
	ActiveProviders  int             `json:"activeProviders"`
	ActiveProxies    int             `json:"activeProxies"`
	RequestsToday    int             `json:"requestsToday"`
	CostToday        float64         `json:"costToday"`
	TokensToday      int             `json:"tokensToday"`
	ErrorCount       int             `json:"errorCount"`
	McpCallCount     int             `json:"mcpCallCount"`
	McpErrorCount    int             `json:"mcpErrorCount"`
	APIKeys          *APIKeysSummary `json:"apiKeys"`
	Proxies          *ProxiesSummary `json:"proxies"`
}

type DatabaseLoad struct {
	ActiveConnections     int     `json:"activeConnections"`
	MaxConnections        int     `json:"maxConnections"`
	PoolIdle              int     `json:"poolIdle"`
	PoolInUse             int     `json:"poolInUse"`
	TransactionsPerSecond float64 `json:"transactionsPerSecond"`
	CacheHitRate          float64 `json:"cacheHitRate"`
	Deadlocks             int     `json:"deadlocks"`
}

type DependencyStatus struct {
	Name      string  `json:"name"`
	Status    string  `json:"status"`
	LatencyMs float64 `json:"latencyMs"`
	Version   *string `json:"version,omitempty"`
	Details   *string `json:"details,omitempty"`
}

type DlpConfig struct {
	ID              string      `json:"id"`
	ProjectID       string      `json:"projectId"`
	IsEnabled       bool        `json:"isEnabled"`
	Strategy        DlpStrategy `json:"strategy"`
	MaskEmails      bool        `json:"maskEmails"`
	MaskPhones      bool        `json:"maskPhones"`
	MaskCreditCards bool        `json:"maskCreditCards"`
	MaskSsn         bool        `json:"maskSsn"`
	MaskAPIKeys     bool        `json:"maskApiKeys"`
	CustomRegex     []string    `json:"customRegex"`
	CreatedAt       time.Time   `json:"createdAt"`
	UpdatedAt       time.Time   `json:"updatedAt"`
}

type DlpTestResult struct {
	OriginalText string `json:"originalText"`
	ScrubbedText string `json:"scrubbedText"`
	HasPii       bool   `json:"hasPii"`
	Blocked      bool   `json:"blocked"`
}

type Document struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Slug        string    `json:"slug"`
	Content     string    `json:"content"`
	Category    string    `json:"category"`
	SortOrder   int       `json:"sortOrder"`
	IsPublished bool      `json:"isPublished"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type DocumentInput struct {
	Title       string  `json:"title"`
	Slug        string  `json:"slug"`
	Content     string  `json:"content"`
	Category    *string `json:"category,omitempty"`
	SortOrder   *int    `json:"sortOrder,omitempty"`
	IsPublished *bool   `json:"isPublished,omitempty"`
}

type ErrorLog struct {
	ID           string    `json:"id"`
	TrajectoryID string    `json:"trajectoryId"`
	TraceID      string    `json:"traceId"`
	Provider     string    `json:"provider"`
	Model        string    `json:"model"`
	StatusCode   int       `json:"statusCode"`
	Headers      string    `json:"headers"`
	ResponseBody string    `json:"responseBody"`
	CreatedAt    time.Time `json:"createdAt"`
}

type ErrorLogConnection struct {
	Data     []*ErrorLog `json:"data"`
	Total    int         `json:"total"`
	Page     int         `json:"page"`
	PageSize int         `json:"pageSize"`
}

type GenerateRedeemCodesInput struct {
	Type         string     `json:"type"`
	CreditAmount *float64   `json:"creditAmount,omitempty"`
	PlanID       *string    `json:"planId,omitempty"`
	PlanDays     *int       `json:"planDays,omitempty"`
	Count        int        `json:"count"`
	ExpiresAt    *time.Time `json:"expiresAt,omitempty"`
	Note         *string    `json:"note,omitempty"`
}

type GenerateRedeemCodesResult struct {
	Codes []string `json:"codes"`
	Count int      `json:"count"`
}

type HealthEvent struct {
	ID         string    `json:"id"`
	TargetType string    `json:"targetType"`
	TargetID   string    `json:"targetId"`
	Status     string    `json:"status"`
	Message    *string   `json:"message,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
}

type IdentityProvider struct {
	ID               string        `json:"id"`
	OrgID            string        `json:"orgId"`
	Organization     *Organization `json:"organization"`
	Type             string        `json:"type"`
	Name             string        `json:"name"`
	IsActive         bool          `json:"isActive"`
	Domains          string        `json:"domains"`
	OidcClientID     *string       `json:"oidcClientId,omitempty"`
	OidcIssuerURL    *string       `json:"oidcIssuerUrl,omitempty"`
	SamlEntityID     *string       `json:"samlEntityId,omitempty"`
	SamlSsoURL       *string       `json:"samlSsoUrl,omitempty"`
	SamlIdpCert      *string       `json:"samlIdpCert,omitempty"`
	EnableJit        bool          `json:"enableJit"`
	DefaultRole      string        `json:"defaultRole"`
	GroupRoleMapping string        `json:"groupRoleMapping"`
	CreatedAt        time.Time     `json:"createdAt"`
	UpdatedAt        time.Time     `json:"updatedAt"`
}

type IntegrationConfig struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Enabled   bool      `json:"enabled"`
	Config    string    `json:"config"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type InviteCode struct {
	ID        string     `json:"id"`
	Code      string     `json:"code"`
	CreatedBy string     `json:"createdBy"`
	MaxUses   int        `json:"maxUses"`
	UseCount  int        `json:"useCount"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	IsActive  bool       `json:"isActive"`
	CreatedAt time.Time  `json:"createdAt"`
}

type InviteCodeInput struct {
	MaxUses   *int       `json:"maxUses,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type McpEnvInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type McpResource struct {
	ID          string  `json:"id"`
	ServerID    string  `json:"serverId"`
	Name        string  `json:"name"`
	URI         string  `json:"uri"`
	Description *string `json:"description,omitempty"`
	MimeType    *string `json:"mimeType,omitempty"`
}

type McpServer struct {
	ID            string     `json:"id"`
	Name          string     `json:"name"`
	Type          string     `json:"type"`
	Command       *string    `json:"command,omitempty"`
	Args          []string   `json:"args,omitempty"`
	URL           *string    `json:"url,omitempty"`
	IsActive      bool       `json:"isActive"`
	Status        string     `json:"status"`
	LastError     *string    `json:"lastError,omitempty"`
	LastCheckedAt *time.Time `json:"lastCheckedAt,omitempty"`
	Tools         []*McpTool `json:"tools,omitempty"`
	CreatedAt     time.Time  `json:"createdAt"`
}

type McpServerInput struct {
	Name     string         `json:"name"`
	Type     string         `json:"type"`
	Command  *string        `json:"command,omitempty"`
	Args     []string       `json:"args,omitempty"`
	URL      *string        `json:"url,omitempty"`
	IsActive *bool          `json:"isActive,omitempty"`
	Env      []*McpEnvInput `json:"env,omitempty"`
}

type McpTool struct {
	ID          string  `json:"id"`
	ServerID    string  `json:"serverId"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	InputSchema *string `json:"inputSchema,omitempty"`
	IsActive    bool    `json:"isActive"`
}

type MfaSecretInfo struct {
	Secret      string   `json:"secret"`
	QRCodeURL   string   `json:"qrCodeUrl"`
	BackupCodes []string `json:"backupCodes"`
}

type Model struct {
	ID               string    `json:"id"`
	ProviderID       string    `json:"providerId"`
	Name             string    `json:"name"`
	DisplayName      string    `json:"displayName"`
	InputPricePer1k  float64   `json:"inputPricePer1k"`
	OutputPricePer1k float64   `json:"outputPricePer1k"`
	PricePerSecond   *float64  `json:"pricePerSecond,omitempty"`
	PricePerImage    *float64  `json:"pricePerImage,omitempty"`
	PricePerMinute   *float64  `json:"pricePerMinute,omitempty"`
	MaxTokens        int       `json:"maxTokens"`
	IsActive         bool      `json:"isActive"`
	CreatedAt        time.Time `json:"createdAt"`
}

type ModelInput struct {
	Name             string   `json:"name"`
	DisplayName      *string  `json:"displayName,omitempty"`
	InputPricePer1k  *float64 `json:"inputPricePer1k,omitempty"`
	OutputPricePer1k *float64 `json:"outputPricePer1k,omitempty"`
	PricePerSecond   *float64 `json:"pricePerSecond,omitempty"`
	PricePerImage    *float64 `json:"pricePerImage,omitempty"`
	PricePerMinute   *float64 `json:"pricePerMinute,omitempty"`
	MaxTokens        *int     `json:"maxTokens,omitempty"`
	IsActive         *bool    `json:"isActive,omitempty"`
}

type ModelStats struct {
	ModelID      string  `json:"modelId"`
	ModelName    string  `json:"modelName"`
	Requests     int     `json:"requests"`
	InputTokens  int     `json:"inputTokens"`
	OutputTokens int     `json:"outputTokens"`
	TotalCost    float64 `json:"totalCost"`
}

type Mutation struct {
}

type NotificationChannel struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	IsEnabled bool      `json:"isEnabled"`
	Config    string    `json:"config"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type NotificationChannelInput struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	IsEnabled *bool  `json:"isEnabled,omitempty"`
	Config    string `json:"config"`
}

type Order struct {
	ID            string    `json:"id"`
	OrderNo       string    `json:"orderNo"`
	Amount        float64   `json:"amount"`
	Currency      string    `json:"currency"`
	Status        string    `json:"status"`
	PaymentMethod string    `json:"paymentMethod"`
	CreatedAt     time.Time `json:"createdAt"`
	Plan          *Plan     `json:"plan,omitempty"`
}

type Organization struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	BillingLimit float64   `json:"billingLimit"`
	CreatedAt    time.Time `json:"createdAt"`
}

type OrganizationMember struct {
	UserID    string        `json:"userId"`
	OrgID     string        `json:"orgId"`
	Role      string        `json:"role"`
	User      *UserListItem `json:"user"`
	CreatedAt time.Time     `json:"createdAt"`
}

type Plan struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Description  string  `json:"description"`
	PriceMonth   float64 `json:"priceMonth"`
	TokenLimit   int     `json:"tokenLimit"`
	RateLimit    int     `json:"rateLimit"`
	SupportLevel string  `json:"supportLevel"`
	IsActive     bool    `json:"isActive"`
	Features     *string `json:"features,omitempty"`
}

type PlanInput struct {
	Name         string  `json:"name"`
	Description  *string `json:"description,omitempty"`
	PriceMonth   float64 `json:"priceMonth"`
	TokenLimit   int     `json:"tokenLimit"`
	RateLimit    int     `json:"rateLimit"`
	SupportLevel *string `json:"supportLevel,omitempty"`
	IsActive     *bool   `json:"isActive,omitempty"`
	Features     *string `json:"features,omitempty"`
}

type Project struct {
	ID             string    `json:"id"`
	OrgID          string    `json:"orgId"`
	Name           string    `json:"name"`
	Description    *string   `json:"description,omitempty"`
	QuotaLimit     float64   `json:"quotaLimit"`
	WhiteListedIps *string   `json:"whiteListedIps,omitempty"`
	CreatedAt      time.Time `json:"createdAt"`
}

type PromptTemplate struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	Description     string         `json:"description"`
	ProjectID       *string        `json:"projectId,omitempty"`
	IsActive        bool           `json:"isActive"`
	ActiveVersionID *string        `json:"activeVersionId,omitempty"`
	ActiveVersion   *PromptVersion `json:"activeVersion,omitempty"`
	VersionCount    int            `json:"versionCount"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       time.Time      `json:"updatedAt"`
}

type PromptTemplateConnection struct {
	Data  []*PromptTemplate `json:"data"`
	Total int               `json:"total"`
}

type PromptTemplateInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	ProjectID   *string `json:"projectId,omitempty"`
	IsActive    *bool   `json:"isActive,omitempty"`
}

type PromptVersion struct {
	ID         string    `json:"id"`
	TemplateID string    `json:"templateId"`
	Version    int       `json:"version"`
	Content    string    `json:"content"`
	Model      *string   `json:"model,omitempty"`
	Parameters *string   `json:"parameters,omitempty"`
	ChangeLog  *string   `json:"changeLog,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
}

type PromptVersionInput struct {
	TemplateID string  `json:"templateId"`
	Content    string  `json:"content"`
	Model      *string `json:"model,omitempty"`
	Parameters *string `json:"parameters,omitempty"`
	ChangeLog  *string `json:"changeLog,omitempty"`
}

type Provider struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	BaseURL        string    `json:"baseUrl"`
	IsActive       bool      `json:"isActive"`
	Priority       int       `json:"priority"`
	Weight         float64   `json:"weight"`
	MaxRetries     int       `json:"maxRetries"`
	Timeout        int       `json:"timeout"`
	UseProxy       bool      `json:"useProxy"`
	DefaultProxyID *string   `json:"defaultProxyId,omitempty"`
	RequiresAPIKey bool      `json:"requiresApiKey"`
	CreatedAt      time.Time `json:"createdAt"`
}

type ProviderAPIKey struct {
	ID         string     `json:"id"`
	ProviderID string     `json:"providerId"`
	Alias      string     `json:"alias"`
	KeyPrefix  string     `json:"keyPrefix"`
	IsActive   bool       `json:"isActive"`
	Priority   int        `json:"priority"`
	Weight     float64    `json:"weight"`
	RateLimit  int        `json:"rateLimit"`
	UsageCount int        `json:"usageCount"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
}

type ProviderAPIKeyInput struct {
	APIKey    string   `json:"apiKey"`
	Alias     string   `json:"alias"`
	Priority  *int     `json:"priority,omitempty"`
	Weight    *float64 `json:"weight,omitempty"`
	RateLimit *int     `json:"rateLimit,omitempty"`
}

type ProviderHealth struct {
	ID           string     `json:"id"`
	Name         string     `json:"name"`
	BaseURL      string     `json:"baseUrl"`
	IsActive     bool       `json:"isActive"`
	IsHealthy    bool       `json:"isHealthy"`
	UseProxy     bool       `json:"useProxy"`
	ResponseTime float64    `json:"responseTime"`
	LastCheck    *time.Time `json:"lastCheck,omitempty"`
	SuccessRate  float64    `json:"successRate"`
	ErrorMessage *string    `json:"errorMessage,omitempty"`
}

type ProviderInput struct {
	Name           *string  `json:"name,omitempty"`
	BaseURL        *string  `json:"baseUrl,omitempty"`
	IsActive       *bool    `json:"isActive,omitempty"`
	Priority       *int     `json:"priority,omitempty"`
	Weight         *float64 `json:"weight,omitempty"`
	MaxRetries     *int     `json:"maxRetries,omitempty"`
	Timeout        *int     `json:"timeout,omitempty"`
	UseProxy       *bool    `json:"useProxy,omitempty"`
	DefaultProxyID *string  `json:"defaultProxyId,omitempty"`
	RequiresAPIKey *bool    `json:"requiresApiKey,omitempty"`
}

type ProviderStats struct {
	ProviderID   string  `json:"providerId"`
	ProviderName string  `json:"providerName"`
	Requests     int     `json:"requests"`
	Tokens       int     `json:"tokens"`
	SuccessRate  float64 `json:"successRate"`
	AvgLatencyMs float64 `json:"avgLatencyMs"`
	TotalCost    float64 `json:"totalCost"`
}

type ProviderUsage struct {
	ProviderID   string  `json:"providerId"`
	ProviderName string  `json:"providerName"`
	Requests     int     `json:"requests"`
	Tokens       int     `json:"tokens"`
	Cost         float64 `json:"cost"`
}

type ProxiesSummary struct {
	Total   int `json:"total"`
	Healthy int `json:"healthy"`
}

type Proxy struct {
	ID              string     `json:"id"`
	URL             string     `json:"url"`
	Type            string     `json:"type"`
	Region          string     `json:"region"`
	IsActive        bool       `json:"isActive"`
	Weight          float64    `json:"weight"`
	SuccessCount    int        `json:"successCount"`
	FailureCount    int        `json:"failureCount"`
	AvgLatency      float64    `json:"avgLatency"`
	LastChecked     *time.Time `json:"lastChecked,omitempty"`
	CreatedAt       time.Time  `json:"createdAt"`
	HasAuth         bool       `json:"hasAuth"`
	UpstreamProxyID *string    `json:"upstreamProxyId,omitempty"`
}

type ProxyHealth struct {
	ID           string     `json:"id"`
	URL          string     `json:"url"`
	Type         string     `json:"type"`
	Region       string     `json:"region"`
	IsActive     bool       `json:"isActive"`
	IsHealthy    bool       `json:"isHealthy"`
	ResponseTime float64    `json:"responseTime"`
	LastCheck    *time.Time `json:"lastCheck,omitempty"`
	SuccessRate  float64    `json:"successRate"`
}

type ProxyInput struct {
	URL             string  `json:"url"`
	Type            string  `json:"type"`
	Region          *string `json:"region,omitempty"`
	Username        *string `json:"username,omitempty"`
	Password        *string `json:"password,omitempty"`
	UpstreamProxyID *string `json:"upstreamProxyId,omitempty"`
}

type ProxyTestResult struct {
	ID        string  `json:"id"`
	URL       string  `json:"url"`
	IsHealthy bool    `json:"isHealthy"`
	LatencyMs float64 `json:"latencyMs"`
	Error     *string `json:"error,omitempty"`
}

type Query struct {
}

type QuotaInput struct {
	MonthlyTokenLimit *int     `json:"monthlyTokenLimit,omitempty"`
	MonthlyBudgetUsd  *float64 `json:"monthlyBudgetUsd,omitempty"`
}

type RedeemCode struct {
	ID           string     `json:"id"`
	Code         string     `json:"code"`
	Type         string     `json:"type"`
	CreditAmount float64    `json:"creditAmount"`
	PlanID       *string    `json:"planId,omitempty"`
	PlanDays     int        `json:"planDays"`
	UsedBy       *string    `json:"usedBy,omitempty"`
	UsedAt       *time.Time `json:"usedAt,omitempty"`
	ExpiresAt    *time.Time `json:"expiresAt,omitempty"`
	IsActive     bool       `json:"isActive"`
	BatchID      string     `json:"batchId"`
	Note         *string    `json:"note,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
}

type RedeemCodeConnection struct {
	Nodes []*RedeemCode `json:"nodes"`
	Total int           `json:"total"`
}

type RedeemRecord struct {
	ID           string    `json:"id"`
	Code         string    `json:"code"`
	CreditAmount float64   `json:"creditAmount"`
	PlanName     *string   `json:"planName,omitempty"`
	RedeemedAt   time.Time `json:"redeemedAt"`
}

type RedeemResult struct {
	Success      bool     `json:"success"`
	Message      string   `json:"message"`
	CreditAmount *float64 `json:"creditAmount,omitempty"`
	PlanName     *string  `json:"planName,omitempty"`
}

type RedisLoad struct {
	ConnectedClients int     `json:"connectedClients"`
	UsedMemoryMb     float64 `json:"usedMemoryMB"`
	MaxMemoryMb      float64 `json:"maxMemoryMB"`
	OpsPerSecond     float64 `json:"opsPerSecond"`
	HitRate          float64 `json:"hitRate"`
	KeyCount         int     `json:"keyCount"`
}

type RegisterInput struct {
	Email      string  `json:"email"`
	Password   string  `json:"password"`
	Name       string  `json:"name"`
	InviteCode *string `json:"inviteCode,omitempty"`
}

type RegistrationMode struct {
	Mode               string `json:"mode"`
	InviteCodeRequired bool   `json:"inviteCodeRequired"`
}

type ResetPasswordInput struct {
	Token       string `json:"token"`
	NewPassword string `json:"newPassword"`
}

type RoutingRule struct {
	ID                 string    `json:"id"`
	Name               string    `json:"name"`
	Description        string    `json:"description"`
	ModelPattern       string    `json:"modelPattern"`
	TargetProviderID   string    `json:"targetProviderId"`
	FallbackProviderID *string   `json:"fallbackProviderId,omitempty"`
	Priority           int       `json:"priority"`
	IsEnabled          bool      `json:"isEnabled"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
	TargetProvider     *Provider `json:"targetProvider,omitempty"`
	FallbackProvider   *Provider `json:"fallbackProvider,omitempty"`
}

type RoutingRuleList struct {
	Data     []*RoutingRule `json:"data"`
	Total    int            `json:"total"`
	Page     int            `json:"page"`
	PageSize int            `json:"pageSize"`
}

type RuntimeInfo struct {
	Goroutines  int     `json:"goroutines"`
	HeapAllocMb float64 `json:"heapAllocMB"`
	HeapSysMb   float64 `json:"heapSysMB"`
	GcPauseMs   float64 `json:"gcPauseMs"`
	NumGc       int     `json:"numGC"`
	CPUCores    int     `json:"cpuCores"`
}

type SemanticCache struct {
	ID        string    `json:"id"`
	Hash      string    `json:"hash"`
	Provider  string    `json:"provider"`
	Model     string    `json:"model"`
	HitCount  int       `json:"hitCount"`
	CreatedAt time.Time `json:"createdAt"`
}

type ServiceInfo struct {
	Version    string `json:"version"`
	GitCommit  string `json:"gitCommit"`
	BuildTime  string `json:"buildTime"`
	Uptime     string `json:"uptime"`
	ConfigMode string `json:"configMode"`
}

type ServiceLoad struct {
	RequestsInFlight  int     `json:"requestsInFlight"`
	RequestsPerSecond float64 `json:"requestsPerSecond"`
	AvgLatencyMs      float64 `json:"avgLatencyMs"`
	P95LatencyMs      float64 `json:"p95LatencyMs"`
	ErrorRate         float64 `json:"errorRate"`
}

type SystemLoad struct {
	Service  *ServiceLoad  `json:"service"`
	Database *DatabaseLoad `json:"database"`
	Redis    *RedisLoad    `json:"redis"`
}

type SystemSLA struct {
	TotalRequests    int     `json:"totalRequests"`
	FailureRate      float64 `json:"failureRate"`
	AvgLatencyMs     float64 `json:"avgLatencyMs"`
	P95LatencyMs     float64 `json:"p95LatencyMs"`
	P99LatencyMs     float64 `json:"p99LatencyMs"`
	ActiveProviders  int     `json:"activeProviders"`
	HealthyProviders int     `json:"healthyProviders"`
}

type SystemSettings struct {
	RegistrationMode  string   `json:"registrationMode"`
	DefaultTokenLimit *int     `json:"defaultTokenLimit,omitempty"`
	DefaultBudgetUsd  *float64 `json:"defaultBudgetUsd,omitempty"`
	Site              *string  `json:"site,omitempty"`
	Security          *string  `json:"security,omitempty"`
	Defaults          *string  `json:"defaults,omitempty"`
	Email             *string  `json:"email,omitempty"`
	Backup            *string  `json:"backup,omitempty"`
	Payment           *string  `json:"payment,omitempty"`
	Oauth             *string  `json:"oauth,omitempty"`
}

type SystemSettingsInput struct {
	Category string `json:"category"`
	Data     string `json:"data"`
}

type SystemStatus struct {
	Service       *ServiceInfo        `json:"service"`
	Runtime       *RuntimeInfo        `json:"runtime"`
	Dependencies  []*DependencyStatus `json:"dependencies"`
	OverallStatus string              `json:"overallStatus"`
}

type Task struct {
	ID          string     `json:"id"`
	ProjectID   string     `json:"projectId"`
	Type        string     `json:"type"`
	Status      string     `json:"status"`
	Input       string     `json:"input"`
	Result      *string    `json:"result,omitempty"`
	Error       *string    `json:"error,omitempty"`
	Progress    int        `json:"progress"`
	WebhookURL  *string    `json:"webhookUrl,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	StartedAt   *time.Time `json:"startedAt,omitempty"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
}

type TaskConnection struct {
	Data  []*Task `json:"data"`
	Total int     `json:"total"`
}

type UpdateDlpConfigInput struct {
	ProjectID       string       `json:"projectId"`
	IsEnabled       *bool        `json:"isEnabled,omitempty"`
	Strategy        *DlpStrategy `json:"strategy,omitempty"`
	MaskEmails      *bool        `json:"maskEmails,omitempty"`
	MaskPhones      *bool        `json:"maskPhones,omitempty"`
	MaskCreditCards *bool        `json:"maskCreditCards,omitempty"`
	MaskSsn         *bool        `json:"maskSsn,omitempty"`
	MaskAPIKeys     *bool        `json:"maskApiKeys,omitempty"`
	CustomRegex     []string     `json:"customRegex,omitempty"`
}

type UpdateIdentityProviderInput struct {
	Name             *string `json:"name,omitempty"`
	IsActive         *bool   `json:"isActive,omitempty"`
	Domains          *string `json:"domains,omitempty"`
	OidcClientID     *string `json:"oidcClientId,omitempty"`
	OidcClientSecret *string `json:"oidcClientSecret,omitempty"`
	OidcIssuerURL    *string `json:"oidcIssuerUrl,omitempty"`
	SamlEntityID     *string `json:"samlEntityId,omitempty"`
	SamlSsoURL       *string `json:"samlSsoUrl,omitempty"`
	SamlIdpCert      *string `json:"samlIdpCert,omitempty"`
	EnableJit        *bool   `json:"enableJit,omitempty"`
	DefaultRole      *string `json:"defaultRole,omitempty"`
	GroupRoleMapping *string `json:"groupRoleMapping,omitempty"`
}

type UpdateIntegrationInput struct {
	Enabled bool   `json:"enabled"`
	Config  string `json:"config"`
}

type UpdateNotificationChannelInput struct {
	Name      *string `json:"name,omitempty"`
	IsEnabled *bool   `json:"isEnabled,omitempty"`
	Config    *string `json:"config,omitempty"`
}

type UpdateProfileInput struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type UpdateProjectInput struct {
	Name           *string  `json:"name,omitempty"`
	Description    *string  `json:"description,omitempty"`
	QuotaLimit     *float64 `json:"quotaLimit,omitempty"`
	WhiteListedIps *string  `json:"whiteListedIps,omitempty"`
}

type UpdateProviderAPIKeyInput struct {
	Priority  *int     `json:"priority,omitempty"`
	Weight    *float64 `json:"weight,omitempty"`
	RateLimit *int     `json:"rateLimit,omitempty"`
}

type UpdateRoutingRuleInput struct {
	Name               *string `json:"name,omitempty"`
	Description        *string `json:"description,omitempty"`
	ModelPattern       *string `json:"modelPattern,omitempty"`
	TargetProviderID   *string `json:"targetProviderId,omitempty"`
	FallbackProviderID *string `json:"fallbackProviderId,omitempty"`
	Priority           *int    `json:"priority,omitempty"`
	IsEnabled          *bool   `json:"isEnabled,omitempty"`
}

type UpdateWebhookEndpointInput struct {
	URL         *string  `json:"url,omitempty"`
	Events      []string `json:"events,omitempty"`
	IsActive    *bool    `json:"isActive,omitempty"`
	Description *string  `json:"description,omitempty"`
}

type UsageChartPoint struct {
	Date     string  `json:"date"`
	Requests int     `json:"requests"`
	Tokens   int     `json:"tokens"`
	Cost     float64 `json:"cost"`
}

type UsageConnection struct {
	Data  []*UsageRecord `json:"data"`
	Total int            `json:"total"`
}

type UsageRecord struct {
	ID           string    `json:"id"`
	ModelName    string    `json:"modelName"`
	InputTokens  int       `json:"inputTokens"`
	OutputTokens int       `json:"outputTokens"`
	Cost         float64   `json:"cost"`
	LatencyMs    int       `json:"latencyMs"`
	IsSuccess    bool      `json:"isSuccess"`
	CreatedAt    time.Time `json:"createdAt"`
}

type UsageSummary struct {
	TotalRequests int     `json:"totalRequests"`
	SuccessRate   float64 `json:"successRate"`
	TotalTokens   int     `json:"totalTokens"`
	TotalCost     float64 `json:"totalCost"`
}

type User struct {
	ID                    string     `json:"id"`
	Email                 string     `json:"email"`
	Name                  string     `json:"name"`
	Role                  string     `json:"role"`
	IsActive              bool       `json:"isActive"`
	RequirePasswordChange bool       `json:"requirePasswordChange"`
	MonthlyTokenLimit     *int       `json:"monthlyTokenLimit,omitempty"`
	MonthlyBudgetUsd      *float64   `json:"monthlyBudgetUsd,omitempty"`
	Balance               *float64   `json:"balance,omitempty"`
	CreatedAt             time.Time  `json:"createdAt"`
	LastLoginAt           *time.Time `json:"lastLoginAt,omitempty"`
	MfaEnabled            bool       `json:"mfaEnabled"`
}

type UserConnection struct {
	Data  []*UserListItem `json:"data"`
	Total int             `json:"total"`
}

type UserDetail struct {
	ID                string            `json:"id"`
	Email             string            `json:"email"`
	Name              string            `json:"name"`
	Role              string            `json:"role"`
	IsActive          bool              `json:"isActive"`
	CreatedAt         time.Time         `json:"createdAt"`
	APIKeys           int               `json:"apiKeys"`
	MonthlyTokenLimit *int              `json:"monthlyTokenLimit,omitempty"`
	MonthlyBudgetUsd  *float64          `json:"monthlyBudgetUsd,omitempty"`
	MfaEnabled        bool              `json:"mfaEnabled"`
	UsageMonth        *UserMonthlyUsage `json:"usageMonth,omitempty"`
}

type UserListItem struct {
	ID          string     `json:"id"`
	Email       string     `json:"email"`
	Name        string     `json:"name"`
	Role        string     `json:"role"`
	IsActive    bool       `json:"isActive"`
	LastLoginAt *time.Time `json:"lastLoginAt,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	APIKeyCount int        `json:"apiKeyCount"`
}

type UserMonthlyUsage struct {
	TotalRequests int     `json:"totalRequests"`
	TotalTokens   int     `json:"totalTokens"`
	TotalCost     float64 `json:"totalCost"`
	AvgLatency    float64 `json:"avgLatency"`
	SuccessRate   float64 `json:"successRate"`
	ErrorCount    int     `json:"errorCount"`
}

type UserSubscription struct {
	ID                 string    `json:"id"`
	OrgID              string    `json:"orgId"`
	PlanID             string    `json:"planId"`
	Status             string    `json:"status"`
	CurrentPeriodStart time.Time `json:"currentPeriodStart"`
	CurrentPeriodEnd   time.Time `json:"currentPeriodEnd"`
	CancelAtPeriodEnd  bool      `json:"cancelAtPeriodEnd"`
	Plan               *Plan     `json:"plan"`
}

type WebhookDelivery struct {
	ID           string    `json:"id"`
	EndpointID   string    `json:"endpointId"`
	EventType    string    `json:"eventType"`
	Payload      string    `json:"payload"`
	Status       string    `json:"status"`
	StatusCode   int       `json:"statusCode"`
	ResponseBody *string   `json:"responseBody,omitempty"`
	ErrorMessage *string   `json:"errorMessage,omitempty"`
	RetryCount   int       `json:"retryCount"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type WebhookEndpoint struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"projectId"`
	URL         string    `json:"url"`
	Secret      *string   `json:"secret,omitempty"`
	Events      []string  `json:"events"`
	IsActive    bool      `json:"isActive"`
	Description *string   `json:"description,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type DlpStrategy string

const (
	DlpStrategyRedact DlpStrategy = "REDACT"
	DlpStrategyBlock  DlpStrategy = "BLOCK"
)

var AllDlpStrategy = []DlpStrategy{
	DlpStrategyRedact,
	DlpStrategyBlock,
}

func (e DlpStrategy) IsValid() bool {
	switch e {
	case DlpStrategyRedact, DlpStrategyBlock:
		return true
	}
	return false
}

func (e DlpStrategy) String() string {
	return string(e)
}

func (e *DlpStrategy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DlpStrategy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DlpStrategy", str)
	}
	return nil
}

func (e DlpStrategy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DlpStrategy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DlpStrategy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleUser  Role = "USER"
	RoleAdmin Role = "ADMIN"
)

var AllRole = []Role{
	RoleUser,
	RoleAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleUser, RoleAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
