apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
  labels:
    {{- include "llm-router.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "llm-router.server.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    {{- include "llm-router.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "llm-router.web.selectorLabels" . | nindent 4 }}
