ALTER TABLE providers ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE providers ALTER COLUMN updated_at DROP NOT NULL;
ALTER TABLE providers ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE providers ALTER COLUMN updated_at DROP DEFAULT;
