package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"llm-router-platform/internal/crypto"
	"llm-router-platform/internal/graphql/directives"
	"llm-router-platform/internal/graphql/generated"
	"llm-router-platform/internal/graphql/model"
	"llm-router-platform/internal/models"
	"llm-router-platform/pkg/sanitize"
	"net/http"
	"net/smtp"
	"strings"
	"time"

	"github.com/google/uuid"
	"go.uber.org/zap"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	u, err := r.UserSvc.Authenticate(ctx, input.Email, input.Password)
	if err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}
	token, err := r.generateJWT(u)
	if err != nil {
		return nil, err
	}
	refresh, err := r.generateRefreshJWT(u)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{Token: token, RefreshToken: &refresh, User: userToGQL(u)}, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	u, err := r.UserSvc.Register(ctx, input.Email, input.Password, input.Name)
	if err != nil {
		return nil, err
	}
	token, err := r.generateJWT(u)
	if err != nil {
		return nil, err
	}
	refresh, err := r.generateRefreshJWT(u)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{Token: token, RefreshToken: &refresh, User: userToGQL(u)}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context) (*model.AuthPayload, error) {
	uid, err := directives.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	id, _ := uuid.Parse(uid)
	u, err := r.UserSvc.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	token, _ := r.generateJWT(u)
	return &model.AuthPayload{Token: token, User: userToGQL(u)}, nil
}

// RotateRefreshToken is the resolver for the rotateRefreshToken field.
func (r *mutationResolver) RotateRefreshToken(ctx context.Context, refreshToken string) (*model.AuthPayload, error) {
	uid, err := directives.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	id, _ := uuid.Parse(uid)
	u, err := r.UserSvc.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	token, _ := r.generateJWT(u)
	refresh, _ := r.generateRefreshJWT(u)
	return &model.AuthPayload{Token: token, RefreshToken: &refresh, User: userToGQL(u)}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	uid, err := directives.UserIDFromContext(ctx)
	if err != nil {
		return false, err
	}
	id, _ := uuid.Parse(uid)
	_ = r.UserSvc.InvalidateTokens(ctx, id)
	return true, nil
}

// ForgotPassword is the resolver for the forgotPassword field.
func (r *mutationResolver) ForgotPassword(ctx context.Context, email string) (bool, error) {
	u, err := r.UserSvc.GetByEmail(ctx, email)
	if err != nil {
		return true, nil // don't reveal if email exists
	}
	buf := make([]byte, 32)
	rand.Read(buf)
	token := hex.EncodeToString(buf)
	_ = r.EmailService.SendResetPasswordEmail(u.Email, token)
	return true, nil
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, input model.ResetPasswordInput) (bool, error) {
	return false, fmt.Errorf("not implemented: token-based reset")
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input model.ChangePasswordInput) (bool, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	if err := r.UserSvc.ChangePassword(ctx, id, input.OldPassword, input.NewPassword); err != nil {
		return false, err
	}
	return true, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.User, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	name := ""
	if input.Name != nil {
		name = *input.Name
	}
	if err := r.UserSvc.UpdateProfile(ctx, id, name); err != nil {
		return nil, err
	}
	u, _ := r.UserSvc.GetByID(ctx, id)
	return userToGQL(u), nil
}

// CreateAPIKey is the resolver for the createApiKey field.
func (r *mutationResolver) CreateAPIKey(ctx context.Context, name string) (*model.APIKeyWithSecret, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	key, secret, err := r.UserSvc.CreateAPIKey(ctx, id, name)
	if err != nil {
		return nil, err
	}
	return &model.APIKeyWithSecret{
		ID: key.ID.String(), Name: key.Name, Key: secret,
		KeyPrefix: key.KeyPrefix, IsActive: key.IsActive,
		CreatedAt: key.CreatedAt,
	}, nil
}

// RevokeAPIKey is the resolver for the revokeApiKey field.
func (r *mutationResolver) RevokeAPIKey(ctx context.Context, id string) (*model.APIKey, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	userID, _ := uuid.Parse(uid)
	keyID, _ := uuid.Parse(id)
	if err := r.UserSvc.RevokeAPIKey(ctx, userID, keyID); err != nil {
		return nil, err
	}
	key, _ := r.UserSvc.GetAPIKeyByID(ctx, keyID)
	return apiKeyToGQL(key), nil
}

// DeleteAPIKey is the resolver for the deleteApiKey field.
func (r *mutationResolver) DeleteAPIKey(ctx context.Context, id string) (bool, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	userID, _ := uuid.Parse(uid)
	keyID, _ := uuid.Parse(id)
	return true, r.UserSvc.DeleteAPIKey(ctx, userID, keyID)
}

// SetBudget is the resolver for the setBudget field.
func (r *mutationResolver) SetBudget(ctx context.Context, input model.BudgetInput) (*model.Budget, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	threshold := 80.0
	if input.AlertThreshold != nil {
		threshold = *input.AlertThreshold
	}
	b, err := r.BudgetService.SetBudget(ctx, id, input.MonthlyLimitUsd, threshold, derefStr(input.WebhookURL), derefStr(input.Email))
	if err != nil {
		return nil, err
	}
	return budgetToGQL(b), nil
}

// DeleteBudget is the resolver for the deleteBudget field.
func (r *mutationResolver) DeleteBudget(ctx context.Context) (bool, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	return true, r.BudgetService.DeleteBudget(ctx, id)
}

// ExportUsageCSV is the resolver for the exportUsageCsv field.
func (r *mutationResolver) ExportUsageCSV(ctx context.Context) (string, error) {
	return "", fmt.Errorf("not implemented: use REST endpoint")
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	t, err := r.TaskService.CreateTask(ctx, id, input.Type, input.Input, derefStr(input.WebhookURL))
	if err != nil {
		return nil, err
	}
	return asyncTaskToGQL(t), nil
}

// CancelTask is the resolver for the cancelTask field.
func (r *mutationResolver) CancelTask(ctx context.Context, id string) (*model.Task, error) {
	tid, _ := uuid.Parse(id)
	if err := r.TaskService.CancelTask(ctx, tid); err != nil {
		return nil, err
	}
	// Return a minimal task with cancelled status
	return &model.Task{ID: id, Status: "cancelled"}, nil
}

// CreateCheckoutSession is the resolver for the createCheckoutSession field.
func (r *mutationResolver) CreateCheckoutSession(ctx context.Context, planID string) (*model.CheckoutSession, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	userID, _ := uuid.Parse(uid)
	pid, _ := uuid.Parse(planID)
	url, err := r.Payment.CreateCheckoutSession(ctx, userID, pid)
	if err != nil {
		return nil, err
	}
	return &model.CheckoutSession{URL: url}, nil
}

// CreateRechargeSession is the resolver for the createRechargeSession field.
func (r *mutationResolver) CreateRechargeSession(ctx context.Context, amount float64) (*model.CheckoutSession, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	userID, _ := uuid.Parse(uid)
	url, err := r.Payment.CreateRechargeSession(ctx, userID, amount)
	if err != nil {
		return nil, err
	}
	return &model.CheckoutSession{URL: url}, nil
}

// RedeemCode is the resolver for the redeemCode field.
func (r *mutationResolver) RedeemCode(ctx context.Context, code string) (*model.RedeemResult, error) {
	uid, err := directives.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	userID, _ := uuid.Parse(uid)
	result, err := r.RedeemSvc.Redeem(userID, code)
	if err != nil {
		return nil, err
	}
	return &model.RedeemResult{
		Success:      true,
		Message:      result.Message,
		CreditAmount: &result.CreditAmount,
		PlanName:     &result.PlanName,
	}, nil
}

// ToggleUser is the resolver for the toggleUser field.
func (r *mutationResolver) ToggleUser(ctx context.Context, id string) (*model.User, error) {
	uid, _ := uuid.Parse(id)
	u, err := r.UserSvc.ToggleUser(ctx, uid)
	if err != nil {
		return nil, err
	}
	return userToGQL(u), nil
}

// UpdateUserRole is the resolver for the updateUserRole field.
func (r *mutationResolver) UpdateUserRole(ctx context.Context, id string, role string) (*model.User, error) {
	uid, _ := uuid.Parse(id)
	u, err := r.UserSvc.UpdateRole(ctx, uid, role)
	if err != nil {
		return nil, err
	}
	return userToGQL(u), nil
}

// UpdateUserQuota is the resolver for the updateUserQuota field.
func (r *mutationResolver) UpdateUserQuota(ctx context.Context, id string, input model.QuotaInput) (*model.User, error) {
	uid, _ := uuid.Parse(id)
	var tokenLimit *int64
	if input.MonthlyTokenLimit != nil {
		v := int64(*input.MonthlyTokenLimit)
		tokenLimit = &v
	}
	u, err := r.UserSvc.UpdateQuota(ctx, uid, tokenLimit, input.MonthlyBudgetUsd)
	if err != nil {
		return nil, err
	}
	return userToGQL(u), nil
}

// UpdateProvider is the resolver for the updateProvider field.
func (r *mutationResolver) UpdateProvider(ctx context.Context, id string, input model.ProviderInput) (*model.Provider, error) {
	pid, _ := uuid.Parse(id)
	p, err := r.Router.GetProviderByID(ctx, pid)
	if err != nil {
		return nil, fmt.Errorf("provider not found")
	}
	if input.Name != nil {
		p.Name = *input.Name
	}
	if input.BaseURL != nil {
		p.BaseURL = *input.BaseURL
	}
	if input.IsActive != nil {
		p.IsActive = *input.IsActive
	}
	if input.Priority != nil {
		p.Priority = *input.Priority
	}
	if input.Weight != nil {
		p.Weight = *input.Weight
	}
	if input.MaxRetries != nil {
		p.MaxRetries = *input.MaxRetries
	}
	if input.Timeout != nil {
		p.Timeout = *input.Timeout
	}
	if input.UseProxy != nil {
		p.UseProxy = *input.UseProxy
	}
	if input.DefaultProxyID != nil {
		if *input.DefaultProxyID == "" {
			p.DefaultProxyID = nil
		} else {
			pid, _ := uuid.Parse(*input.DefaultProxyID)
			p.DefaultProxyID = &pid
		}
	}
	if err := r.Router.UpdateProvider(ctx, p); err != nil {
		return nil, err
	}
	return providerToGQL(p), nil
}

// ToggleProvider is the resolver for the toggleProvider field.
func (r *mutationResolver) ToggleProvider(ctx context.Context, id string) (*model.Provider, error) {
	pid, _ := uuid.Parse(id)
	p, err := r.Router.GetProviderByID(ctx, pid)
	if err != nil {
		return nil, fmt.Errorf("provider not found")
	}
	p.IsActive = !p.IsActive
	if err := r.Router.UpdateProvider(ctx, p); err != nil {
		return nil, err
	}
	return providerToGQL(p), nil
}

// ToggleProviderProxy is the resolver for the toggleProviderProxy field.
func (r *mutationResolver) ToggleProviderProxy(ctx context.Context, id string) (*model.Provider, error) {
	pid, _ := uuid.Parse(id)
	p, err := r.Router.GetProviderByID(ctx, pid)
	if err != nil {
		return nil, fmt.Errorf("provider not found")
	}
	p.UseProxy = !p.UseProxy
	if err := r.Router.UpdateProvider(ctx, p); err != nil {
		return nil, err
	}
	return providerToGQL(p), nil
}

// CreateProviderAPIKey is the resolver for the createProviderApiKey field.
func (r *mutationResolver) CreateProviderAPIKey(ctx context.Context, providerID string, input model.ProviderAPIKeyInput) (*model.ProviderAPIKey, error) {
	pid, _ := uuid.Parse(providerID)
	keyPrefix := input.APIKey
	if len(keyPrefix) > 8 {
		keyPrefix = keyPrefix[:8] + "..."
	}
	encrypted, err := crypto.Encrypt(input.APIKey)
	if err != nil {
		return nil, fmt.Errorf("failed to encrypt API key")
	}
	prio := 1
	if input.Priority != nil {
		prio = *input.Priority
	}
	weight := 1.0
	if input.Weight != nil {
		weight = *input.Weight
	}
	rl := 0
	if input.RateLimit != nil {
		rl = *input.RateLimit
	}
	key := &models.ProviderAPIKey{
		ProviderID: pid, Alias: input.Alias, EncryptedAPIKey: encrypted,
		KeyPrefix: keyPrefix, IsActive: true, Priority: prio, Weight: weight, RateLimit: rl,
	}
	if err := r.Router.CreateProviderAPIKey(ctx, key); err != nil {
		return nil, err
	}
	return providerAPIKeyToGQL(key), nil
}

// UpdateProviderAPIKey is the resolver for the updateProviderApiKey field.
func (r *mutationResolver) UpdateProviderAPIKey(ctx context.Context, providerID string, keyID string, input model.UpdateProviderAPIKeyInput) (*model.ProviderAPIKey, error) {
	kid, _ := uuid.Parse(keyID)
	key, err := r.Router.GetProviderAPIKeyByID(ctx, kid)
	if err != nil {
		return nil, fmt.Errorf("API key not found")
	}
	if input.Priority != nil {
		key.Priority = *input.Priority
	}
	if input.Weight != nil {
		key.Weight = *input.Weight
	}
	if input.RateLimit != nil {
		key.RateLimit = *input.RateLimit
	}
	if err := r.Router.UpdateProviderAPIKey(ctx, key); err != nil {
		return nil, err
	}
	return providerAPIKeyToGQL(key), nil
}

// ToggleProviderAPIKey is the resolver for the toggleProviderApiKey field.
func (r *mutationResolver) ToggleProviderAPIKey(ctx context.Context, providerID string, keyID string) (*model.ProviderAPIKey, error) {
	kid, _ := uuid.Parse(keyID)
	key, err := r.Router.ToggleProviderAPIKey(ctx, kid)
	if err != nil {
		return nil, err
	}
	return providerAPIKeyToGQL(key), nil
}

// DeleteProviderAPIKey is the resolver for the deleteProviderApiKey field.
func (r *mutationResolver) DeleteProviderAPIKey(ctx context.Context, providerID string, keyID string) (bool, error) {
	kid, _ := uuid.Parse(keyID)
	return true, r.Router.DeleteProviderAPIKey(ctx, kid)
}

// CreateModel is the resolver for the createModel field.
func (r *mutationResolver) CreateModel(ctx context.Context, providerID string, input model.ModelInput) (*model.Model, error) {
	pid, err := uuid.Parse(providerID)
	if err != nil {
		return nil, fmt.Errorf("invalid provider id")
	}
	m := models.Model{
		ProviderID:  pid,
		Name:        input.Name,
		DisplayName: derefStrDefault(input.DisplayName, input.Name),
		IsActive:    derefBool(input.IsActive, true),
		MaxTokens:   valInt(input.MaxTokens, 4096),
	}
	if input.InputPricePer1k != nil {
		m.InputPricePer1K = *input.InputPricePer1k
	}
	if input.OutputPricePer1k != nil {
		m.OutputPricePer1K = *input.OutputPricePer1k
	}
	if input.PricePerSecond != nil {
		m.PricePerSecond = *input.PricePerSecond
	}
	if input.PricePerImage != nil {
		m.PricePerImage = *input.PricePerImage
	}
	if input.PricePerMinute != nil {
		m.PricePerMinute = *input.PricePerMinute
	}
	if err := r.DB.Create(&m).Error; err != nil {
		return nil, fmt.Errorf("failed to create model: %w", err)
	}
	return modelToGQL(&m), nil
}

// UpdateModel is the resolver for the updateModel field.
func (r *mutationResolver) UpdateModel(ctx context.Context, id string, input model.ModelInput) (*model.Model, error) {
	mid, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid model id")
	}
	var m models.Model
	if err := r.DB.First(&m, "id = ?", mid).Error; err != nil {
		return nil, fmt.Errorf("model not found")
	}
	m.Name = input.Name
	if input.DisplayName != nil {
		m.DisplayName = *input.DisplayName
	}
	if input.MaxTokens != nil {
		m.MaxTokens = *input.MaxTokens
	}
	if input.IsActive != nil {
		m.IsActive = *input.IsActive
	}
	if input.InputPricePer1k != nil {
		m.InputPricePer1K = *input.InputPricePer1k
	}
	if input.OutputPricePer1k != nil {
		m.OutputPricePer1K = *input.OutputPricePer1k
	}
	if input.PricePerSecond != nil {
		m.PricePerSecond = *input.PricePerSecond
	}
	if input.PricePerImage != nil {
		m.PricePerImage = *input.PricePerImage
	}
	if input.PricePerMinute != nil {
		m.PricePerMinute = *input.PricePerMinute
	}
	if err := r.DB.Save(&m).Error; err != nil {
		return nil, fmt.Errorf("failed to update model: %w", err)
	}
	return modelToGQL(&m), nil
}

// DeleteModel is the resolver for the deleteModel field.
func (r *mutationResolver) DeleteModel(ctx context.Context, id string) (bool, error) {
	mid, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid model id")
	}
	if err := r.DB.Delete(&models.Model{}, "id = ?", mid).Error; err != nil {
		return false, fmt.Errorf("failed to delete model: %w", err)
	}
	return true, nil
}

// ToggleModel is the resolver for the toggleModel field.
func (r *mutationResolver) ToggleModel(ctx context.Context, id string) (*model.Model, error) {
	mid, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid model id")
	}
	var m models.Model
	if err := r.DB.First(&m, "id = ?", mid).Error; err != nil {
		return nil, fmt.Errorf("model not found")
	}
	m.IsActive = !m.IsActive
	if err := r.DB.Save(&m).Error; err != nil {
		return nil, fmt.Errorf("failed to toggle model: %w", err)
	}
	return modelToGQL(&m), nil
}

// SyncProviderModels is the resolver for the syncProviderModels field.
func (r *mutationResolver) SyncProviderModels(ctx context.Context, providerID string) ([]*model.Model, error) {
	pid, err := uuid.Parse(providerID)
	if err != nil {
		return nil, fmt.Errorf("invalid provider id")
	}
	// Get provider from DB
	var prov models.Provider
	if err := r.DB.Preload("Models").First(&prov, "id = ?", pid).Error; err != nil {
		return nil, fmt.Errorf("provider not found")
	}

	// Call upstream /v1/models to discover available models
	client := &http.Client{Timeout: 15 * time.Second}
	reqURL := strings.TrimRight(prov.BaseURL, "/") + "/v1/models"
	req, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to build request: %w", err)
	}

	// Try to get the first active API key for auth
	var apiKey models.ProviderAPIKey
	if err := r.DB.Where("provider_id = ? AND is_active = ?", pid, true).Order("priority ASC").First(&apiKey).Error; err == nil {
		if decrypted, err := crypto.Decrypt(apiKey.EncryptedAPIKey); err == nil {
			req.Header.Set("Authorization", "Bearer "+decrypted)
		}
	}

	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to reach provider at %s: %w", reqURL, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("provider returned status %d", resp.StatusCode)
	}

	var result struct {
		Data []struct {
			ID string `json:"id"`
		} `json:"data"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to parse model list: %w", err)
	}

	// Build existing model map
	existing := make(map[string]bool)
	for _, m := range prov.Models {
		existing[m.Name] = true
	}

	// Upsert discovered models
	for _, upstream := range result.Data {
		if existing[upstream.ID] {
			continue
		}
		m := models.Model{
			ProviderID:  pid,
			Name:        upstream.ID,
			DisplayName: upstream.ID,
			IsActive:    true,
			MaxTokens:   4096,
		}
		r.DB.Create(&m)
	}

	// Return full model list
	var allModels []models.Model
	r.DB.Where("provider_id = ?", pid).Order("name ASC").Find(&allModels)
	out := make([]*model.Model, len(allModels))
	for i := range allModels {
		out[i] = modelToGQL(&allModels[i])
	}
	return out, nil
}

// CreateProxy is the resolver for the createProxy field.
func (r *mutationResolver) CreateProxy(ctx context.Context, input model.ProxyInput) (*model.Proxy, error) {
	var upstreamID *uuid.UUID
	if input.UpstreamProxyID != nil && *input.UpstreamProxyID != "" {
		id, _ := uuid.Parse(*input.UpstreamProxyID)
		upstreamID = &id
	}
	p, err := r.Proxy.Create(ctx, input.URL, input.Type, derefStr(input.Region), derefStr(input.Username), derefStr(input.Password), upstreamID)
	if err != nil {
		return nil, err
	}
	return proxyToGQL(p), nil
}

// BatchCreateProxies is the resolver for the batchCreateProxies field.
func (r *mutationResolver) BatchCreateProxies(ctx context.Context, input model.BatchProxyInput) (*model.BatchProxyResult, error) {
	result := &model.BatchProxyResult{Proxies: []*model.Proxy{}}
	for _, item := range input.Proxies {
		typ := "http"
		if item.Type != nil {
			typ = *item.Type
		}
		p, err := r.Proxy.Create(ctx, item.URL, typ, derefStr(item.Region), "", "", nil)
		if err != nil {
			result.Failed++
			result.Errors = append(result.Errors, item.URL+": "+err.Error())
		} else {
			result.Success++
			result.Proxies = append(result.Proxies, proxyToGQL(p))
		}
	}
	return result, nil
}

// UpdateProxy is the resolver for the updateProxy field.
func (r *mutationResolver) UpdateProxy(ctx context.Context, id string, input model.ProxyInput) (*model.Proxy, error) {
	pid, _ := uuid.Parse(id)
	var upstreamID *uuid.UUID
	if input.UpstreamProxyID != nil && *input.UpstreamProxyID != "" {
		uid, _ := uuid.Parse(*input.UpstreamProxyID)
		upstreamID = &uid
	}
	p, err := r.Proxy.Update(ctx, pid, input.URL, input.Type, derefStr(input.Region), true, derefStr(input.Username), derefStr(input.Password), upstreamID)
	if err != nil {
		return nil, err
	}
	return proxyToGQL(p), nil
}

// DeleteProxy is the resolver for the deleteProxy field.
func (r *mutationResolver) DeleteProxy(ctx context.Context, id string) (bool, error) {
	pid, _ := uuid.Parse(id)
	return true, r.Proxy.Delete(ctx, pid)
}

// ToggleProxyStatus is the resolver for the toggleProxyStatus field.
func (r *mutationResolver) ToggleProxyStatus(ctx context.Context, id string) (*model.Proxy, error) {
	pid, _ := uuid.Parse(id)
	p, err := r.Proxy.Toggle(ctx, pid)
	if err != nil {
		return nil, err
	}
	return proxyToGQL(p), nil
}

// TestProxy is the resolver for the testProxy field.
func (r *mutationResolver) TestProxy(ctx context.Context, id string) (*model.ProxyTestResult, error) {
	pid, _ := uuid.Parse(id)
	healthy, latency, testErr := r.Proxy.CheckHealth(ctx, pid)
	p, err := r.Proxy.GetByID(ctx, pid)
	if err != nil {
		return nil, err
	}
	result := &model.ProxyTestResult{ID: p.ID.String(), URL: p.URL, IsHealthy: healthy, LatencyMs: float64(latency.Milliseconds())}
	if testErr != nil {
		e := testErr.Error()
		result.Error = &e
	}
	return result, nil
}

// TestAllProxies is the resolver for the testAllProxies field.
func (r *mutationResolver) TestAllProxies(ctx context.Context) ([]*model.ProxyTestResult, error) {
	proxies, err := r.Proxy.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.ProxyTestResult, 0, len(proxies))
	for _, p := range proxies {
		healthy, latency, testErr := r.Proxy.CheckHealth(ctx, p.ID)
		result := &model.ProxyTestResult{ID: p.ID.String(), URL: p.URL, IsHealthy: healthy, LatencyMs: float64(latency.Milliseconds())}
		if testErr != nil {
			e := testErr.Error()
			result.Error = &e
		}
		out = append(out, result)
	}
	return out, nil
}

// CheckAPIKeyHealth is the resolver for the checkApiKeyHealth field.
func (r *mutationResolver) CheckAPIKeyHealth(ctx context.Context, id string) (*model.APIKeyHealth, error) {
	kid, _ := uuid.Parse(id)
	s, err := r.Health.CheckSingleAPIKey(ctx, kid)
	if err != nil {
		return nil, err
	}
	var lc *time.Time
	if !s.LastCheck.IsZero() {
		lc = &s.LastCheck
	}
	return &model.APIKeyHealth{
		ID: s.ID.String(), ProviderID: s.ProviderID.String(),
		ProviderName: s.ProviderName, KeyPrefix: s.KeyPrefix,
		IsActive: s.IsActive, IsHealthy: s.IsHealthy,
		LastCheck: lc, ResponseTime: float64(s.ResponseTime), SuccessRate: s.SuccessRate,
	}, nil
}

// CheckProxyHealth is the resolver for the checkProxyHealth field.
func (r *mutationResolver) CheckProxyHealth(ctx context.Context, id string) (*model.ProxyHealth, error) {
	pid, _ := uuid.Parse(id)
	s, err := r.Health.CheckSingleProxy(ctx, pid)
	if err != nil {
		return nil, err
	}
	var lc *time.Time
	if !s.LastCheck.IsZero() {
		lc = &s.LastCheck
	}
	return &model.ProxyHealth{
		ID: s.ID.String(), URL: s.URL, Type: s.Type, Region: s.Region,
		IsActive: s.IsActive, IsHealthy: s.IsHealthy,
		ResponseTime: float64(s.ResponseTime), LastCheck: lc, SuccessRate: s.SuccessRate,
	}, nil
}

// CheckProviderHealth is the resolver for the checkProviderHealth field.
func (r *mutationResolver) CheckProviderHealth(ctx context.Context, id string) (*model.ProviderHealth, error) {
	pid, _ := uuid.Parse(id)
	s, err := r.Health.CheckSingleProvider(ctx, pid)
	if err != nil {
		return nil, err
	}
	var lc *time.Time
	if !s.LastCheck.IsZero() {
		lc = &s.LastCheck
	}
	var em *string
	if s.ErrorMessage != "" {
		em = &s.ErrorMessage
	}
	return &model.ProviderHealth{
		ID: s.ID.String(), Name: s.Name, BaseURL: s.BaseURL,
		IsActive: s.IsActive, IsHealthy: s.IsHealthy, UseProxy: s.UseProxy,
		ResponseTime: float64(s.ResponseTime), LastCheck: lc,
		SuccessRate: s.SuccessRate, ErrorMessage: em,
	}, nil
}

// CheckAllProviderHealth is the resolver for the checkAllProviderHealth field.
func (r *mutationResolver) CheckAllProviderHealth(ctx context.Context) ([]*model.ProviderHealth, error) {
	if err := r.Health.CheckAllProviders(ctx); err != nil {
		return nil, err
	}
	qr := &queryResolver{r.Resolver}
	return qr.HealthProviders(ctx)
}

// AcknowledgeAlert is the resolver for the acknowledgeAlert field.
func (r *mutationResolver) AcknowledgeAlert(ctx context.Context, id string) (*model.Alert, error) {
	aid, _ := uuid.Parse(id)
	if err := r.Health.AcknowledgeAlert(ctx, aid); err != nil {
		return nil, err
	}
	var alert models.Alert
	if err := r.DB.First(&alert, "id = ?", aid).Error; err != nil {
		return nil, err
	}
	return alertToGQL(&alert), nil
}

// ResolveAlert is the resolver for the resolveAlert field.
func (r *mutationResolver) ResolveAlert(ctx context.Context, id string) (*model.Alert, error) {
	aid, _ := uuid.Parse(id)
	if err := r.Health.ResolveAlert(ctx, aid); err != nil {
		return nil, err
	}
	var alert models.Alert
	if err := r.DB.First(&alert, "id = ?", aid).Error; err != nil {
		return nil, err
	}
	return alertToGQL(&alert), nil
}

// UpdateAlertConfig is the resolver for the updateAlertConfig field.
func (r *mutationResolver) UpdateAlertConfig(ctx context.Context, input model.AlertConfigInput) (*model.AlertConfig, error) {
	targetID, _ := uuid.Parse(input.TargetID)
	if input.WebhookURL != nil {
		if err := sanitize.ValidateWebhookURL(*input.WebhookURL, false); err != nil {
			return nil, fmt.Errorf("invalid webhook URL: %w", err)
		}
	}
	config := &models.AlertConfig{
		TargetType: input.TargetType, TargetID: targetID,
		IsEnabled: input.IsEnabled, FailureThreshold: input.FailureThreshold,
	}
	if input.WebhookURL != nil {
		config.WebhookURL = *input.WebhookURL
	}
	if input.Email != nil {
		config.Email = *input.Email
	}
	if err := r.Health.UpdateAlertConfig(ctx, config); err != nil {
		return nil, err
	}
	return &model.AlertConfig{
		TargetType: config.TargetType, TargetID: config.TargetID.String(),
		IsEnabled: config.IsEnabled, FailureThreshold: config.FailureThreshold,
		WebhookURL: input.WebhookURL, Email: input.Email,
	}, nil
}

// CreateMcpServer is the resolver for the createMcpServer field.
func (r *mutationResolver) CreateMcpServer(ctx context.Context, input model.McpServerInput) (*model.McpServer, error) {
	server := &models.MCPServer{Name: input.Name, Type: input.Type, IsActive: true}
	if input.Command != nil {
		server.Command = *input.Command
	}
	if input.URL != nil {
		server.URL = *input.URL
	}
	if input.IsActive != nil {
		server.IsActive = *input.IsActive
	}
	if input.Args != nil {
		b, _ := json.Marshal(input.Args)
		server.Args = b
	}
	if input.Env != nil {
		envMap := make(map[string]string)
		for _, e := range input.Env {
			envMap[e.Key] = e.Value
		}
		b, _ := json.Marshal(envMap)
		server.Env = b
	}
	if err := r.MCP.CreateServer(ctx, server); err != nil {
		return nil, err
	}
	return mcpServerToGQL(server), nil
}

// UpdateMcpServer is the resolver for the updateMcpServer field.
func (r *mutationResolver) UpdateMcpServer(ctx context.Context, id string, input model.McpServerInput) (*model.McpServer, error) {
	sid, _ := uuid.Parse(id)
	server, err := r.MCP.GetServerByID(ctx, sid)
	if err != nil {
		return nil, fmt.Errorf("server not found")
	}
	server.Name = input.Name
	server.Type = input.Type
	if input.Command != nil {
		server.Command = *input.Command
	}
	if input.URL != nil {
		server.URL = *input.URL
	}
	if input.IsActive != nil {
		server.IsActive = *input.IsActive
	}
	if input.Args != nil {
		b, _ := json.Marshal(input.Args)
		server.Args = b
	}
	if err := r.MCP.UpdateServer(ctx, server); err != nil {
		return nil, err
	}
	return mcpServerToGQL(server), nil
}

// DeleteMcpServer is the resolver for the deleteMcpServer field.
func (r *mutationResolver) DeleteMcpServer(ctx context.Context, id string) (bool, error) {
	sid, _ := uuid.Parse(id)
	return true, r.MCP.DeleteServer(ctx, sid)
}

// RefreshMcpTools is the resolver for the refreshMcpTools field.
func (r *mutationResolver) RefreshMcpTools(ctx context.Context, id string) (*model.McpServer, error) {
	sid, _ := uuid.Parse(id)
	if err := r.MCP.RefreshTools(ctx, sid); err != nil {
		return nil, err
	}
	server, err := r.MCP.GetServerByID(ctx, sid)
	if err != nil {
		return nil, err
	}
	return mcpServerToGQL(server), nil
}

// CreatePlan is the resolver for the createPlan field.
func (r *mutationResolver) CreatePlan(ctx context.Context, input model.PlanInput) (*model.Plan, error) {
	plan := &models.Plan{
		Name: input.Name, PriceMonth: input.PriceMonth,
		TokenLimit: int64(input.TokenLimit), RateLimit: input.RateLimit, IsActive: true,
	}
	if input.Description != nil {
		plan.Description = *input.Description
	}
	if input.SupportLevel != nil {
		plan.SupportLevel = *input.SupportLevel
	}
	if input.IsActive != nil {
		plan.IsActive = *input.IsActive
	}
	if input.Features != nil {
		plan.Features = *input.Features
	}
	if err := r.DB.WithContext(ctx).Create(plan).Error; err != nil {
		return nil, err
	}
	var features *string
	if plan.Features != "" {
		features = &plan.Features
	}
	return &model.Plan{
		ID: plan.ID.String(), Name: plan.Name, PriceMonth: plan.PriceMonth,
		TokenLimit: int(plan.TokenLimit), RateLimit: plan.RateLimit,
		Features: features, IsActive: plan.IsActive,
	}, nil
}

// UpdatePlan is the resolver for the updatePlan field.
func (r *mutationResolver) UpdatePlan(ctx context.Context, id string, input model.PlanInput) (*model.Plan, error) {
	pid, _ := uuid.Parse(id)
	var plan models.Plan
	if err := r.DB.WithContext(ctx).First(&plan, "id = ?", pid).Error; err != nil {
		return nil, fmt.Errorf("plan not found")
	}
	plan.Name = input.Name
	plan.PriceMonth = input.PriceMonth
	plan.TokenLimit = int64(input.TokenLimit)
	plan.RateLimit = input.RateLimit
	if input.Description != nil {
		plan.Description = *input.Description
	}
	if input.SupportLevel != nil {
		plan.SupportLevel = *input.SupportLevel
	}
	if input.IsActive != nil {
		plan.IsActive = *input.IsActive
	}
	if input.Features != nil {
		plan.Features = *input.Features
	}
	if err := r.DB.WithContext(ctx).Save(&plan).Error; err != nil {
		return nil, err
	}
	var features *string
	if plan.Features != "" {
		features = &plan.Features
	}
	return &model.Plan{
		ID: plan.ID.String(), Name: plan.Name, PriceMonth: plan.PriceMonth,
		TokenLimit: int(plan.TokenLimit), RateLimit: plan.RateLimit,
		Features: features, IsActive: plan.IsActive,
	}, nil
}

// UpdateSystemSettings is the resolver for the updateSystemSettings field.
func (r *mutationResolver) UpdateSystemSettings(ctx context.Context, input model.SystemSettingsInput) (*model.SystemSettings, error) {
	if err := r.SystemConfig.UpdateSettings(ctx, input.Category, input.Data); err != nil {
		return nil, err
	}
	// Return full settings after update
	all, err := r.SystemConfig.GetAllSettingsDecrypted(ctx)
	if err != nil {
		return nil, err
	}
	return buildSystemSettings(r.Config.Registration.Mode, all), nil
}

// SendTestEmail is the resolver for the sendTestEmail field.
func (r *mutationResolver) SendTestEmail(ctx context.Context, to string) (bool, error) {
	// Load email settings from DB
	all, err := r.SystemConfig.GetAllSettingsDecrypted(ctx)
	if err != nil {
		return false, fmt.Errorf("failed to load settings: %w", err)
	}
	emailJSON, ok := all["email"]
	if !ok {
		return false, fmt.Errorf("email settings not configured")
	}

	var emailCfg struct {
		Enabled  bool   `json:"enabled"`
		Host     string `json:"host"`
		Port     int    `json:"port"`
		Username string `json:"username"`
		Password string `json:"password"`
		From     string `json:"from"`
		FromName string `json:"fromName"`
	}
	if err := json.Unmarshal([]byte(emailJSON), &emailCfg); err != nil {
		return false, fmt.Errorf("invalid email settings: %w", err)
	}
	if !emailCfg.Enabled || emailCfg.Host == "" {
		return false, fmt.Errorf("email is not enabled or SMTP host not set")
	}

	// Send test email via SMTP
	addr := fmt.Sprintf("%s:%d", emailCfg.Host, emailCfg.Port)
	from := emailCfg.From
	if from == "" {
		from = emailCfg.Username
	}
	subject := "Test Email from LLM Router Platform"
	body := "This is a test email to verify your SMTP configuration is working correctly."
	msg := fmt.Sprintf("From: %s <%s>\r\nTo: %s\r\nSubject: %s\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n%s",
		emailCfg.FromName, from, to, subject, body)

	var auth smtp.Auth
	if emailCfg.Username != "" {
		auth = smtp.PlainAuth("", emailCfg.Username, emailCfg.Password, emailCfg.Host)
	}
	if err := smtp.SendMail(addr, auth, from, []string{to}, []byte(msg)); err != nil {
		return false, fmt.Errorf("failed to send test email: %w", err)
	}
	return true, nil
}

// TriggerBackup is the resolver for the triggerBackup field.
func (r *mutationResolver) TriggerBackup(ctx context.Context) (bool, error) {
	// Load backup settings to validate configuration
	all, err := r.SystemConfig.GetAllSettingsDecrypted(ctx)
	if err != nil {
		return false, fmt.Errorf("failed to load settings: %w", err)
	}
	backupJSON, ok := all["backup"]
	if !ok {
		return false, fmt.Errorf("backup settings not configured")
	}

	var backupCfg struct {
		Enabled    bool   `json:"enabled"`
		S3Endpoint string `json:"s3Endpoint"`
		S3Bucket   string `json:"s3Bucket"`
	}
	if err := json.Unmarshal([]byte(backupJSON), &backupCfg); err != nil {
		return false, fmt.Errorf("invalid backup settings: %w", err)
	}
	if !backupCfg.Enabled || backupCfg.S3Bucket == "" {
		return false, fmt.Errorf("backup is not enabled or S3 bucket not set")
	}

	// TODO: Implement actual S3 database dump + upload
	// For now, log the trigger and return success
	r.Logger.Info("manual backup triggered",
		zap.String("bucket", backupCfg.S3Bucket),
		zap.String("endpoint", backupCfg.S3Endpoint))

	return true, nil
}

// CreateInviteCode is the resolver for the createInviteCode field.
func (r *mutationResolver) CreateInviteCode(ctx context.Context, input model.InviteCodeInput) (*model.InviteCode, error) {
	maxUses := 1
	if input.MaxUses != nil {
		maxUses = *input.MaxUses
	}
	buf := make([]byte, 16)
	rand.Read(buf)
	code := "inv_" + hex.EncodeToString(buf)
	adminID, _ := directives.UserIDFromContext(ctx)
	aid, _ := uuid.Parse(adminID)
	ic := models.InviteCode{Code: code, CreatedBy: aid, MaxUses: maxUses, ExpiresAt: input.ExpiresAt, IsActive: true}
	if err := r.DB.Create(&ic).Error; err != nil {
		return nil, err
	}
	return &model.InviteCode{
		ID: ic.ID.String(), Code: ic.Code, CreatedBy: ic.CreatedBy.String(),
		MaxUses: ic.MaxUses, UseCount: ic.UseCount, ExpiresAt: ic.ExpiresAt,
		IsActive: ic.IsActive, CreatedAt: ic.CreatedAt,
	}, nil
}

// ExportSystemUsageCSV is the resolver for the exportSystemUsageCsv field.
func (r *mutationResolver) ExportSystemUsageCSV(ctx context.Context) (string, error) {
	return "", fmt.Errorf("not implemented: use REST endpoint")
}

// GenerateRedeemCodes is the resolver for the generateRedeemCodes field.
func (r *mutationResolver) GenerateRedeemCodes(ctx context.Context, input model.GenerateRedeemCodesInput) (*model.GenerateRedeemCodesResult, error) {
	var planID *uuid.UUID
	if input.PlanID != nil {
		p, _ := uuid.Parse(*input.PlanID)
		planID = &p
	}
	var expiresAt *time.Time
	if input.ExpiresAt != nil {
		t := *input.ExpiresAt
		expiresAt = &t
	}
	creditAmount := float64(0)
	if input.CreditAmount != nil {
		creditAmount = *input.CreditAmount
	}
	planDays := 30
	if input.PlanDays != nil {
		planDays = *input.PlanDays
	}
	note := ""
	if input.Note != nil {
		note = *input.Note
	}
	codes, err := r.RedeemSvc.GenerateCodes(input.Type, creditAmount, planID, planDays, input.Count, expiresAt, note)
	if err != nil {
		return nil, err
	}
	return &model.GenerateRedeemCodesResult{Codes: codes, Count: len(codes)}, nil
}

// RevokeRedeemCode is the resolver for the revokeRedeemCode field.
func (r *mutationResolver) RevokeRedeemCode(ctx context.Context, id string) (bool, error) {
	uid, _ := uuid.Parse(id)
	return true, r.RedeemSvc.RevokeCode(uid)
}

// CreateAnnouncement is the resolver for the createAnnouncement field.
func (r *mutationResolver) CreateAnnouncement(ctx context.Context, input model.AnnouncementInput) (*model.Announcement, error) {
	a := &models.Announcement{Title: input.Title, Content: input.Content}
	if input.Type != nil {
		a.Type = *input.Type
	} else {
		a.Type = "info"
	}
	if input.Priority != nil {
		a.Priority = *input.Priority
	}
	if input.IsActive != nil {
		a.IsActive = *input.IsActive
	}
	a.StartsAt = input.StartsAt
	a.EndsAt = input.EndsAt
	if err := r.AnnouncementSvc.Create(ctx, a); err != nil {
		return nil, err
	}
	return announcementToGQL(a), nil
}

// UpdateAnnouncement is the resolver for the updateAnnouncement field.
func (r *mutationResolver) UpdateAnnouncement(ctx context.Context, id string, input model.AnnouncementInput) (*model.Announcement, error) {
	aid, _ := uuid.Parse(id)
	a, err := r.AnnouncementSvc.GetByID(ctx, aid)
	if err != nil {
		return nil, fmt.Errorf("announcement not found")
	}
	a.Title = input.Title
	a.Content = input.Content
	if input.Type != nil {
		a.Type = *input.Type
	}
	if input.Priority != nil {
		a.Priority = *input.Priority
	}
	if input.IsActive != nil {
		a.IsActive = *input.IsActive
	}
	a.StartsAt = input.StartsAt
	a.EndsAt = input.EndsAt
	if err := r.AnnouncementSvc.Update(ctx, a); err != nil {
		return nil, err
	}
	return announcementToGQL(a), nil
}

// DeleteAnnouncement is the resolver for the deleteAnnouncement field.
func (r *mutationResolver) DeleteAnnouncement(ctx context.Context, id string) (bool, error) {
	aid, _ := uuid.Parse(id)
	return true, r.AnnouncementSvc.Delete(ctx, aid)
}

// CreateCoupon is the resolver for the createCoupon field.
func (r *mutationResolver) CreateCoupon(ctx context.Context, input model.CouponInput) (*model.Coupon, error) {
	c := &models.Coupon{
		Code: input.Code, Name: input.Name, Type: input.Type,
		DiscountValue: input.DiscountValue, IsActive: true,
	}
	if input.MinAmount != nil {
		c.MinAmount = *input.MinAmount
	}
	if input.MaxUses != nil {
		c.MaxUses = *input.MaxUses
	}
	if input.MaxUsesPerUser != nil {
		c.MaxUsesPerUser = *input.MaxUsesPerUser
	} else {
		c.MaxUsesPerUser = 1
	}
	if input.IsActive != nil {
		c.IsActive = *input.IsActive
	}
	c.ExpiresAt = input.ExpiresAt
	if err := r.CouponSvc.Create(ctx, c); err != nil {
		return nil, err
	}
	return couponToGQL(c), nil
}

// UpdateCoupon is the resolver for the updateCoupon field.
func (r *mutationResolver) UpdateCoupon(ctx context.Context, id string, input model.CouponInput) (*model.Coupon, error) {
	cid, _ := uuid.Parse(id)
	c, err := r.CouponSvc.GetByID(ctx, cid)
	if err != nil {
		return nil, fmt.Errorf("coupon not found")
	}
	c.Code = input.Code
	c.Name = input.Name
	c.Type = input.Type
	c.DiscountValue = input.DiscountValue
	if input.MinAmount != nil {
		c.MinAmount = *input.MinAmount
	}
	if input.MaxUses != nil {
		c.MaxUses = *input.MaxUses
	}
	if input.MaxUsesPerUser != nil {
		c.MaxUsesPerUser = *input.MaxUsesPerUser
	}
	if input.IsActive != nil {
		c.IsActive = *input.IsActive
	}
	c.ExpiresAt = input.ExpiresAt
	if err := r.CouponSvc.Update(ctx, c); err != nil {
		return nil, err
	}
	return couponToGQL(c), nil
}

// DeleteCoupon is the resolver for the deleteCoupon field.
func (r *mutationResolver) DeleteCoupon(ctx context.Context, id string) (bool, error) {
	cid, _ := uuid.Parse(id)
	return true, r.CouponSvc.Delete(ctx, cid)
}

// CreateDocument is the resolver for the createDocument field.
func (r *mutationResolver) CreateDocument(ctx context.Context, input model.DocumentInput) (*model.Document, error) {
	d := &models.Document{Title: input.Title, Slug: input.Slug, Content: input.Content}
	if input.Category != nil {
		d.Category = *input.Category
	} else {
		d.Category = "general"
	}
	if input.SortOrder != nil {
		d.SortOrder = *input.SortOrder
	}
	if input.IsPublished != nil {
		d.IsPublished = *input.IsPublished
	}
	if err := r.DocumentSvc.Create(ctx, d); err != nil {
		return nil, err
	}
	return documentToGQL(d), nil
}

// UpdateDocument is the resolver for the updateDocument field.
func (r *mutationResolver) UpdateDocument(ctx context.Context, id string, input model.DocumentInput) (*model.Document, error) {
	did, _ := uuid.Parse(id)
	d, err := r.DocumentSvc.GetByID(ctx, did)
	if err != nil {
		return nil, fmt.Errorf("document not found")
	}
	d.Title = input.Title
	d.Slug = input.Slug
	d.Content = input.Content
	if input.Category != nil {
		d.Category = *input.Category
	}
	if input.SortOrder != nil {
		d.SortOrder = *input.SortOrder
	}
	if input.IsPublished != nil {
		d.IsPublished = *input.IsPublished
	}
	if err := r.DocumentSvc.Update(ctx, d); err != nil {
		return nil, err
	}
	return documentToGQL(d), nil
}

// DeleteDocument is the resolver for the deleteDocument field.
func (r *mutationResolver) DeleteDocument(ctx context.Context, id string) (bool, error) {
	did, _ := uuid.Parse(id)
	return true, r.DocumentSvc.Delete(ctx, did)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	uid, err := directives.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	id, _ := uuid.Parse(uid)
	u, err := r.UserSvc.GetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("user not found")
	}
	return userToGQL(u), nil
}

// MyAPIKeys is the resolver for the myApiKeys field.
func (r *queryResolver) MyAPIKeys(ctx context.Context) ([]*model.APIKey, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	keys, err := r.UserSvc.GetAPIKeys(ctx, id)
	if err != nil {
		return nil, err
	}
	out := make([]*model.APIKey, len(keys))
	for i := range keys {
		out[i] = apiKeyToGQL(&keys[i])
	}
	return out, nil
}

// MyUsageSummary is the resolver for the myUsageSummary field.
func (r *queryResolver) MyUsageSummary(ctx context.Context) (*model.UsageSummary, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	s, err := r.Billing.GetUsageSummary(ctx, id, monthStart(), time.Now())
	if err != nil {
		return &model.UsageSummary{}, nil
	}
	return &model.UsageSummary{
		TotalRequests: int(s.TotalRequests), SuccessRate: s.SuccessRate,
		TotalTokens: int(s.TotalTokens), TotalCost: s.TotalCost,
	}, nil
}

// MyDailyUsage is the resolver for the myDailyUsage field.
func (r *queryResolver) MyDailyUsage(ctx context.Context, days *int) ([]*model.DailyStats, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	d := valInt(days, 30)
	usage, err := r.Billing.GetDailyUsage(ctx, id, d)
	if err != nil {
		return nil, err
	}
	out := make([]*model.DailyStats, len(usage))
	for i, u := range usage {
		out[i] = &model.DailyStats{Date: u.Date, Requests: int(u.Requests), TotalTokens: int(u.Tokens), TotalCost: u.Cost}
	}
	return out, nil
}

// MyUsageByProvider is the resolver for the myUsageByProvider field.
func (r *queryResolver) MyUsageByProvider(ctx context.Context) ([]*model.ProviderUsage, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	usage, err := r.Billing.GetUsageByProvider(ctx, id, monthStart(), time.Now())
	if err != nil {
		return nil, err
	}
	out := make([]*model.ProviderUsage, len(usage))
	for i, u := range usage {
		out[i] = &model.ProviderUsage{ProviderName: u.ProviderName, Requests: int(u.Requests), Tokens: int(u.Tokens), Cost: u.Cost}
	}
	return out, nil
}

// MyRecentUsage is the resolver for the myRecentUsage field.
func (r *queryResolver) MyRecentUsage(ctx context.Context, page *int, pageSize *int) (*model.UsageConnection, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	ps := valInt(pageSize, 20)
	logs, err := r.Billing.GetRecentUsage(ctx, id, ps)
	if err != nil {
		return &model.UsageConnection{Data: []*model.UsageRecord{}, Total: 0}, nil
	}
	out := make([]*model.UsageRecord, len(logs))
	for i, l := range logs {
		out[i] = &model.UsageRecord{
			ID: l.ID.String(), ModelName: l.ModelName,
			InputTokens: l.RequestTokens, OutputTokens: l.ResponseTokens,
			Cost: l.Cost, LatencyMs: int(l.Latency),
			IsSuccess: l.StatusCode >= 200 && l.StatusCode < 400,
			CreatedAt: l.CreatedAt,
		}
	}
	return &model.UsageConnection{Data: out, Total: len(out)}, nil
}

// MyBudget is the resolver for the myBudget field.
func (r *queryResolver) MyBudget(ctx context.Context) (*model.Budget, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	b := r.BudgetService.GetBudget(ctx, id)
	if b == nil {
		return nil, nil
	}
	return budgetToGQL(b), nil
}

// MyBudgetStatus is the resolver for the myBudgetStatus field.
func (r *queryResolver) MyBudgetStatus(ctx context.Context) (*model.BudgetStatus, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	s, err := r.BudgetService.CheckBudget(ctx, id)
	if err != nil {
		return nil, err
	}
	b := r.BudgetService.GetBudget(ctx, id)
	var budget *model.Budget
	if b != nil {
		budget = budgetToGQL(b)
	}
	return &model.BudgetStatus{
		Budget: budget, CurrentSpend: s.CurrentSpend,
		PercentUsed: s.UsagePercent, IsOverBudget: s.IsOverBudget,
	}, nil
}

// MySubscription is the resolver for the mySubscription field.
func (r *queryResolver) MySubscription(ctx context.Context) (*model.UserSubscription, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	sub, err := r.SubscriptionSvc.GetUserSubscription(ctx, id)
	if err != nil || sub == nil {
		return nil, nil
	}
	return &model.UserSubscription{
		ID: sub.ID.String(), UserID: uid, PlanID: sub.PlanID.String(),
		Status: sub.Status, CurrentPeriodStart: sub.CurrentPeriodStart,
		CurrentPeriodEnd: sub.CurrentPeriodEnd,
	}, nil
}

// MyOrders is the resolver for the myOrders field.
func (r *queryResolver) MyOrders(ctx context.Context) ([]*model.Order, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	orders, err := r.Payment.GetUserOrders(ctx, id)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Order, len(orders))
	for i, o := range orders {
		out[i] = &model.Order{
			ID: o.ID.String(), OrderNo: o.OrderNo,
			Amount: o.Amount, Currency: o.Currency,
			Status: o.Status, PaymentMethod: o.PaymentMethod,
			CreatedAt: o.CreatedAt,
		}
	}
	return out, nil
}

// MyTasks is the resolver for the myTasks field.
func (r *queryResolver) MyTasks(ctx context.Context, page *int, pageSize *int) (*model.TaskConnection, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	p, ps := valInt(page, 1), valInt(pageSize, 20)
	tasks, total, err := r.TaskService.ListTasks(ctx, id, "", ps, (p-1)*ps)
	if err != nil {
		return &model.TaskConnection{Data: []*model.Task{}, Total: 0}, nil
	}
	out := make([]*model.Task, len(tasks))
	for i := range tasks {
		out[i] = asyncTaskToGQL(&tasks[i])
	}
	return &model.TaskConnection{Data: out, Total: int(total)}, nil
}

// MyAnomalyDetection is the resolver for the myAnomalyDetection field.
func (r *queryResolver) MyAnomalyDetection(ctx context.Context) (*model.AnomalyResult, error) {
	uid, _ := directives.UserIDFromContext(ctx)
	id, _ := uuid.Parse(uid)
	result, err := r.Billing.DetectCostAnomaly(ctx, id, 30, 2.0)
	if err != nil {
		return &model.AnomalyResult{HasAnomaly: false}, nil
	}
	return &model.AnomalyResult{HasAnomaly: result.IsAnomaly, Message: &result.Message}, nil
}

// MyRedeemHistory is the resolver for the myRedeemHistory field.
func (r *queryResolver) MyRedeemHistory(ctx context.Context) ([]*model.RedeemRecord, error) {
	uid, err := directives.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	userID, _ := uuid.Parse(uid)
	records, err := r.RedeemSvc.UserHistory(userID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.RedeemRecord, len(records))
	for i, rc := range records {
		out[i] = &model.RedeemRecord{
			ID: rc.ID.String(), Code: rc.Code,
			CreditAmount: rc.CreditAmount, RedeemedAt: rc.UpdatedAt,
		}
	}
	return out, nil
}

// Dashboard is the resolver for the dashboard field.
func (r *queryResolver) Dashboard(ctx context.Context) (*model.Dashboard, error) {
	activeUsers, _ := r.UserSvc.CountActiveUsers(ctx, monthStart())
	sysSummary, _ := r.Billing.GetSystemUsageSummary(ctx, monthStart(), time.Now())
	totalReq := 0
	totalTokens := 0
	totalCost := 0.0
	successRate := 0.0
	if sysSummary != nil {
		totalReq = int(sysSummary.TotalRequests)
		totalTokens = int(sysSummary.TotalTokens)
		totalCost = sysSummary.TotalCost
		successRate = sysSummary.SuccessRate
	}
	return &model.Dashboard{
		TotalRequests: totalReq, SuccessRate: successRate,
		TotalTokens: totalTokens, TotalCost: totalCost,
		ActiveUsers: int(activeUsers),
	}, nil
}

// UsageChart is the resolver for the usageChart field.
func (r *queryResolver) UsageChart(ctx context.Context, days *int) ([]*model.UsageChartPoint, error) {
	d := valInt(days, 30)
	usage, err := r.Billing.GetSystemDailyUsage(ctx, d)
	if err != nil {
		return nil, err
	}
	out := make([]*model.UsageChartPoint, len(usage))
	for i, u := range usage {
		out[i] = &model.UsageChartPoint{Date: u.Date, Requests: int(u.Requests), Tokens: int(u.Tokens), Cost: u.Cost}
	}
	return out, nil
}

// ProviderStats is the resolver for the providerStats field.
func (r *queryResolver) ProviderStats(ctx context.Context) ([]*model.ProviderStats, error) {
	usage, err := r.Billing.GetSystemUsageByProvider(ctx, monthStart(), time.Now())
	if err != nil {
		return nil, err
	}
	out := make([]*model.ProviderStats, len(usage))
	for i, u := range usage {
		out[i] = &model.ProviderStats{ProviderName: u.ProviderName, Requests: int(u.Requests), Tokens: int(u.Tokens), TotalCost: u.Cost}
	}
	return out, nil
}

// ModelStats is the resolver for the modelStats field.
func (r *queryResolver) ModelStats(ctx context.Context) ([]*model.ModelStats, error) {
	usage, err := r.Billing.GetSystemUsageByModel(ctx, monthStart(), time.Now())
	if err != nil {
		return nil, err
	}
	out := make([]*model.ModelStats, len(usage))
	for i, u := range usage {
		out[i] = &model.ModelStats{ModelName: u.ModelName, Requests: int(u.Requests), TotalCost: u.Cost}
	}
	return out, nil
}

// Plans is the resolver for the plans field.
func (r *queryResolver) Plans(ctx context.Context) ([]*model.Plan, error) {
	plans, err := r.SubscriptionSvc.ListPlans(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Plan, len(plans))
	for i, p := range plans {
		var features *string
		if p.Features != "" {
			features = &p.Features
		}
		out[i] = &model.Plan{
			ID: p.ID.String(), Name: p.Name, PriceMonth: p.PriceMonth,
			TokenLimit: int(p.TokenLimit), RateLimit: p.RateLimit,
			Features: features, IsActive: p.IsActive,
		}
	}
	return out, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, q *string, page *int, pageSize *int) (*model.UserConnection, error) {
	var users []models.User
	var err error
	if q != nil && *q != "" {
		users, err = r.UserSvc.SearchUsers(ctx, *q)
	} else {
		users, err = r.UserSvc.ListUsers(ctx)
	}
	if err != nil {
		return nil, err
	}
	p := valInt(page, 1)
	ps := valInt(pageSize, 20)
	total := len(users)
	start := (p - 1) * ps
	end := start + ps
	if start > total {
		start = total
	}
	if end > total {
		end = total
	}
	paged := users[start:end]
	out := make([]*model.UserListItem, len(paged))
	for i := range paged {
		out[i] = userToListItem(&paged[i])
	}
	return &model.UserConnection{Data: out, Total: total}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.UserDetail, error) {
	uid, _ := uuid.Parse(id)
	u, err := r.UserSvc.GetByID(ctx, uid)
	if err != nil {
		return nil, fmt.Errorf("user not found")
	}
	ud := &model.UserDetail{
		ID: u.ID.String(), Email: u.Email, Name: u.Name,
		Role: u.Role, IsActive: u.IsActive,
		CreatedAt: u.CreatedAt,
	}
	summary, _ := r.Billing.GetUsageSummary(ctx, uid, monthStart(), time.Now())
	if summary != nil {
		ud.UsageMonth = &model.UserMonthlyUsage{
			TotalRequests: int(summary.TotalRequests),
			TotalTokens:   int(summary.TotalTokens),
			TotalCost:     summary.TotalCost,
		}
	}
	return ud, nil
}

// UserUsage is the resolver for the userUsage field.
func (r *queryResolver) UserUsage(ctx context.Context, id string, days *int) ([]*model.DailyStats, error) {
	uid, _ := uuid.Parse(id)
	d := valInt(days, 30)
	usage, err := r.Billing.GetDailyUsage(ctx, uid, d)
	if err != nil {
		return nil, err
	}
	out := make([]*model.DailyStats, len(usage))
	for i, u := range usage {
		out[i] = &model.DailyStats{Date: u.Date, Requests: int(u.Requests), TotalTokens: int(u.Tokens), TotalCost: u.Cost}
	}
	return out, nil
}

// UserAPIKeys is the resolver for the userApiKeys field.
func (r *queryResolver) UserAPIKeys(ctx context.Context, id string) ([]*model.APIKey, error) {
	uid, _ := uuid.Parse(id)
	keys, err := r.UserSvc.GetAPIKeys(ctx, uid)
	if err != nil {
		return nil, err
	}
	out := make([]*model.APIKey, len(keys))
	for i := range keys {
		out[i] = apiKeyToGQL(&keys[i])
	}
	return out, nil
}

// Providers is the resolver for the providers field.
func (r *queryResolver) Providers(ctx context.Context) ([]*model.Provider, error) {
	providers, err := r.Router.GetAllProviders(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Provider, len(providers))
	for i := range providers {
		out[i] = providerToGQL(&providers[i])
	}
	return out, nil
}

// ProviderAPIKeys is the resolver for the providerApiKeys field.
func (r *queryResolver) ProviderAPIKeys(ctx context.Context, providerID string) ([]*model.ProviderAPIKey, error) {
	pid, _ := uuid.Parse(providerID)
	keys, err := r.Router.GetAllProviderAPIKeys(ctx, pid)
	if err != nil {
		return nil, err
	}
	out := make([]*model.ProviderAPIKey, len(keys))
	for i := range keys {
		out[i] = providerAPIKeyToGQL(&keys[i])
	}
	return out, nil
}

// Models is the resolver for the models field.
func (r *queryResolver) Models(ctx context.Context, providerID string) ([]*model.Model, error) {
	pid, err := uuid.Parse(providerID)
	if err != nil {
		return nil, fmt.Errorf("invalid provider id")
	}
	var dbModels []models.Model
	if err := r.DB.Where("provider_id = ?", pid).Order("name ASC").Find(&dbModels).Error; err != nil {
		return nil, fmt.Errorf("failed to query models: %w", err)
	}
	out := make([]*model.Model, len(dbModels))
	for i := range dbModels {
		out[i] = modelToGQL(&dbModels[i])
	}
	return out, nil
}

// ProviderHealth is the resolver for the providerHealth field.
func (r *queryResolver) ProviderHealth(ctx context.Context, providerID string) (*model.ProviderHealth, error) {
	pid, _ := uuid.Parse(providerID)
	s, err := r.Health.CheckSingleProvider(ctx, pid)
	if err != nil {
		return nil, err
	}
	var lc *time.Time
	if !s.LastCheck.IsZero() {
		lc = &s.LastCheck
	}
	var em *string
	if s.ErrorMessage != "" {
		em = &s.ErrorMessage
	}
	return &model.ProviderHealth{
		ID: s.ID.String(), Name: s.Name, BaseURL: s.BaseURL,
		IsActive: s.IsActive, IsHealthy: s.IsHealthy, UseProxy: s.UseProxy,
		ResponseTime: float64(s.ResponseTime), LastCheck: lc,
		SuccessRate: s.SuccessRate, ErrorMessage: em,
	}, nil
}

// Proxies is the resolver for the proxies field.
func (r *queryResolver) Proxies(ctx context.Context) ([]*model.Proxy, error) {
	proxies, err := r.Proxy.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Proxy, len(proxies))
	for i := range proxies {
		out[i] = proxyToGQL(&proxies[i])
	}
	return out, nil
}

// Alerts is the resolver for the alerts field.
func (r *queryResolver) Alerts(ctx context.Context, status *string) (*model.AlertConnection, error) {
	s := ""
	if status != nil {
		s = *status
	}
	alerts, total, err := r.Health.GetAlerts(ctx, s, 1, 100)
	if err != nil {
		return &model.AlertConnection{Data: []*model.Alert{}, Total: 0}, nil
	}
	out := make([]*model.Alert, len(alerts))
	for i := range alerts {
		out[i] = alertToGQL(&alerts[i])
	}
	return &model.AlertConnection{Data: out, Total: int(total)}, nil
}

// AlertConfig is the resolver for the alertConfig field.
func (r *queryResolver) AlertConfig(ctx context.Context, targetType string, targetID string) (*model.AlertConfig, error) {
	tid, _ := uuid.Parse(targetID)
	cfg, err := r.Health.GetAlertConfig(ctx, targetType, tid)
	if err != nil || cfg == nil {
		return nil, nil
	}
	var wh, em *string
	if cfg.WebhookURL != "" {
		wh = &cfg.WebhookURL
	}
	if cfg.Email != "" {
		em = &cfg.Email
	}
	idStr := cfg.ID.String()
	return &model.AlertConfig{
		ID: &idStr, TargetType: cfg.TargetType, TargetID: cfg.TargetID.String(),
		IsEnabled: cfg.IsEnabled, FailureThreshold: cfg.FailureThreshold,
		WebhookURL: wh, Email: em,
	}, nil
}

// HealthAPIKeys is the resolver for the healthApiKeys field.
func (r *queryResolver) HealthAPIKeys(ctx context.Context) ([]*model.APIKeyHealth, error) {
	statuses, err := r.Health.GetAPIKeysHealth(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.APIKeyHealth, len(statuses))
	for i, s := range statuses {
		var lc *time.Time
		if !s.LastCheck.IsZero() {
			lc = &s.LastCheck
		}
		out[i] = &model.APIKeyHealth{
			ID: s.ID.String(), ProviderID: s.ProviderID.String(),
			ProviderName: s.ProviderName, KeyPrefix: s.KeyPrefix,
			IsActive: s.IsActive, IsHealthy: s.IsHealthy,
			LastCheck: lc, ResponseTime: float64(s.ResponseTime), SuccessRate: s.SuccessRate,
		}
	}
	return out, nil
}

// HealthProxies is the resolver for the healthProxies field.
func (r *queryResolver) HealthProxies(ctx context.Context) ([]*model.ProxyHealth, error) {
	statuses, err := r.Health.GetProxiesHealth(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.ProxyHealth, len(statuses))
	for i, s := range statuses {
		var lc *time.Time
		if !s.LastCheck.IsZero() {
			lc = &s.LastCheck
		}
		out[i] = &model.ProxyHealth{
			ID: s.ID.String(), URL: s.URL, Type: s.Type, Region: s.Region,
			IsActive: s.IsActive, IsHealthy: s.IsHealthy,
			ResponseTime: float64(s.ResponseTime), LastCheck: lc, SuccessRate: s.SuccessRate,
		}
	}
	return out, nil
}

// HealthProviders is the resolver for the healthProviders field.
func (r *queryResolver) HealthProviders(ctx context.Context) ([]*model.ProviderHealth, error) {
	statuses, err := r.Health.GetProvidersHealth(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.ProviderHealth, len(statuses))
	for i, s := range statuses {
		var lc *time.Time
		if !s.LastCheck.IsZero() {
			lc = &s.LastCheck
		}
		var em *string
		if s.ErrorMessage != "" {
			em = &s.ErrorMessage
		}
		out[i] = &model.ProviderHealth{
			ID: s.ID.String(), Name: s.Name, BaseURL: s.BaseURL,
			IsActive: s.IsActive, IsHealthy: s.IsHealthy, UseProxy: s.UseProxy,
			ResponseTime: float64(s.ResponseTime), LastCheck: lc,
			SuccessRate: s.SuccessRate, ErrorMessage: em,
		}
	}
	return out, nil
}

// HealthHistory is the resolver for the healthHistory field.
func (r *queryResolver) HealthHistory(ctx context.Context) ([]*model.HealthEvent, error) {
	history, err := r.Health.GetHealthHistory(ctx, "", 100)
	if err != nil {
		return []*model.HealthEvent{}, nil
	}
	out := make([]*model.HealthEvent, len(history))
	for i, h := range history {
		var msg *string
		if h.ErrorMessage != "" {
			msg = &h.ErrorMessage
		}
		status := "healthy"
		if !h.IsHealthy {
			status = "unhealthy"
		}
		out[i] = &model.HealthEvent{
			ID: h.ID.String(), TargetType: h.TargetType,
			TargetID: h.TargetID.String(), Status: status,
			Message: msg, CreatedAt: h.CreatedAt,
		}
	}
	return out, nil
}

// McpServers is the resolver for the mcpServers field.
func (r *queryResolver) McpServers(ctx context.Context) ([]*model.McpServer, error) {
	servers, err := r.MCP.GetAllServers(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.McpServer, len(servers))
	for i := range servers {
		out[i] = mcpServerToGQL(&servers[i])
	}
	return out, nil
}

// McpServer is the resolver for the mcpServer field.
func (r *queryResolver) McpServer(ctx context.Context, id string) (*model.McpServer, error) {
	sid, _ := uuid.Parse(id)
	server, err := r.MCP.GetServerByID(ctx, sid)
	if err != nil {
		return nil, fmt.Errorf("server not found")
	}
	return mcpServerToGQL(server), nil
}

// McpTools is the resolver for the mcpTools field.
func (r *queryResolver) McpTools(ctx context.Context) ([]*model.McpTool, error) {
	tools, err := r.MCP.GetActiveTools(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.McpTool, len(tools))
	for i := range tools {
		out[i] = mcpToolToGQL(&tools[i])
	}
	return out, nil
}

// McpResources is the resolver for the mcpResources field.
func (r *queryResolver) McpResources(ctx context.Context) ([]*model.McpResource, error) {
	return []*model.McpResource{}, nil
}

// SystemSettings is the resolver for the systemSettings field.
func (r *queryResolver) SystemSettings(ctx context.Context) (*model.SystemSettings, error) {
	all, err := r.SystemConfig.GetAllSettingsDecrypted(ctx)
	if err != nil {
		return &model.SystemSettings{RegistrationMode: r.Config.Registration.Mode}, nil
	}
	return buildSystemSettings(r.Config.Registration.Mode, all), nil
}

// InviteCodes is the resolver for the inviteCodes field.
func (r *queryResolver) InviteCodes(ctx context.Context) ([]*model.InviteCode, error) {
	var codes []models.InviteCode
	if err := r.DB.Order("created_at DESC").Find(&codes).Error; err != nil {
		return nil, err
	}
	out := make([]*model.InviteCode, len(codes))
	for i, c := range codes {
		out[i] = &model.InviteCode{
			ID: c.ID.String(), Code: c.Code, CreatedBy: c.CreatedBy.String(),
			MaxUses: c.MaxUses, UseCount: c.UseCount, ExpiresAt: c.ExpiresAt,
			IsActive: c.IsActive, CreatedAt: c.CreatedAt,
		}
	}
	return out, nil
}

// SystemAnomalyDetection is the resolver for the systemAnomalyDetection field.
func (r *queryResolver) SystemAnomalyDetection(ctx context.Context) (*model.AnomalyResult, error) {
	return &model.AnomalyResult{HasAnomaly: false}, nil
}

// RedeemCodes is the resolver for the redeemCodes field.
func (r *queryResolver) RedeemCodes(ctx context.Context, page *int, pageSize *int) (*model.RedeemCodeConnection, error) {
	p, ps := valInt(page, 1), valInt(pageSize, 20)
	codes, total, err := r.RedeemSvc.ListCodes(p, ps)
	if err != nil {
		return nil, err
	}
	out := make([]*model.RedeemCode, len(codes))
	for i, c := range codes {
		var usedBy, planID *string
		if c.UsedByID != nil {
			s := c.UsedByID.String()
			usedBy = &s
		}
		if c.PlanID != nil {
			s := c.PlanID.String()
			planID = &s
		}
		out[i] = &model.RedeemCode{
			ID: c.ID.String(), Code: c.Code, Type: c.Type,
			CreditAmount: c.CreditAmount, PlanID: planID,
			PlanDays: c.PlanDays,
			UsedBy:   usedBy, UsedAt: c.UsedAt,
			ExpiresAt: c.ExpiresAt, IsActive: c.IsActive,
			BatchID: c.BatchID, Note: &c.Note, CreatedAt: c.CreatedAt,
		}
	}
	return &model.RedeemCodeConnection{Nodes: out, Total: int(total)}, nil
}

// ActiveAnnouncements is the resolver for the activeAnnouncements field.
func (r *queryResolver) ActiveAnnouncements(ctx context.Context) ([]*model.Announcement, error) {
	list, err := r.AnnouncementSvc.GetActive(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Announcement, len(list))
	for i := range list {
		out[i] = announcementToGQL(&list[i])
	}
	return out, nil
}

// Announcements is the resolver for the announcements field.
func (r *queryResolver) Announcements(ctx context.Context) ([]*model.Announcement, error) {
	list, err := r.AnnouncementSvc.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Announcement, len(list))
	for i := range list {
		out[i] = announcementToGQL(&list[i])
	}
	return out, nil
}

// Coupons is the resolver for the coupons field.
func (r *queryResolver) Coupons(ctx context.Context) ([]*model.Coupon, error) {
	list, err := r.CouponSvc.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Coupon, len(list))
	for i := range list {
		out[i] = couponToGQL(&list[i])
	}
	return out, nil
}

// Coupon is the resolver for the coupon field.
func (r *queryResolver) Coupon(ctx context.Context, id string) (*model.Coupon, error) {
	cid, _ := uuid.Parse(id)
	c, err := r.CouponSvc.GetByID(ctx, cid)
	if err != nil {
		return nil, fmt.Errorf("coupon not found")
	}
	return couponToGQL(c), nil
}

// Documents is the resolver for the documents field.
func (r *queryResolver) Documents(ctx context.Context) ([]*model.Document, error) {
	list, err := r.DocumentSvc.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Document, len(list))
	for i := range list {
		out[i] = documentToGQL(&list[i])
	}
	return out, nil
}

// PublishedDocuments is the resolver for the publishedDocuments field.
func (r *queryResolver) PublishedDocuments(ctx context.Context) ([]*model.Document, error) {
	list, err := r.DocumentSvc.GetPublished(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Document, len(list))
	for i := range list {
		out[i] = documentToGQL(&list[i])
	}
	return out, nil
}

// Document is the resolver for the document field.
func (r *queryResolver) Document(ctx context.Context, id string) (*model.Document, error) {
	did, _ := uuid.Parse(id)
	d, err := r.DocumentSvc.GetByID(ctx, did)
	if err != nil {
		return nil, fmt.Errorf("document not found")
	}
	return documentToGQL(d), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
