package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"llm-router-platform/internal/graphql/model"
)

// FeatureGates is the resolver for the featureGates field.
func (r *queryResolver) FeatureGates(ctx context.Context) ([]*model.FeatureGate, error) {
	cfg := r.Config()
	gates := cfg.FeatureGates.ListGates()

	result := make([]*model.FeatureGate, len(gates))
	for i, g := range gates {
		result[i] = &model.FeatureGate{
			Name:        g.Name,
			Enabled:     g.Enabled,
			Category:    g.Category,
			Description: g.Description,
			EnvVar:      g.EnvVar,
		}
	}
	return result, nil
}
