package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"llm-router-platform/internal/graphql/directives"
	"llm-router-platform/internal/graphql/model"
	gdbModels "llm-router-platform/internal/models"
	"llm-router-platform/internal/service/dlp"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// UpdateDlpConfig is the resolver for the updateDlpConfig field.
func (r *mutationResolver) UpdateDlpConfig(ctx context.Context, input model.UpdateDlpConfigInput) (*model.DlpConfig, error) {
	userID, err := directives.UserIDFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthorized")
	}
	if err = r.RequireProjectRole(ctx, userID, input.ProjectID, "OWNER", "ADMIN"); err != nil {
		return nil, err
	}

	var dlpConfig gdbModels.DlpConfig
	err = r.DB.Where("project_id = ?", input.ProjectID).First(&dlpConfig).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			// Create a new one
			dlpConfig = gdbModels.DlpConfig{
				BaseModel:       gdbModels.BaseModel{ID: uuid.New()},
				ProjectID:       uuid.MustParse(input.ProjectID),
				IsEnabled:       false,
				Strategy:        string(dlp.StrategyRedact),
				MaskEmails:      true,
				MaskPhones:      true,
				MaskCreditCards: true,
				MaskSSN:         true,
				MaskApiKeys:     true,
				CustomRegex:     []string{},
			}
		} else {
			return nil, fmt.Errorf("failed to fetch dlp config: %v", err)
		}
	}

	if input.IsEnabled != nil {
		dlpConfig.IsEnabled = *input.IsEnabled
	}
	if input.Strategy != nil {
		dlpConfig.Strategy = string(*input.Strategy)
	}
	if input.MaskEmails != nil {
		dlpConfig.MaskEmails = *input.MaskEmails
	}
	if input.MaskPhones != nil {
		dlpConfig.MaskPhones = *input.MaskPhones
	}
	if input.MaskCreditCards != nil {
		dlpConfig.MaskCreditCards = *input.MaskCreditCards
	}
	if input.MaskSsn != nil {
		dlpConfig.MaskSSN = *input.MaskSsn
	}
	if input.MaskAPIKeys != nil {
		dlpConfig.MaskApiKeys = *input.MaskAPIKeys
	}
	if input.CustomRegex != nil {
		dlpConfig.CustomRegex = input.CustomRegex
	}

	if err := r.DB.Save(&dlpConfig).Error; err != nil {
		return nil, fmt.Errorf("failed to update dlp config: %v", err)
	}

	return mapDlpConfig(&dlpConfig), nil
}

// GetDlpConfig is the resolver for the getDlpConfig field.
func (r *queryResolver) GetDlpConfig(ctx context.Context, projectID string) (*model.DlpConfig, error) {
	userID, err := directives.UserIDFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthorized")
	}
	if err = r.RequireProjectRole(ctx, userID, projectID, "OWNER", "ADMIN", "MEMBER"); err != nil {
		return nil, err
	}

	var dlpConfig gdbModels.DlpConfig
	err = r.DB.Where("project_id = ?", projectID).First(&dlpConfig).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			// Return a default config mapping, without saving to DB yet to save space
			return &model.DlpConfig{
				ID:              uuid.New().String(),
				ProjectID:       projectID,
				IsEnabled:       false,
				Strategy:        model.DlpStrategyRedact,
				MaskEmails:      true,
				MaskPhones:      true,
				MaskCreditCards: true,
				MaskSsn:         true,
				MaskAPIKeys:     true,
				CustomRegex:     []string{},
				CreatedAt:       time.Now(),
				UpdatedAt:       time.Now(),
			}, nil
		}
		return nil, fmt.Errorf("failed to fetch dlp config: %v", err)
	}

	return mapDlpConfig(&dlpConfig), nil
}

// TestDlpRedaction is the resolver for the testDlpRedaction field.
func (r *queryResolver) TestDlpRedaction(ctx context.Context, projectID string, input string) (*model.DlpTestResult, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}
	if err := r.RequireProjectRole(ctx, userID, projectID, "OWNER", "ADMIN", "MEMBER"); err != nil {
		return nil, err
	}

	var dlpConfig gdbModels.DlpConfig
	err := r.DB.Where("project_id = ?", projectID).First(&dlpConfig).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			// Pseudo config
			dlpConfig = gdbModels.DlpConfig{
				IsEnabled:       true, // enable in sandbox to show what it would do? Sandbox defaults to testing the specific rules given, wait, let's treat not found as all defaults ENABLED so user can see what the defaults do
				Strategy:        string(dlp.StrategyRedact),
				MaskEmails:      true,
				MaskPhones:      true,
				MaskCreditCards: true,
				MaskSSN:         true,
				MaskApiKeys:     true,
			}
		} else {
			return nil, fmt.Errorf("failed to fetch dlp config: %v", err)
		}
	} else {
		// Even if not enabled in production, the sandbox test should always apply the logic to show the "what-if" result!
		dlpConfig.IsEnabled = true
	}

	hasPII := dlp.HasPII(input, &dlpConfig)
	scrubbedText := input
	blocked := false

	if dlpConfig.Strategy == string(dlp.StrategyBlock) && hasPII {
		blocked = true
		scrubbedText = "[BLOCKED BY DLP]"
	} else if dlpConfig.Strategy == string(dlp.StrategyRedact) {
		scrubbedText = dlp.ScrubText(input, &dlpConfig)
	}

	return &model.DlpTestResult{
		OriginalText: input,
		ScrubbedText: scrubbedText,
		HasPii:       hasPII,
		Blocked:      blocked,
	}, nil
}
