package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"llm-router-platform/internal/graphql/model"
	gdbModels "llm-router-platform/internal/models"

	"github.com/google/uuid"
)

// CreateWebhookEndpoint is the resolver for the createWebhookEndpoint field.
func (r *mutationResolver) CreateWebhookEndpoint(ctx context.Context, input model.CreateWebhookEndpointInput) (*model.WebhookEndpoint, error) {
	projectID, err := uuid.Parse(input.ProjectID)
	if err != nil {
		return nil, err
	}
	var desc string
	if input.Description != nil {
		desc = *input.Description
	}
	endpoint, err := r.WebhookSvc.CreateEndpoint(ctx, projectID, input.URL, input.Events, desc)
	if err != nil {
		return nil, err
	}
	return mapWebhookEndpoint(endpoint, true), nil // include secret once upon creation
}

// UpdateWebhookEndpoint is the resolver for the updateWebhookEndpoint field.
func (r *mutationResolver) UpdateWebhookEndpoint(ctx context.Context, id string, input model.UpdateWebhookEndpointInput) (*model.WebhookEndpoint, error) {
	endpointID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}
	var urlStr, desc string
	var events []string
	var isActive bool

	var current *gdbModels.WebhookEndpoint
	current, err = r.WebhookSvc.GetEndpoint(ctx, endpointID)
	if err != nil {
		return nil, err
	}

	urlStr = current.URL
	events = current.Events
	isActive = current.IsActive
	desc = current.Description

	if input.URL != nil {
		urlStr = *input.URL
	}
	if input.Events != nil {
		events = input.Events
	}
	if input.IsActive != nil {
		isActive = *input.IsActive
	}
	if input.Description != nil {
		desc = *input.Description
	}

	endpoint, err := r.WebhookSvc.UpdateEndpoint(ctx, endpointID, urlStr, events, isActive, desc)
	if err != nil {
		return nil, err
	}
	return mapWebhookEndpoint(endpoint, false), nil
}

// DeleteWebhookEndpoint is the resolver for the deleteWebhookEndpoint field.
func (r *mutationResolver) DeleteWebhookEndpoint(ctx context.Context, id string) (bool, error) {
	endpointID, err := uuid.Parse(id)
	if err != nil {
		return false, err
	}
	if err := r.WebhookSvc.DeleteEndpoint(ctx, endpointID); err != nil {
		return false, err
	}
	return true, nil
}

// TestWebhookEndpoint is the resolver for the testWebhookEndpoint field.
func (r *mutationResolver) TestWebhookEndpoint(ctx context.Context, id string) (bool, error) {
	endpointID, err := uuid.Parse(id)
	if err != nil {
		return false, err
	}

	endpoint, err := r.WebhookSvc.GetEndpoint(ctx, endpointID)
	if err != nil {
		return false, err
	}

	payload := map[string]interface{}{
		"event":     "ping",
		"timestamp": endpoint.CreatedAt.Unix(),
		"message":   "This is a test logic execution from LLM Router Platform",
		"endpoint":  endpoint.ID.String(),
	}

	err = r.WebhookSvc.DispatchEvent(ctx, endpoint.ProjectID, "ping", payload)
	if err != nil {
		return false, err
	}
	return true, nil
}

// Webhooks is the resolver for the webhooks field.
func (r *queryResolver) Webhooks(ctx context.Context, projectID string) ([]*model.WebhookEndpoint, error) {
	pID, err := uuid.Parse(projectID)
	if err != nil {
		return nil, err
	}
	endpoints, err := r.WebhookSvc.GetEndpoints(ctx, pID)
	if err != nil {
		return nil, err
	}
	var res []*model.WebhookEndpoint
	for _, e := range endpoints {
		res = append(res, mapWebhookEndpoint(e, false))
	}
	return res, nil
}

// WebhookDeliveries is the resolver for the webhookDeliveries field.
func (r *queryResolver) WebhookDeliveries(ctx context.Context, endpointID string, limit *int) ([]*model.WebhookDelivery, error) {
	eID, err := uuid.Parse(endpointID)
	if err != nil {
		return nil, err
	}
	l := 50
	if limit != nil {
		l = *limit
	}
	deliveries, err := r.WebhookSvc.GetDeliveries(ctx, eID, l)
	if err != nil {
		return nil, err
	}
	var res []*model.WebhookDelivery
	for _, d := range deliveries {
		res = append(res, mapWebhookDelivery(d))
	}
	return res, nil
}
