package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"llm-router-platform/internal/graphql/directives"
	"llm-router-platform/internal/graphql/errs"
	"llm-router-platform/internal/graphql/model"
	gdbModels "llm-router-platform/internal/models"

	"github.com/google/uuid"
)

// webhookMaxDescription bounds the description field so the dialog
// can't shovel an unbounded string into the row. The audit didn't
// flag a specific overflow, but enforcing a sensible cap here is
// cheap and lets the frontend show an inline message rather than
// relying on Postgres truncating server-side.
const webhookMaxDescription = 500

var (
	webhookManagerRoles = []string{"OWNER", "ADMIN"}
	webhookReaderRoles  = []string{"OWNER", "ADMIN", "MEMBER", "READONLY"}
)

// CreateWebhookEndpoint is the resolver for the createWebhookEndpoint field.
//
// H-05: input validation happens BEFORE the service call so failures
// can be surfaced as typed errs.Validation errors with extensions.field.
// The webhook service also validates internally, but its fmt.Errorf
// wrappers get masked to a generic "internal error [...]" by the
// GraphQL error presenter (see handler.go), which left the dialog
// silent for users supplying a private/loopback URL.
func (r *mutationResolver) CreateWebhookEndpoint(ctx context.Context, input model.CreateWebhookEndpointInput) (*model.WebhookEndpoint, error) {
	projectID, err := uuid.Parse(input.ProjectID)
	if err != nil {
		return nil, errs.Validation("projectId", "Project ID is not valid")
	}
	if err := r.requireWebhookProjectRole(ctx, projectID, webhookManagerRoles...); err != nil {
		return nil, err
	}

	// Validate the URL up-front. Mirrors the dial-time SSRF guard but
	// returns a structured error the form can pin to the URL field.
	if err := validateWebhookURLOrFail(input.URL); err != nil {
		return nil, err
	}
	if len(input.Events) == 0 {
		return nil, errs.Validation("events", "Select at least one event to subscribe to")
	}
	var desc string
	if input.Description != nil {
		desc = *input.Description
	}
	if len(desc) > webhookMaxDescription {
		return nil, errs.Validation("description", "Description is too long")
	}
	isActive := true
	if input.IsActive != nil {
		isActive = *input.IsActive
	}
	endpoint, err := r.WebhookSvc.CreateEndpoint(ctx, projectID, input.URL, input.Events, isActive, desc)
	if err != nil {
		return nil, err
	}
	return mapWebhookEndpoint(endpoint, true), nil // include secret once upon creation
}

// UpdateWebhookEndpoint is the resolver for the updateWebhookEndpoint field.
//
// H-05: as with CreateWebhookEndpoint, we validate user-supplied inputs
// up-front into typed errs.Validation errors so the dialog can show
// inline messages instead of getting silently dropped by the
// internal-error mask.
func (r *mutationResolver) UpdateWebhookEndpoint(ctx context.Context, id string, input model.UpdateWebhookEndpointInput) (*model.WebhookEndpoint, error) {
	endpointID, err := uuid.Parse(id)
	if err != nil {
		return nil, errs.Validation("id", "Webhook ID is not valid")
	}
	var urlStr, desc string
	var events []string
	var isActive bool

	var current *gdbModels.WebhookEndpoint
	current, err = r.WebhookSvc.GetEndpoint(ctx, endpointID)
	if err != nil {
		return nil, err
	}
	if err := r.requireWebhookProjectRole(ctx, current.ProjectID, webhookManagerRoles...); err != nil {
		return nil, err
	}

	urlStr = current.URL
	events = current.Events
	isActive = current.IsActive
	desc = current.Description

	if input.URL != nil {
		// Only re-validate when the user is actually changing the URL.
		// Untouched fields shouldn't be re-checked against the live DNS.
		if *input.URL != current.URL {
			if err := validateWebhookURLOrFail(*input.URL); err != nil {
				return nil, err
			}
		}
		urlStr = *input.URL
	}
	if input.Events != nil {
		if len(input.Events) == 0 {
			return nil, errs.Validation("events", "Select at least one event to subscribe to")
		}
		events = input.Events
	}
	if input.IsActive != nil {
		isActive = *input.IsActive
	}
	if input.Description != nil {
		if len(*input.Description) > webhookMaxDescription {
			return nil, errs.Validation("description", "Description is too long")
		}
		desc = *input.Description
	}

	endpoint, err := r.WebhookSvc.UpdateEndpoint(ctx, endpointID, urlStr, events, isActive, desc)
	if err != nil {
		return nil, err
	}
	return mapWebhookEndpoint(endpoint, false), nil
}

// DeleteWebhookEndpoint is the resolver for the deleteWebhookEndpoint field.
func (r *mutationResolver) DeleteWebhookEndpoint(ctx context.Context, id string) (bool, error) {
	endpointID, err := uuid.Parse(id)
	if err != nil {
		return false, err
	}
	endpoint, err := r.WebhookSvc.GetEndpoint(ctx, endpointID)
	if err != nil {
		return false, err
	}
	if err := r.requireWebhookProjectRole(ctx, endpoint.ProjectID, webhookManagerRoles...); err != nil {
		return false, err
	}
	if err := r.WebhookSvc.DeleteEndpoint(ctx, endpointID); err != nil {
		return false, err
	}
	return true, nil
}

// TestWebhookEndpoint is the resolver for the testWebhookEndpoint field.
func (r *mutationResolver) TestWebhookEndpoint(ctx context.Context, id string) (bool, error) {
	endpointID, err := uuid.Parse(id)
	if err != nil {
		return false, err
	}

	endpoint, err := r.WebhookSvc.GetEndpoint(ctx, endpointID)
	if err != nil {
		return false, err
	}

	if err := r.requireWebhookProjectRole(ctx, endpoint.ProjectID, webhookManagerRoles...); err != nil {
		return false, err
	}

	payload := map[string]interface{}{
		"event":     "ping",
		"timestamp": endpoint.CreatedAt.Unix(),
		"message":   "This is a test logic execution from LLM Router Platform",
		"endpoint":  endpoint.ID.String(),
	}

	err = r.WebhookSvc.DispatchEvent(ctx, endpoint.ProjectID, "ping", payload)
	if err != nil {
		return false, err
	}
	return true, nil
}

// Webhooks is the resolver for the webhooks field.
func (r *queryResolver) Webhooks(ctx context.Context, projectID string) ([]*model.WebhookEndpoint, error) {
	pID, err := uuid.Parse(projectID)
	if err != nil {
		return nil, err
	}
	if err := r.requireWebhookProjectRole(ctx, pID, webhookReaderRoles...); err != nil {
		return nil, err
	}
	endpoints, err := r.WebhookSvc.GetEndpoints(ctx, pID)
	if err != nil {
		return nil, err
	}
	var res []*model.WebhookEndpoint
	for _, e := range endpoints {
		res = append(res, mapWebhookEndpoint(e, false))
	}
	return res, nil
}

// WebhookDeliveries is the resolver for the webhookDeliveries field.
func (r *queryResolver) WebhookDeliveries(ctx context.Context, endpointID string, limit *int) ([]*model.WebhookDelivery, error) {
	eID, err := uuid.Parse(endpointID)
	if err != nil {
		return nil, err
	}
	endpoint, err := r.WebhookSvc.GetEndpoint(ctx, eID)
	if err != nil {
		return nil, err
	}
	if err := r.requireWebhookProjectRole(ctx, endpoint.ProjectID, webhookReaderRoles...); err != nil {
		return nil, err
	}
	l := 50
	if limit != nil && *limit > 0 {
		l = *limit
	}
	if l > 100 {
		l = 100
	}
	deliveries, err := r.WebhookSvc.GetDeliveries(ctx, eID, l)
	if err != nil {
		return nil, err
	}
	var res []*model.WebhookDelivery
	for _, d := range deliveries {
		res = append(res, mapWebhookDelivery(d))
	}
	return res, nil
}

func (r *Resolver) requireWebhookProjectRole(ctx context.Context, projectID uuid.UUID, roles ...string) error {
	userID, err := directives.UserIDFromContext(ctx)
	if err != nil || userID == "" {
		return fmt.Errorf("unauthenticated")
	}
	if err := r.UserSvc.RequireProjectRole(ctx, userID, projectID.String(), roles...); err != nil {
		return fmt.Errorf("forbidden: access denied")
	}
	return nil
}
