package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"llm-router-platform/internal/graphql/model"
	"llm-router-platform/internal/models"
)

// ClearSemanticCache is the resolver for the clearSemanticCache field.
func (r *mutationResolver) ClearSemanticCache(ctx context.Context, id string) (bool, error) {
	err := r.SemanticCache.DeleteCache(ctx, id)
	return err == nil, err
}

// ClearAllSemanticCaches is the resolver for the clearAllSemanticCaches field.
func (r *mutationResolver) ClearAllSemanticCaches(ctx context.Context) (bool, error) {
	err := r.SemanticCache.DeleteAllCaches(ctx)
	return err == nil, err
}

// UpdateCacheConfig is the resolver for the updateCacheConfig field.
func (r *mutationResolver) UpdateCacheConfig(ctx context.Context, input model.CacheConfigInput) (*model.CacheConfig, error) {
	var cfg models.CacheConfig
	if err := r.DB.WithContext(ctx).First(&cfg).Error; err != nil {
		// Create new config
		cfg = models.CacheConfig{
			IsEnabled:           input.IsEnabled,
			SimilarityThreshold: input.SimilarityThreshold,
			DefaultTTLMinutes:   input.DefaultTTLMinutes,
			EmbeddingModel:      input.EmbeddingModel,
			MaxCacheSize:        input.MaxCacheSize,
		}
		if err := r.DB.WithContext(ctx).Create(&cfg).Error; err != nil {
			return nil, err
		}
	} else {
		cfg.IsEnabled = input.IsEnabled
		cfg.SimilarityThreshold = input.SimilarityThreshold
		cfg.DefaultTTLMinutes = input.DefaultTTLMinutes
		cfg.EmbeddingModel = input.EmbeddingModel
		cfg.MaxCacheSize = input.MaxCacheSize
		if err := r.DB.WithContext(ctx).Save(&cfg).Error; err != nil {
			return nil, err
		}
	}
	return cacheConfigToGQL(&cfg), nil
}

// SemanticCaches is the resolver for the semanticCaches field.
func (r *queryResolver) SemanticCaches(ctx context.Context, limit *int, offset *int) ([]*model.SemanticCache, error) {
	l := 50
	if limit != nil {
		l = *limit
	}
	o := 0
	if offset != nil {
		o = *offset
	}

	caches, err := r.SemanticCache.ListCaches(ctx, l, o)
	if err != nil {
		return nil, err
	}

	var result []*model.SemanticCache
	for _, c := range caches {
		result = append(result, &model.SemanticCache{
			ID:        c.ID.String(),
			Hash:      c.Hash,
			Provider:  c.Provider,
			Model:     c.Model,
			HitCount:  c.HitCount,
			CreatedAt: c.CreatedAt,
		})
	}
	return result, nil
}

// CacheStats is the resolver for the cacheStats field.
func (r *queryResolver) CacheStats(ctx context.Context) (*model.CacheStats, error) {
	total, hits, err := r.SemanticCache.GetStats(ctx)
	if err != nil {
		return nil, err
	}
	return &model.CacheStats{
		TotalCaches: total,
		TotalHits:   hits,
	}, nil
}

// CacheConfig is the resolver for the cacheConfig field.
func (r *queryResolver) CacheConfig(ctx context.Context) (*model.CacheConfig, error) {
	var cfg models.CacheConfig
	if err := r.DB.WithContext(ctx).First(&cfg).Error; err != nil {
		// Return defaults
		return &model.CacheConfig{
			ID:                  "default",
			IsEnabled:           true,
			SimilarityThreshold: 0.05,
			DefaultTTLMinutes:   1440,
			EmbeddingModel:      "text-embedding-3-small",
			MaxCacheSize:        10000,
		}, nil
	}
	return cacheConfigToGQL(&cfg), nil
}
