package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"encoding/json"
	"fmt"
	"llm-router-platform/internal/graphql/model"
	"llm-router-platform/internal/models"
	notifSvc "llm-router-platform/internal/service/notification"

	"github.com/google/uuid"
)

// CreateNotificationChannel is the resolver for the createNotificationChannel field.
func (r *mutationResolver) CreateNotificationChannel(ctx context.Context, input model.NotificationChannelInput) (*model.NotificationChannel, error) {
	isEnabled := true
	if input.IsEnabled != nil {
		isEnabled = *input.IsEnabled
	}
	ch := models.NotificationChannel{
		Name:      input.Name,
		Type:      input.Type,
		IsEnabled: isEnabled,
		Config:    input.Config,
	}
	if err := r.DB().WithContext(ctx).Create(&ch).Error; err != nil {
		return nil, fmt.Errorf("failed to create notification channel: %w", err)
	}
	return notifChannelToGQL(&ch), nil
}

// UpdateNotificationChannel is the resolver for the updateNotificationChannel field.
func (r *mutationResolver) UpdateNotificationChannel(ctx context.Context, id string, input model.UpdateNotificationChannelInput) (*model.NotificationChannel, error) {
	uid, _ := uuid.Parse(id)
	var ch models.NotificationChannel
	if err := r.DB().WithContext(ctx).First(&ch, "id = ?", uid).Error; err != nil {
		return nil, fmt.Errorf("channel not found")
	}
	if input.Name != nil {
		ch.Name = *input.Name
	}
	if input.IsEnabled != nil {
		ch.IsEnabled = *input.IsEnabled
	}
	if input.Config != nil {
		ch.Config = *input.Config
	}
	if err := r.DB().WithContext(ctx).Save(&ch).Error; err != nil {
		return nil, fmt.Errorf("failed to update channel: %w", err)
	}
	return notifChannelToGQL(&ch), nil
}

// DeleteNotificationChannel is the resolver for the deleteNotificationChannel field.
func (r *mutationResolver) DeleteNotificationChannel(ctx context.Context, id string) (bool, error) {
	uid, _ := uuid.Parse(id)
	if err := r.DB().WithContext(ctx).Delete(&models.NotificationChannel{}, "id = ?", uid).Error; err != nil {
		return false, fmt.Errorf("failed to delete channel: %w", err)
	}
	return true, nil
}

// TestNotificationChannel is the resolver for the testNotificationChannel field.
func (r *mutationResolver) TestNotificationChannel(ctx context.Context, id string) (bool, error) {
	uid, _ := uuid.Parse(id)
	var ch models.NotificationChannel
	if err := r.DB().WithContext(ctx).First(&ch, "id = ?", uid).Error; err != nil {
		return false, fmt.Errorf("channel not found")
	}

	payload := &notifSvc.AlertPayload{
		TargetType: "system",
		TargetID:   "test",
		AlertType:  "test_notification",
		Message:    "This is a test notification from LLM Router Platform.",
		Severity:   "info",
	}

	var sendErr error
	switch ch.Type {
	case "webhook":
		var cfg struct {
			URL string `json:"url"`
		}
		if err := json.Unmarshal([]byte(ch.Config), &cfg); err != nil {
			return false, fmt.Errorf("invalid webhook config: %w", err)
		}
		wh := notifSvc.NewWebhookChannel(cfg.URL, r.Config().Server.AllowLocalProviders)
		sendErr = wh.Send(ctx, payload)
	case "email":
		var cfg struct {
			Host       string   `json:"host"`
			Port       int      `json:"port"`
			Username   string   `json:"username"`
			Password   string   `json:"password"`
			From       string   `json:"from"`
			Recipients []string `json:"recipients"`
		}
		if err := json.Unmarshal([]byte(ch.Config), &cfg); err != nil {
			return false, fmt.Errorf("invalid email config: %w", err)
		}
		em := notifSvc.NewEmailChannel(notifSvc.EmailConfig{
			Host: cfg.Host, Port: cfg.Port, Username: cfg.Username, Password: cfg.Password, From: cfg.From,
		}, cfg.Recipients)
		sendErr = em.Send(ctx, payload)
	case "dingtalk":
		var cfg struct {
			WebhookURL string `json:"webhook_url"`
			Secret     string `json:"secret"`
		}
		if err := json.Unmarshal([]byte(ch.Config), &cfg); err != nil {
			return false, fmt.Errorf("invalid dingtalk config: %w", err)
		}
		dt := notifSvc.NewDingTalkChannel(cfg.WebhookURL, cfg.Secret, r.Config().Server.AllowLocalProviders)
		sendErr = dt.Send(ctx, payload)
	case "feishu":
		var cfg struct {
			WebhookURL string `json:"webhook_url"`
			Secret     string `json:"secret"`
		}
		if err := json.Unmarshal([]byte(ch.Config), &cfg); err != nil {
			return false, fmt.Errorf("invalid feishu config: %w", err)
		}
		fs := notifSvc.NewFeishuChannel(cfg.WebhookURL, cfg.Secret, r.Config().Server.AllowLocalProviders)
		sendErr = fs.Send(ctx, payload)
	default:
		return false, fmt.Errorf("unknown channel type: %s", ch.Type)
	}

	if sendErr != nil {
		return false, fmt.Errorf("test delivery failed: %w", sendErr)
	}
	return true, nil
}

// NotificationChannels is the resolver for the notificationChannels field.
func (r *queryResolver) NotificationChannels(ctx context.Context) ([]*model.NotificationChannel, error) {
	var channels []models.NotificationChannel
	if err := r.DB().WithContext(ctx).Order("created_at DESC").Find(&channels).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch channels: %w", err)
	}
	out := make([]*model.NotificationChannel, len(channels))
	for i := range channels {
		out[i] = notifChannelToGQL(&channels[i])
	}
	return out, nil
}
